### ISSUE TITLE
Validation to ensure username doesn't contain `\`

### ISSUE THREAD

**Issue by abhinavmpandey08** [aws/eks-anywhere#1073]
Add a preflight validation to ensure the vSphere username doesn't contain `\` as it is treated as an escape character and leads to csi pods being stuck in container creating stage.

A common use case for this is when using AD, users may try to provide `domain\user` as the username which results in this issue.
Users should instead use `user@domain` instead to avoid this error.

**Comment by TerryHowe** [comment]
Is there any work around for this for CSI?

**Comment by TerryHowe** [comment]
We can't escape the escape character or do something like use quoting?

**Comment by abhinavmpandey08** [comment]
We do use quotes around it https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/template-cp.yaml#L554-L581

The thing is for csi secret, we use `cluster-resource-set` which is a CAPI construct. CAPI parses this to create another secret on the workload cluster. But because of the `\`, the parsing fails on CAPI side which results in the secret not being created on the workload cluster. 

I think we would have to patch CAPI to support this? Or maybe we can get away with just escaping the `\` from our end preemptively. Will have to test this to verify.

**Comment by abhinavmpandey08** [comment]
The proper resolution here would be to either surround the creds in single quotes or base64 encode them.

**Comment by chrisdoherty4** [comment]
There are multiple places in the code not correctly handling the creds and are consequently susceptible to the problem.

**Comment by abhinavmpandey08** [comment]
This issue should be resolved with https://github.com/aws/eks-anywhere/pull/1677
