### ISSUE TITLE
VSphereDatacenterConfig 'insecure' value not being used

### ISSUE THREAD

**Issue by smarsh-tim** [aws/eks-anywhere#1117]
**What happened**:
When I set `insecure: true` in my `kind: VSphereDatacenterConfig` resource, that value is not being templated into the vsphere-cloud-config ConfigMap's `vsphere.conf` consumed by the vsphere-cloud-controller-manager DaemonSet.

As such, when vsphere-cloud-controller-manager pods attempt to talk to the vcenter endpoint, if it's using a self-signed certificate, they receive errors. Such as:
```
E0201 04:30:42.449244       1 connection.go:63] Failed to create govmomi client. err: Post "https://vcenter.mydomain.com:443/sdk": x509: certificate signed by unknown authority
E0201 04:30:42.449249       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post "https://vcenter.mydomain.com:443/sdk": x509: certificate signed by unknown authority
E0201 04:30:42.869373       1 connection.go:177] Failed to create new client. err: Post "https://vcenter.mydomain.com:443/sdk": x509: certificate signed by unknown authority
E0201 04:30:42.869402       1 connection.go:63] Failed to create govmomi client. err: Post "https://vcenter.mydomain.com:443/sdk": x509: certificate signed by unknown authority
E0201 04:30:42.869408       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post "https://vcenter.mydomain.com:443/sdk": x509: certificate signed by unknown authority
E0201 04:30:43.454200       1 connection.go:177] Failed to create new client. err: Post "https://vcenter.mydomain.com:443/sdk": x509: certificate signed by unknown authority
E0201 04:30:43.454256       1 connection.go:63] Failed to create govmomi client. err: Post "https://vcenter.mydomain.com:443/sdk": x509: certificate signed by unknown authority
E0201 04:30:43.454273       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post "https://vcenter.mydomain.com:443/sdk": x509: certificate signed by unknown authority
```

This causes cascading affects, such as the CNI failing to load, which causes all the nodes to fail to get to Ready status. Essentially meaning when I run `eksctl anywhere create..`, I get stuck here indefinitely:
```sh
✅ Vsphere Provider setup is valid
✅ Create preflight validations pass
Creating new bootstrap cluster
Installing cluster-api providers on bootstrap cluster
Provider specific setup
Creating new workload cluster
```

### The workaround
_Manually update the value, and restart the pods that use it_

1. Edit the ConfigMap manually
    ```sh
    kubectl edit ConfigMap vsphere-cloud-config -n kube-system
    ```
2. Inject `insecureFlag: true` under `global:`
3. Kill each of the pods for the DaemonSet `vsphere-cloud-controller-manager`

**What you expected to happen**:
I expect when I set `insecure: true` in my EKS cluster yaml configuration, that the ConfigMap vsphere-cloud-config correctly sets `insecureFlag: true` in vsphere.conf. There's an [example here](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-0C202FC5-F973-4D24-B383-DDA27DA49BFA.html)

The results should be something like this:
```yaml
global:
  insecureFlag: true
  secretName: cloud-provider-vsphere-credentials
  secretNamespace: kube-system
  thumbprint: ""
vcenter:
  vcenter.mydomain.com:
    datacenters:
    - 'MyDomain'
    secretName: cloud-provider-vsphere-credentials
    secretNamespace: kube-system
    server: 'vcenter.mydomain.com'
    thumbprint: ''
```

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to create an EKS cluster using a vcenter endpoint that leverages a self-signed certificate.

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
```sh
% eksctl anywhere version
v0.7.0
```
- EKS Distro Release:
```sh
% eksctl version
0.82.0
```

**Comment by TerryHowe** [comment]
I'm still messing with this, but wanted to suggest adding a thumbprint as a work around. That would be more secure than insecure.

**Comment by TerryHowe** [comment]
No problem recreating that. It looks like insecure was removed from here causing the issue https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/template-cp.yaml#L1146

**Comment by TerryHowe** [comment]
The fix has been merged and should be out in the next release. I'm going to close this as resolved and definitely reopen if there is something I've missed. The thumbprint work around is documented here https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/vsphere/#thumbprint-required-if-insecurefalse and I've heard from others that it works
