### ISSUE TITLE
ARM64 Node has run away agetty process

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere#1159]
**What happened**:
Customer created ARM64 cluster and node has agetty process consuming 100% CPU

**What you expected to happen**:
agetty not consuing 100% CPU

**How to reproduce it (as minimally and precisely as possible)**:
Create cluster on ARM64

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.7.0
- EKS Distro Release: v.1.21

https://github.com/aws/eks-anywhere/pull/1158#issuecomment-1030712948

https://user-images.githubusercontent.com/3286998/152662193-f155001e-490b-45d9-8c24-957a48d3963f.png

**Comment by jaxesn** [comment]
I am going to take a look at this one. Looks like a known issue with older versions of systemd/getty which almost def effects al2 which our kind image is based on.  Im suspicious its not an arm specific issue, but ill report back.

**Comment by kingdonb** [comment]
Yep I can't say for sure that it's an ARM64 specific issue, I was running on ARM64 and did not want to omit that from the report because it seems light on support. (The vast majority of things were working, but Homebrew itself isn't supported on arm64 linux and I had to compile it myself to get it working.)

This is Linux-on-ARM64 on bare metal, (not Linux via Docker Desktop on an M1 mac, in case that makes a difference too.)

**Comment by jaxesn** [comment]
@kingdonb totally thanks for the amazing details!

arm64 is something we "added" recently, but do not currently have e2e tests for it so have held off on officially "supporting" it.  This is why we havent published to the arm builds for linux or mac to homebrew or added anything to the docs.  Hearing you go through and replicate success is awesome to hear and adds motivation to prioritizing finalizing our arm support, at least for capd and bootstrap clusters.

For this specific issue, I was able to replicate on my amd64 mac and have a fix coming soon.  Ill expand on the details in my PR.

**Comment by TerryHowe** [comment]
I think the work is done here, PR merged, available in next release.

**Comment by kingdonb** [comment]
Amazing, 🎉  I gave it a shot and this is much better:

<img width="1383" alt="Screen Shot 2022-02-08 at 12 16 29 PM" src="https://user-images.githubusercontent.com/3286998/153040858-123abccd-d08b-4740-bbb3-ff2b33dad5bc.png">

This machine is running 10 capd workload clusters and a management cluster. Looks like there's room for at least another 40 before the control planes would start to overwhelm the node. It's 128GB of RAM with 32 cores, for reference.
