### ISSUE TITLE
Add brew formula update during release

### ISSUE THREAD

**Issue by jaxesn** [aws/eks-anywhere#118]
We publishing new releases we should automatically publish new versions to the aws brew tap.

**Comment by rothgar** [comment]
Two common ways to do this are via the [`brew bump-formula-pr` command](https://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request) or [github actions](https://github.com/marketplace/actions/homebrew-bump-formula)

If we also want to start auto-generating the formula we can look at [goreleaser](https://goreleaser.com/) which can create the formula and bump the version but it's probably a bit heavy for what we need.

FWIW the formula exists here https://github.com/aws/homebrew-tap/blob/master/Formula/eks-anywhere.rb

**Comment by mitalipaygude** [comment]
https://github.com/aws/homebrew-tap/pull/251

**Comment by danbudris** [comment]
https://github.com/aws/homebrew-tap/pull/260

**Comment by mrajashree** [comment]
https://github.com/aws/homebrew-tap/pull/277

**Comment by mitalipaygude** [comment]
Projects #8

**Comment by taneyland** [comment]
Added in #1871
