### ISSUE TITLE
CloudStack integration

### ISSUE THREAD

**Issue by g-gaston** [aws/eks-anywhere#1186]
All of these should be resolved before the first release
- [x] #1187
- [x] #1291
- [x] #1393

**Comment by maxdrib** [comment]
Please add https://github.com/aws/eks-anywhere/issues/1291 to this list

**Comment by maxdrib** [comment]
Please add https://github.com/aws/eks-anywhere/issues/1393 to this list

**Comment by maxdrib** [comment]
This issue can be closed.
