### ISSUE TITLE
Investigate `additionalDetails` field for CloudStack machine API

### ISSUE THREAD

**Issue by g-gaston** [aws/eks-anywhere#1187]
Coming from [this conversation](https://github.com/aws/eks-anywhere/pull/1076#discussion_r801149840)

* What is this field supposed to be used for?
* Can the user specify only random custom UI info (like labels) or can some of this affect how CloudStack behaves? Or both?
* If the user needs to pass here configuration that actually affects the CloudStack logic, can we parametrize them into actual API fields?

**Comment by maxdrib** [comment]
https://github.com/shapeblue/cloudstack/blob/main/api/src/main/java/com/cloud/vm/VmDetailConstants.java lists out some of the explicit labels/details that are allowed by CloudStack. However users can also submit their own labels/details for cloudstack management systems to use when managing the CloudStack VM's

**Comment by vignesh-goutham** [comment]
After discussing more about this, we will be exposing `userCustomDetails` that would allow non-standard key value inputs that are *not* defined [here](https://github.com/shapeblue/cloudstack/blob/main/api/src/main/java/com/cloud/vm/VmDetailConstants.java). Any standard inputs required from user would be evaluated case by case basis, and will be exposed through definitive cluster spec inputs.

**Comment by maxdrib** [comment]
Issue has been addressed - please resolve it
