### ISSUE TITLE
Error when running eksctl anywhere upgrade plan cluster

### ISSUE THREAD

**Issue by rade4404** [aws/eks-anywhere#1190]
**What happened**:

When running the eksctl anywhere upgrade plan cluster command, I receive the following errors.  We are experimenting with AWS EKS Anywhere and am not able to solve these issues.  

[user1:~/projects/eks_anywhere/eks-anywhere-clusters]$ eksctl anywhere upgrade plan cluster -f booger/booger-eks-a-cluster.yaml
Checking new release availability...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x205135c]

goroutine 1 [running]:
github.com/aws/eks-anywhere/pkg/types.(*ChangeDiff).Append(0x0, 0xc00057fc68, 0x1, 0x1)
	/codebuild/output/src643701019/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/types/upgrades.go:29 +0x5c
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.(*upgradeClusterOptions).upgradePlanCluster(0x36d6e60, 0x2ac22a8, 0xc0001a2008, 0x4, 0x23cfee0)
	/codebuild/output/src643701019/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/cmd/eksctl-anywhere/cmd/upgradeplancluster.go:101 +0x645
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.glob..func12(0x36bfce0, 0xc0004552a0, 0x0, 0x2, 0x0, 0x0)
	/codebuild/output/src643701019/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/cmd/eksctl-anywhere/cmd/upgradeplancluster.go:40 +0x4e
github.com/spf13/cobra.(*Command).execute(0x36bfce0, 0xc000455280, 0x2, 0x2, 0x36bfce0, 0xc000455280)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x36be660, 0x8, 0xc000000180, 0x245e7e5)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:895
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.Execute(0x0, 0x0)
	/codebuild/output/src643701019/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/cmd/eksctl-anywhere/cmd/root.go:43 +0x53
main.main()
	/codebuild/output/src643701019/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/cmd/eksctl-anywhere/main.go:29 +0xe5

	
[user1:~/projects/eks_anywhere/eks-anywhere-clusters]$ eksctl anywhere upgrade plan cluster -f booger-workload/booger-workload-eks-a-cluster.yaml
Checking new release availability...
Error: failed to display upgrade plan: failed getting EKS-A cluster to build current cluster Spec: error getting eksa cluster: error: the server doesn't have a resource type "clusters"

**Management Cluster YAML**
`apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: booger
  namespace: default
spec:
  clusterNetwork:
    cni: cilium
    dns:
      resolvConf:
        path: /root/resolv.conf
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: deleted
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: booger
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-etcd
  kubernetesVersion: "1.21"
  managementCluster:
    name: booger
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: booger
  namespace: default
spec:
  datacenter: Playground
  insecure: false
  network: /Playground/network/testing
  server: deleted
  thumbprint: deleted

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: booger-cp
  namespace: default
spec:
  datastore: /Playground/datastore/Managment
  diskGiB: 25
  folder: /Playground/vm/EKS-Control-Plane
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Playground/host/Playground_Management/Resources/EKS-cluster
  template: /Playground/vm/Templates/bottlerocket-v1.21.5-kubernetes-1-21-eks-8-amd64-7dd3792
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
    anywhere.eks.amazonaws.com/managed-by: booger
  name: booger-etcd
  namespace: default
spec:
  datastore: /Playground/datastore/Managment
  diskGiB: 25
  folder: /Playground/vm/EKS-ETCD
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Playground/host/Playground_Management/Resources/EKS-cluster
  template: /Playground/vm/Templates/bottlerocket-v1.21.5-kubernetes-1-21-eks-8-amd64-7dd3792
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: booger
  namespace: default
spec:
  datastore: /Playground/datastore/Managment
  diskGiB: 25
  folder: /Playground/vm/EKS-Management
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Playground/host/Playground_Management/Resources/EKS-cluster
  template: /Playground/vm/Templates/bottlerocket-v1.21.5-kubernetes-1-21-eks-8-amd64-7dd3792
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 

---`

**Workload Cluster YAML**

`apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by: booger
  name: booger-workload
  namespace: default
spec:
  clusterNetwork:
    cni: cilium
    dns:
      resolvConf:
        path: /root/resolv.conf
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: deleted
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-workload-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: booger-workload
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-workload-etcd
  kubernetesVersion: "1.21"
  managementCluster:
    name: booger
  workerNodeGroupConfigurations:
  - count: 4
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-workload
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: booger-workload
  namespace: default
spec:
  datacenter: Playground
  insecure: false
  network: /Playground/network/testing
  server: deleted
  thumbprint: deleted

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
    anywhere.eks.amazonaws.com/managed-by: booger
  name: booger-workload-cp
  namespace: default
spec:
  datastore: /Playground/datastore/Managment
  diskGiB: 25
  folder: /Playground/vm/EKS-Control-Plane
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Playground/host/Playground_Management/Resources/EKS-cluster
  template: /Playground/vm/Templates/bottlerocket-v1.21.5-kubernetes-1-21-eks-8-amd64-7dd3792
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
    anywhere.eks.amazonaws.com/managed-by: booger
  name: booger-workload-etcd
  namespace: default
spec:
  datastore: /Playground/datastore/Managment
  diskGiB: 25
  folder: /Playground/vm/EKS-ETCD
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Playground/host/Playground_Management/Resources/EKS-cluster
  template: /Playground/vm/Templates/bottlerocket-v1.21.5-kubernetes-1-21-eks-8-amd64-7dd3792
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/managed-by: booger
  name: booger-workload
  namespace: default
spec:
  datastore: /Playground/datastore/Managment
  diskGiB: 25
  folder: /Playground/vm/EKS-Management
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: /Playground/host/Playground_Management/Resources/EKS-cluster
  template: /Playground/vm/Templates/bottlerocket-v1.21.5-kubernetes-1-21-eks-8-amd64-7dd3792
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 

---`
**What you expected to happen**:
Should return a list of packages that can be upgraded
**How to reproduce it**:
Deploy a Management Cluster and Workload Cluster
Increase workload cluster worker node number
run: eksctl anywhere upgrade plan cluster -f booger/booger-eks-a-cluster.yaml

**Anything else we need to know?**:

**Environment**:
MacOS 11.6
Docker Desktop version 4.2.0
VMware ESXi, 7.0.3, 19193900

- EKS Anywhere Release: 0.7.0
- EKS Distro Release:  v1.21.6

**Comment by rade4404** [comment]
Running the upgrade without the plan on the workload cluster

[user1:~/projects/eks_anywhere/eks-anywhere-clusters]$ eksctl anywhere upgrade cluster -f booger-workload/booger-workload-eks-a-cluster.yaml
Performing setup and validations
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Control plane and Workload templates validated
❌ Validation failed	{"validation": "vsphere Provider setup is valid", "error": "failed validate machineconfig uniqueness: error getting eksa cluster: error: the server doesn't have a resource type \"clusters\"\n", "remediation": ""}
✅ Nodes ready
✅ Upgrade cluster kubernetes version increment
❌ Validation failed	{"validation": "upgrade preflight validations pass", "error": "validation failed with 5 errors: error getting kubeadmcontrolplane: error: the server doesn't have a resource type \"kubeadmcontrolplanes\"\n,error getting machine deployments: error: the server doesn't have a resource type \"machinedeployments\"\n,error getting clusters crd: Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io \"clusters.cluster.x-k8s.io\" not found\n,error getting clusters: error: the server doesn't have a resource type \"clusters\"\n,error getting eksa cluster: error: the server doesn't have a resource type \"clusters\"\n", "remediation": ""}
Error: failed to upgrade cluster: validations failed

**Comment by mitalipaygude** [comment]
Hello @rade4404 ,

I am going to need to investigate why the `upgrade plan` and `upgrade` commands are having issues here. For the `upgrade plan` command the null pointer could be a potential bug, I am going to tag this issue as a bug for now.

**Comment by mitalipaygude** [comment]
Were you able to create a cluster successfully using the above cluster spec file? Could you also upload the yaml file in the issue here, would be easier for me to reciprocate the issue with the spec file.

**Comment by rade4404** [comment]
Management Cluster

`apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: booger
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
    dns:
      resolvConf:
        path: "/root/resolv.conf"
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: deleted
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: booger
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-etcd
  kubernetesVersion: "1.21"
  managementCluster:
    name: booger
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: booger
spec:
  datacenter: "Playground"
  insecure: false
  network: "testing"
  server:deleted
  thumbprint: deleted

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: booger-cp
spec:
  datastore: "Managment"
  diskGiB: 25
  folder: "EKS-Control-Plane"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Playground/host/Playground_Management/Resources/EKS-cluster"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: booger
spec:
  datastore: "Managment"
  diskGiB: 25
  folder: "EKS-Management"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Playground/host/Playground_Management/Resources/EKS-cluster"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 
    
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: booger-etcd
spec:
  datastore: "Managment"
  diskGiB: 25
  folder: "EKS-ETCD"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Playground/host/Playground_Management/Resources/EKS-cluster"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 
---`

**Workload Cluster**

`apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: booger-workload
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
    dns:
      resolvConf:
        path: "/root/resolv.conf"
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: deleted
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-workload-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: booger-workload
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-workload-etcd
  kubernetesVersion: "1.21"
  managementCluster:
    name: booger
  workerNodeGroupConfigurations:
  - count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: booger-workload
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: booger-workload
spec:
  datacenter: "Playground"
  insecure: false
  network: "testing"
  server: deleted
  thumbprint: deleted

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: booger-workload-cp
spec:
  datastore: "Managment"
  diskGiB: 25
  folder: "EKS-Control-Plane"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Playground/host/Playground_Management/Resources/EKS-cluster"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: booger-workload
spec:
  datastore: "Managment"
  diskGiB: 25
  folder: "EKS-Management"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Playground/host/Playground_Management/Resources/EKS-cluster"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: booger-workload-etcd
spec:
  datastore: "Managment"
  diskGiB: 25
  folder: "EKS-ETCD"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: bottlerocket
  resourcePool: "/Playground/host/Playground_Management/Resources/EKS-cluster"
  users:
  - name: ec2-user
    sshAuthorizedKeys:
    - ssh-rsa 
---`

**Comment by taneyland** [comment]
Hi @rade4404,

Thanks for opening this issue. We will add a fix for the `upgrade plan` bug.

As for upgrading the workload cluster, can you try passing in the `kubeconfig` file of the management cluster (similar to how you passed it in to create the workload cluster)?
From there, you should be able to upgrade the workload cluster.

**Comment by EGmhenze** [comment]
Same issue happening to me. 

mhenze@computer:~$ eksctl anywhere upgrade plan cluster -f ./eks-mhenze-w01/eks-mhenze-w01-eks-a-cluster.yaml
Checking new release availability...
Error: failed to display upgrade plan: failed getting EKS-A cluster to build current cluster Spec: error getting eksa cluster: error: the server doesn't have a resource type "clusters"

**Comment by taneyland** [comment]
Fixed with #1318
