### ISSUE TITLE
What is the difference between management and workload clusters?

### ISSUE THREAD

**Issue by brandonhon** [aws/eks-anywhere#1191]
I am looking at the documentation at https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/ and see there are two different clusters you can spin up. One is a management cluster and the other a workload cluster.

Would someone be able to tell me the difference in these two and why the workload cluster spins up etcd and control plane nodes? I was thinking that the workload cluster would talk back to the management cluster for those.

**Comment by TerryHowe** [comment]
The installer creates or uses a management cluster to create a workload cluster. The management cluster could just be a KinD cluster. If you use thye KinD cluster option, it tears it down when the workload cluster is up. The management cluster is set up to start up Cluster API to create the workload.

As far as etcd goes, the default is to create 3 etcd nodes I think for a production cluster. You can run etcd on the control plane if you like.

**Comment by mitalipaygude** [comment]
Hey Brandon, here's an overview of what we are doing when we spin up these clusters: https://anywhere.eks.amazonaws.com/docs/overview/

To summarize, we create the workload cluster in vSphere, by creating a temporary bootstrap cluster to direct the workload cluster creation. Once the workload cluster is created, the cluster management resources are moved to the workload cluster and the local bootstrap cluster is deleted. 

You can also take a look at the workflow [here](https://anywhere.eks.amazonaws.com/docs/concepts/clusterworkflow/).
