### ISSUE TITLE
NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

### ISSUE THREAD

**Issue by bhavin04890** [aws/eks-anywhere#1235]
**What happened**: Cilium CNI plugin not initialized. That's causing the Nodes to stay in NotReady state, which in turn stops the pods to be running. The final output is a failure to deploy the EKS Anywhere mgmt cluster. 

Output from "kubectl describe nodes"
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Thu, 17 Feb 2022 08:27:34 -0800   Thu, 17 Feb 2022 08:22:03 -0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Thu, 17 Feb 2022 08:27:34 -0800   Thu, 17 Feb 2022 08:22:03 -0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Thu, 17 Feb 2022 08:27:34 -0800   Thu, 17 Feb 2022 08:22:03 -0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            False   Thu, 17 Feb 2022 08:27:34 -0800   Thu, 17 Feb 2022 08:22:03 -0800   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

**What you expected to happen**: Ideal outcome should have been a successful deployment of the EKS Anywhere management cluster

**How to reproduce it (as minimally and precisely as possible)**: I am just following the usual steps in the documentation. Here is a copy of my yaml file: 

apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: mgmt-eks-e-admin
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 10.12.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: "10.21.143.58"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: mgmt
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt-etcd
  kubernetesVersion: "1.20"
  managementCluster:
    name: mgmt
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: mgmt
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: mgmt
spec:
  datacenter: "tanzu-px"
  insecure: true
  network: "VM Network"
  server: "10.21.143.140"
  thumbprint: ""
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-cp
spec:
  datastore: "Tanzu-Infra-1"
  diskGiB: 50
  folder: "eksvm"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: "/tanzu-px/host/avs-tanzu/Resources/eks-rp"
  users:
  - name: capv
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt
spec:
  datastore: "Tanzu-Infra-1"
  diskGiB: 50
  folder: "eksvm"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: "/tanzu-px/host/avs-tanzu/Resources/eks-rp"
  users:
  - name: capv
---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: mgmt-etcd
spec:
  datastore: "Tanzu-Infra-1"
  diskGiB: 50
  folder: "eksvm"
  memoryMiB: 8192
  numCPUs: 4
  osFamily: ubuntu
  resourcePool: "/tanzu-px/host/avs-tanzu/Resources/eks-rp"
  users:
  - name: capv
---

**Anything else we need to know?**: I tried installing Calico instead using this link: https://www.tigera.io/blog/calico-on-eks-anywhere/ 
That brings the nodes to "Ready" state. But, can't use it, as Calico isnt a supported CNI. 

**Environment**:
- EKS Anywhere Release: v0.7.0 
- EKS Distro Release: Not sure. But, Kubernetes version 1.20 and 1.21

**Comment by pokearu** [comment]
Hi @bhavin04890 thanks for reaching out!
Could you please provide the list of kind cluster pods?
`kubectl get po -A --kubeconfig ./mgmt-eks-e-admin/generated/mgmt-eks-e-admin-kind.kubeconfig `
Also if possible the CAPI controller logs on the kind cluster?

**Comment by bhavin04890** [comment]
Here you go @pokearu 
This is from the kind cluster. 

root@eks-admin:/home/bshah# kubectl get po -A
NAMESPACE                           NAME                                                                   READY   STATUS    RESTARTS   AGE
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-7ff4846759-bbxpn             1/1     Running   0          4h1m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-7859bb9c7f-jtg8q         1/1     Running   0          4h1m
capi-system                         capi-controller-manager-84665fdc94-hlz9k                               1/1     Running   0          4h1m
capv-system                         capv-controller-manager-54d84fd7d5-pzrd9                               1/1     Running   0          4h1m
cert-manager                        cert-manager-7988d4fb6c-rvbdc                                          1/1     Running   0          4h2m
cert-manager                        cert-manager-cainjector-6bc8dcdb64-46p7c                               1/1     Running   0          4h2m
cert-manager                        cert-manager-webhook-5cb5df8595-dmll6                                  1/1     Running   0          4h2m
etcdadm-bootstrap-provider-system   etcdadm-bootstrap-provider-controller-manager-74c86ffb56-h986c         1/1     Running   0          4h1m
etcdadm-controller-system           etcdadm-controller-controller-manager-7894945688-skcd8                 1/1     Running   0          4h1m
kube-system                         coredns-fbff88fc6-8c6nz                                                1/1     Running   0          4h2m
kube-system                         coredns-fbff88fc6-vcvtj                                                1/1     Running   0          4h2m
kube-system                         etcd-mgmt-eks-e-admin-eks-a-cluster-control-plane                      1/1     Running   0          4h1m
kube-system                         kindnet-svtsv                                                          1/1     Running   0          4h2m
kube-system                         kube-apiserver-mgmt-eks-e-admin-eks-a-cluster-control-plane            1/1     Running   0          4h1m
kube-system                         kube-controller-manager-mgmt-eks-e-admin-eks-a-cluster-control-plane   1/1     Running   0          4h1m
kube-system                         kube-proxy-gpjbp                                                       1/1     Running   0          4h2m
kube-system                         kube-scheduler-mgmt-eks-e-admin-eks-a-cluster-control-plane            1/1     Running   0          4h1m
local-path-storage                  local-path-provisioner-666bfc797f-j6p4j                                1/1     Running   0          4h2m

And I have attached the capi controller logs. 
[capi-controller-logs.txt](https://github.com/aws/eks-anywhere/files/8091970/capi-controller-logs.txt)

**Comment by pokearu** [comment]
Thanks for the logs 👍
Looking at the logs seems that its failing on
`"msg"="Failed to parse ProviderID" "error"="providerID is empty"` we have seen this error sometimes when the VMs on vCenter dont have access to the vCenter API. Hence the cloud provider was not able to set the provider.
Could you check if the VMs have the right access permissions?

**Comment by bhavin04890** [comment]
Hey @pokearu 
Thank you for the response. 

I followed the steps listed here: https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/ 
and set environment variables for my administrator@vsphere.local credentials. 

How do these get transferred to the VMs that are deployed? I dont think I specify this in the yaml file. 

Could you help me make sure I am passing these correctly to the VMs? 

Thanks

**Comment by pokearu** [comment]
We would not have to do anything extra for having the permissions transferred to the VMs.
Could you please ensure the vSphere account you are using has the below permissions?
[user-permissions](https://anywhere.eks.amazonaws.com/docs/reference/vsphere/user-permissions/)
and the vmware pre-requisites are met? [vsphere-prereq](https://anywhere.eks.amazonaws.com/docs/reference/vsphere/vsphere-prereq/)

Thanks!

**Comment by jaxesn** [comment]
@bhavin04890 I think its this part specifically

`One network in vSphere to use for the cluster. This network must have inbound access into vCenter`

In the network/firewall settings on the vCenter side, inboard access the vCenter api needs to be allowed for the ip cidr range of the specific network you are creating the cluster using.

**Comment by abhinavmpandey08** [comment]
Hi @bhavin04890, were there are vms that were created? Do you have a kubeconfig under `<cluster-name>/<cluster-name>-eks-a-cluster.kubeconfig`

If so, can you use it to check vsphere cloud controller logs?
```
kubectl logs -n kube-system vsphere-cloud-controller-manager-xxxxx --kubeconfig <cluster-name>/<cluster-name>-eks-a-cluster.kubeconfig
```
This should give you more info about the exact error.

**Comment by bhavin04890** [comment]
I tried checking the vsphere cloud controller logs, and it looks like this. But, I did set _**"insecure: true"**_ in the yaml file. 
Does that help? 

E0222 16:07:50.723703       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:51.728017       1 connection.go:177] Failed to create new client. err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:51.728049       1 connection.go:63] Failed to create govmomi client. err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:51.728058       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:52.728207       1 search.go:118] WhichVCandDCByNodeID error vc:Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:52.728297       1 nodemanager.go:182] shakeOutNodeIDLookup failed. Err=Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:52.728329       1 node_lifecycle_controller.go:149] error checking if node mgmt-eks-h-admin-pqcs7 exists: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
I0222 16:07:52.728350       1 search.go:76] WhichVCandDCByNodeID nodeID: mgmt-eks-h-admin-md-0-7f7868766-m9crs
E0222 16:07:52.732550       1 connection.go:177] Failed to create new client. err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:52.732582       1 connection.go:63] Failed to create govmomi client. err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:52.732591       1 connectionmanager.go:148] Cannot connect to vCenter with err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:53.736915       1 connection.go:177] Failed to create new client. err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs
E0222 16:07:53.736947       1 connection.go:63] Failed to create govmomi client. err: Post "https://10.21.143.140:443/sdk": x509: cannot validate certificate for 10.21.143.140 because it doesn't contain any IP SANs

**Comment by bhavin04890** [comment]
To workaround this, I changed the insecure flag to false and provided a thumbprint for my vcenter instance. 
And the management cluster deployment was successful.
