### ISSUE TITLE
Define to be Released work processes

### ISSUE THREAD

**Issue by jaxesn** [aws/eks-anywhere#128]
- [x] How do we build a release Changelog?
- [x] How do we handle docs when merging features for unreleased versions?
- [x] ?

Sync with the BottleRocket team to see how they handle this type of management.

**Comment by TerryHowe** [comment]
I like the way eks-distro has the changelog in the docs. The docs do not cover bug fixes, but we could just modify the same file to generate a change log for 0.5.0 to 0.5.1

**Comment by micahhausler** [comment]
It might be nice to use [netlify](https://www.netlify.com/) for doc previews too
