### ISSUE TITLE
E2E tests improvements 

### ISSUE THREAD

**Issue by jaxesn** [aws/eks-anywhere#131]
- [x] Developer experience when debugging failed tests (needed tools in ami, docs/wiki, support bundle generated and stored on s3, etc)
- [ ] Tracking failures over time
- [ ] Flake handling process
- [x] Define Oncall responsibilities 
- [ ] Clean up left over VMs

E2E code changes:
- [x] https://github.com/aws/eks-anywhere/issues/229
- [x] https://github.com/aws/eks-anywhere/issues/269
- [x] https://github.com/aws/eks-anywhere/issues/271
- [x] https://github.com/aws/eks-anywhere/issues/306
- [ ] https://github.com/aws/eks-anywhere/issues/385

**Comment by mrajashree** [comment]
E2E code changes:

- [ ] https://github.com/aws/eks-anywhere/issues/229
