### ISSUE TITLE
Support bare metal deployments

### ISSUE THREAD

**Issue by rothgar** [aws/eks-anywhere#132]
It would be great if I could bring my own servers and EKS Anywhere will install Kubernetes directly on top of an existing OS or provision the OS and Kubernetes for me.

Please :+1: if you would like this feature

**Comment by vrabbi** [comment]
Maybe integrating with capt or capm3 in order to do this? Or going along a similar approach as rancher and weave took with an existing infra provider for capi

**Comment by Opswatch** [comment]
https://github.com/tinkerbell/cluster-api-provider-tink Tinkerbell has a cluster api provider, and talos.dev has sidero https://www.sidero.dev/

**Comment by DavidSpek** [comment]
Canonical’s MAAS (Metal-as-a-Service) is integrated with the [Cluster API](https://github.com/spectrocloud/cluster-api-provider-maas), so I believe that should make it possible to use EKS anywhere with bare-metal servers.

**Comment by elgalu** [comment]
is the status for this still `notstarted` ?

**Comment by abhinavmpandey08** [comment]
EKS Anywhere for Bare Metal is officially GA! 🚀🚀🚀

Refer to the docs here for trying it out in your bare-metal environment https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/baremetal-getstarted/

Marking this issue as closed
