### ISSUE TITLE
Storage class creation, Persistent Volume and Persistent Volume Claim support in EKS Anywhere

### ISSUE THREAD

**Issue by gauravmittal80** [aws/eks-anywhere#1359]
**What happened**:
Could not find any documentation on how to create a storage class and then PV and PVC in EKS Anywhere.

**Comment by TerryHowe** [comment]
On a production cluster, it will create a default storage class for you that may or may not be useful for you https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/defaultStorageClass.yaml

You can see that doing a `kubectl get storageclass`

There really is nothing special about EKS Anywhere for PV or PVCs and just basic Kubernetes docs will work fine. I imagine that is why there is no documentation.

**Comment by gauravmittal80** [comment]
Thanks for the reply. 

In EKS when we create a PV/PVC, the volume is created and is visible in the volumes section of EC2 service. But here in EKS-Anywhere from where does the PV/PVC take the storage space to create the volume.

As far as I understand when the worker nodes are created they have a default storage of 25Gb, will the PV/PVC takes the space from this default storage.

**Comment by abhinavmpandey08** [comment]
When you create an EKS Anywhere cluster on vSphere, it also installs the vSphere CSI driver and uses that to create PVs. When you use this, it doesn't take space on the node itself but instead creates a vSphere Container Volume. You can find out more about this here: https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-C44D8071-85E7-4933-83EA-6797518C1837.html

**Comment by gauravmittal80** [comment]
Thanks a lot Abhinav for the response. I see there is a default storage class as below.
# kubectl get sc
NAME                 PROVISIONER              RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
standard (default)   csi.vsphere.vmware.com   Delete          Immediate           false                  59d
#

But when I create the PV/PVC i am getting the error.
  Warning  ProvisioningFailed    4m49s                csi.vsphere.vmware.com_vsphere-csi-controller-765894dd54-nnsmt_2e115f7c-7bde-4d27-858c-0f7ea504f4cc  failed to provision volume with StorageClass "standard": rpc error: code = Internal desc = failed to create volume. Error: failed to create cns volume pvc-9b84a1b0-3db8-4d7f-a0f2-19d6363dcfbb. createSpec: "(*types.CnsVolumeCreateSpec)(0xc0000dc1e0)({\n DynamicData: (types.DynamicData) {\n },\n Name: (string) (len=40) \"pvc-9b84a1b0-3db8-4d7f-a0f2-19d6363dcfbb\",\n VolumeType: (string) (len=5) \"BLOCK\",\n Datastores: ([]types.ManagedObjectReference) (len=1 cap=1) {\n  (types.ManagedObjectReference) Datastore:datastore-41\n },\n Metadata: (types.CnsVolumeMetadata) {\n  DynamicData: (types.DynamicData) {\n  },\n  ContainerCluster: (types.CnsContainerCluster) {\n   DynamicData: (types.DynamicData) {\n   },\n   ClusterType: (string) (len=10) \"KUBERNETES\",\n   ClusterId: (string) (len=11) \"default/dms\",\n   VSphereUser: (string) (len=56) \"DMS.LAB.INDIA.WIRELESSWORLD.AIRVANANET.COM\\\\Administrator\",\n   ClusterFlavor: (string) (len=7) \"VANILLA\",\n   ClusterDistribution: (string) \"\"\n  },\n  EntityMetadata: ([]types.BaseCnsEntityMetadata) <nil>,\n  ContainerClusterArray: ([]types.CnsContainerCluster) (len=1 cap=1) {\n   (types.CnsContainerCluster) {\n    DynamicData: (types.DynamicData) {\n    },\n    ClusterType: (string) (len=10) \"KUBERNETES\",\n    ClusterId: (string) (len=11) \"default/dms\",\n    VSphereUser: (string) (len=56) \"administrator@dms.lab.india.wirelessworld.airvananet.com\",\n    ClusterFlavor: (string) (len=7) \"VANILLA\",\n    ClusterDistribution: (string) \"\"\n   }\n  }\n },\n BackingObjectDetails: (*types.CnsBlockBackingDetails)(0xc0005f02a0)({\n  CnsBackingObjectDetails: (types.CnsBackingObjectDetails) {\n   DynamicData: (types.DynamicData) {\n   },\n   CapacityInMb: (int64) 30720\n  },\n  BackingDiskId: (string) \"\",\n  BackingDiskUrlPath: (string) \"\"\n }),\n Profile: ([]types.BaseVirtualMachineProfileSpec) (len=1 cap=1) {\n  (*types.VirtualMachineDefinedProfileSpec)(0xc0008eb8c0)({\n   VirtualMachineProfileSpec: (types.VirtualMachineProfileSpec) {\n    DynamicData: (types.DynamicData) {\n    }\n   },\n   ProfileId: (string) (len=36) \"aa6d5a82-1c88-45da-85d3-3d74b91a5bad\",\n   ReplicationSpec: (*types.ReplicationSpec)(<nil>),\n   ProfileData: (*types.VirtualMachineProfileRawData)(<nil>),\n   ProfileParams: ([]types.KeyValue) <nil>\n  })\n },\n CreateSpec: (types.BaseCnsBaseCreateSpec) <nil>\n})\n", fault: "(*types.LocalizedMethodFault)(0xc0009b69e0)({\n DynamicData: (types.DynamicData) {\n },\n Fault: (types.CnsFault) {\n  BaseMethodFault: (types.BaseMethodFault) <nil>,\n  Reason: (string) (len=85) \"No compatible datastore found for storagePolicy: aa6d5a82-1c88-45da-85d3-3d74b91a5bad\"\n },\n LocalizedMessage: (string) (len=101) \"CnsFault error: No compatible datastore found for storagePolicy: aa6d5a82-1c88-45da-85d3-3d74b91a5bad\"\n})\n", opId: "f05546f6"

Kindly suggest. This EKS cluster is created using the local HDD in the baremetal server.

**Comment by gauravmittal80** [comment]
Thanks a lot @lewisdiamond.
[Creating a storage Policy with a local storage.docx](https://github.com/aws/eks-anywhere/files/8204219/Creating.a.storage.Policy.with.a.local.storage.docx)
 Really appreciate taking out time and sharing the steps. Well i tried the same thing and also created a storage class with the local Disk that was attached to the server. 

Just though of sharing the steps which i followed, for team to use.

Regards,
Gaurav

**Comment by raykrueger** [comment]
Kubernetes will block changes to storageclass parameters (not sure if this was introduced after this issue was closed).

```
$kubectl patch storageclass standard -p '{"parameters": {"storagePolicyName": "my-test-policy"}}'
The StorageClass "standard" is invalid: parameters: Forbidden: updates to parameters are forbidden.
```
Using kubectl edit will get you the same error outcome.

As an alternative workaround, we need to create our own StorageClass using the storage policy we want used.

Create the file _new-storage-class.yaml_
``` 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: new-standard
provisioner: csi.vsphere.vmware.com
parameters:
    storagePolicyName: "My Storage Policy"
 ```

`kubectl apply -f new-storage-class.yaml`

This creates a StorageClass using the named policy rather than the “vSAN Default Storage Policy” that EKS Anywhere will create by default.
 
We can then make this our default. We can use the “new-standard” without it being default as well by specifying the storage class name in any persistent volume configs or helm charts.
 
To make this default as per https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/
 ```
kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
kubectl patch storageclass duke-standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

Optionally, we can delete the "standard" storage class. `kubectl delete storageclass standard`
