### ISSUE TITLE
Support multiple control plane nodes in CloudStack shared network

### ISSUE THREAD

**Issue by wanyufe** [aws/eks-anywhere#1396]
**What would you like to be added**:
Add kube-vip as static pod in control plane nodes to support control plane kube-apiserver load balancing - similar implementation as eks-a does for VSphere provider.
**Why is this needed**:
Without a load balancing like kube-vip, current implementation does not support multiple control plane nodes in **shared** network. Second control plane node deployment in CloudStack will fail when trying to allocate the same IP address. 

This kube-vip is not needed for CloudStack **isolated** network for multiple control plane nodes since all control plane nodes are behind a CloudStack built-in load-balancer and uses private IP addresses.

A simple change in CAPC (CloudStack) provider is needed so that IP address is not specified when deploying control plane VM in shared network.

NOTE:
* Enable kube-vip should be a feature that can be disabled, so that customers who use external load balancing can disable this feature. 
* This feature can be enabled by default
* An env variable like Enable_KUBE_VIP=false/true can be added to disable this feature.

**Comment by maxdrib** [comment]
This work is completed
