### ISSUE TITLE
Support AWS(EC2) provider

### ISSUE THREAD

**Issue by inductor** [aws/eks-anywhere#144]
**What would you like to be added**:

The current implementation does not include aws provider for dev/prd environment, but the `provider` pkg contains AWS.
https://github.com/aws/eks-anywhere/tree/315f3f3783dce07019b79340ce720f0592d397aa/pkg/providers/aws

Since I do not have vSphere environment, I hope AWS to be supported for production use as well.

**Why is this needed**:

**Comment by jaxesn** [comment]
Thanks for the suggestion! When running Kubernetes in AWS cloud we strongly recommend using the EKS service as the best option!

We do understand there may be cases where self managed Kubernetes on EC2 could make sense for people. To track interested I've added a thumbs up above.

**Comment by inductor** [comment]
@jaxesn 
One usecase that is very important for me is that if you support this, I can make use of Cluster API functionality which enables us to use `FeatureGates` on EKS-Distro more easily while having a consistent deployment procedure.

**Comment by abhinavmpandey08** [comment]
Marking this issue was `wontfix` for now but will leave it open to track interest
