### ISSUE TITLE
ESXI Standalone Provider Support

### ISSUE THREAD

**Issue by albertfrates** [aws/eks-anywhere#146]
Ability to deploy EKS Anywhere using a provider to a standalone instance of VMWare ESXI without vCenter. 

Many lab machines, and home lab machines are running VMWare ESXI in a single server configuration. While this is not production grade, it would make bootstrapping a cluster for development/testing/training trivial. 
Currently you cannot do this with the existing providers as you do not define a datacenter name on a single instance resulting in this error: 

> Validation failed    {"validation": "vsphere Provider setup is valid", "error": "error validating vCenter setup: failed to get datacenter: govc: datacenter 'localhost.localdomain' not found\n", "remediation": ""}
Error: failed to create cluster: validations failed

**Comment by TerryHowe** [comment]
EKS Anywhere uses CAPV and CAPV has a vSphere requirement. I don't honestly see them supporting single ESXI hosts because you have to take on all the problems you would deploying on bare metal to deploy a HA cluster. The docker provider is a good alternative for a single node deployment.

**Comment by albertfrates** [comment]
@TerryHowe in this scenario, it would not be for a true HA cluster. Instead you'd simulate an HA cluster, multi-controller, multi-node environment on one physical machine, using sets of virtual machines. Not intended for production grade environments. Purely lab/testing/experimenting/development.

**Comment by inductor** [comment]
ESXi does not have an API like vSphere(vCenter) does. So I don't think this is gonna happen.

**Comment by jaxesn** [comment]
Linking the upstream issue which appears to have never really got any steam behind it and most likely the decision today would be even more clear that requiring vCenter is the right approach to avoid the testing overhead and implementing two code paths for similar features.  

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/400

I'll leave this ticket open and have added a thumbs up to be able to track interest, but I would say this one is pretty unlikely.  As mentioned in the above issue, spinning up a "small" vcenter node is going to be best workaround.

**Comment by TerryHowe** [comment]
I marked this https://github.com/aws/eks-anywhere/labels/wontfix for now, but I'd like to leave this open in case this starts generating a lot of interest. This is a common question.
