### ISSUE TITLE
Update Documentation for Restoring EKS-A cluster ETCD during a complete Quorum Loss!

### ISSUE THREAD

**Issue by suman10586** [aws/eks-anywhere#1460]
**What happened**:
When a majority of the ETCD nodes are lost or if they have changed their IP Addresses ETCD recovery procedure requires manual restoration, Following EKS-A ETCD recovery [documentation](https://anywhere.eks.amazonaws.com/docs/tasks/cluster/etcd-backup-restore/) the docs outline restoring snapshot on each and every node one by one. This process involves getting the DB snapshot saved and then restore the DB to the new nodes This restore is a 2 part process: The first part is restoring etcd using the snapshot, creating a new data-dir for etcd. The second part is replacing the current etcd data-dir with the one generated after restore.

However when the ETCD nodes of the cluster have lost quorum this procedure do not helps to restore the cluster and we end up having certificate errors such as PKI mismatch between new nodes, If the nodes are recycled with new IP addresses the current docs do not explain the recovery procedure in such cases and we end up in below errors:

mgmt-ubuntu-1-etcd-jcdzx etcd[198127]: rejected connection from "10.4.131.102:47056" (error "remote error: tls: bad certificate", ServerName "")

mgmt-ubuntu-1-etcd-jcdzx etcd[774]: the server is already initialised as member before, starting as etcd member...

**What you expected to happen**:
Cluster should be restored as per the documented procedure! 

**How to reproduce it (as minimally and precisely as possible)**:

On a running EKS-A cluster with 3 ETCD nodes create clones of the two ETCD nodes this will launch exact same copies of the the ETCD Nodes with different IP addresses ,Now delete the original ETCD nodes which you have cloned on the Vsphere , The ETCD quorum is lost and the new(clones) are up and running with different IP addresses , Now try restoring the cluster following the docs here: https://anywhere.eks.amazonaws.com/docs/tasks/cluster/etcd-backup-restore/ 

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: V0.7
- EKS Distro Release:

**Comment by panktishah26** [comment]
@suman10586 thank you for creating a Github issue for this. We are looking into this and will get back to you.
cc: @mrajashree
