### ISSUE TITLE
Proxmox Provider Support

### ISSUE THREAD

**Issue by albertfrates** [aws/eks-anywhere#147]
Support for deploying EKS Anywhere using a provider for Proxmox.

Many labs, homelabs, & test systems run proxmox as the underlying VM host. Having an easy way to deploy to a single instance of proxmox or a proxmox cluster would be very useful for testing/development/training.

As many ways as possible to deploy a full cluster onto a single server host would rapidly increase adoption in this realm.

**Comment by inductor** [comment]
I believe this has to be done by Cluster API Providers first.
https://cluster-api.sigs.k8s.io/reference/providers.html

**Comment by ptrivedi** [comment]
Thanks for reporting and commenting. @inductor is correct, EKS Anywhere uses Kubernetes Cluster API under the covers and currently CAPI does not have a Proxmox provider implementation. We could revisit this when the support is available and add it to the roadmap based on feedback and interest.

**Comment by azN2** [comment]
+1 for proxmox

**Comment by jmreicha** [comment]
Interested in this as well. Is there any place to track the upstream Proxmox support? My quick Google search isn’t turning much up.

**Comment by inductor** [comment]
@jmreicha As written in my comment, you should see Cluster API's activity.

**Comment by jmreicha** [comment]
@inductor Can you point me in the right direction?

**Comment by jmreicha** [comment]
Did a little more digging, couldn't find much. Would the [cluster-api](https://github.com/kubernetes-sigs/cluster-api)  repo be the correct place to open an issue/proposal for adding the upstream support?

**Comment by inductor** [comment]
As @ptrivedi explained very well above in the comment, EKS Anywhere is just a wrapper of Cluster API in the very core.

In [the Kubernetes blog](https://kubernetes.io/blog/2020/04/21/cluster-api-v1alpha3-delivers-new-features-and-an-improved-user-experience/), Cluster API is explained as follows

>The Cluster API is a Kubernetes project to bring declarative, Kubernetes-style APIs to cluster creation, configuration, and management.

Cluster API has their own cloud provider specifications and the implementation that currently exists are listed in [here](https://github.com/kubernetes-sigs?q=cluster-api-provider) and [here](https://cluster-api.sigs.k8s.io/reference/providers.html).

There's no proxmox right now. Someone has to start the project, anyone can be.

**Comment by inductor** [comment]
@jmreicha You should ask on Slack first maybe, there's #cluster-api channel.

**Comment by danbudris** [comment]
going to mark this as `wontfix` but leave it open to help gauge interest in the provider

**Comment by azN2** [comment]
https://github.com/k8s-proxmox/cluster-api-provider-proxmox

**Comment by NX1X** [comment]
Few years later: any chance EKS Anywhere will support Proxmox in the near future?
