### ISSUE TITLE
Validate size of BR disk before continuing

### ISSUE THREAD

**Issue by vivek-koppuru** [aws/eks-anywhere#1571]
We should fail earlier if the BR disk is not big enough instead of waiting until create cluster gets stuck in provisioning the nodes due to a lack of space.

**Comment by vignesh-goutham** [comment]
There is a govc command `datastore.disk.info` that returns the metadata about the disk stored on vSphere datastore. This can be used to validate the disk size. Please refer here for usage - https://github.com/vmware/govmomi/blob/master/govc/USAGE.md#datastorediskinfo

**Comment by rahulbabu95** [comment]
Added a validation for BR disk size with PR #5000 which will be available in release .15.0.
