### ISSUE TITLE
registry mirroring doesn't work for oci://public.ecr.aws/isovalent/cilium

### ISSUE THREAD

**Issue by wongni** [aws/eks-anywhere#1599]
**What happened**:
When creating a cluster from an environment that does not have internet access I am getting the following error even with the registry mirroring to an internal registry. 
`
$ /usr/bin/docker exec -i -e HELM_EXPERIMENTAL_OCI=1 eksa_1648068307441834002 helm template oci://public.ecr.aws/isovalent/cilium --version 1.9.11-eksa.1 --namespace kube-system -f -
Error: failed to download "oci://public.ecr.aws/isovalent/cilium" at version "1.9.11-eksa.1"
`

**What you expected to happen**:
The URL for the cillum may be replaced with the mirrored registry URL. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster in an air-gapped environment with registry mirroring to an internal registry. 

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.7.2
- EKS Distro Release: 0.88.0

**Comment by ptrivedi** [comment]
Hi @wongni, this issue should be addressed and fixed in the upcoming 0.8.0 release.
