### ISSUE TITLE
Pull access denied for public.ecr.aws/eks-anywhere/cli-tools

### ISSUE THREAD

**Issue by ttirtawi** [aws/eks-anywhere#1628]
The documentation for creating the local cluster doesn't mentioned about the ECR login.

Following the guide step-by-step will stuck with the following error:

```
Error: failed to create cluster: Error response from daemon: pull access denied for public.ecr.aws/eks-anywhere/cli-tools, repository does not exist or may require 'docker login': denied: Your authorization token has expired. Reauthenticate and try again.
```

This can be fixed by running the following command ahead:

```
aws --region us-east-1 ecr-public get-login-password  | docker login  --username AWS --password-stdin public.ecr.aws/eks-anywhere/cli-tools
```

Would be helpful if the documentation put it as prerequisite step before creating the cluster.

**Comment by vivek-koppuru** [comment]
It could be that you tried an authenticated pull before on this registry or a different private ECR registry that docker is getting confused with. If you try to docker logout like it says below, it should hopefully work for you!

https://docs.aws.amazon.com/AmazonECR/latest/public/public-troubleshooting.html
