### ISSUE TITLE
Store cilium chart for registry mirror in isovalent repository

### ISSUE THREAD

**Issue by vivek-koppuru** [aws/eks-anywhere#1629]
Currently `import-images` stores the cilium chart under the registry of `<registry-mirror>/cilium-chart`, while the cilium image is stored under `<registry-mirror>/isovalent/cilium`. We should reuse the same `isovalent` repository instead of have the user have to create a separate repository called `cilium-chart` to decrease the number of repositories that have to be created. 

We also seem to have different naming for other images, such as `<registry-mirror>/l0g8r8j6/kubernetes-sigs/cluster-api/kubeadm-bootstrap-controller`, so maybe we can use `l0g8r8j6` as the common repository instead, or have a command that will create the necessary repositories for the user instead of creating them manually through these steps: https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/registrymirror/#registry-configurations

**Comment by mrajashree** [comment]
> We should reuse the same isovalent repository instead of have the user have to create a separate repository called cilium-chart 

👍 

>so maybe we can use l0g8r8j6 as the common repository instead

that registry only gets used for dev, but a command creating necessary repos would be good

**Comment by vivek-koppuru** [comment]
Resolving this issue in favor of #1783
