### ISSUE TITLE
Improve cleanup of resources on failure

### ISSUE THREAD

**Issue by vivek-koppuru** [aws/eks-anywhere#163]
Currently the CLI leaves resources hanging on failure (such as VM nodes, kind bootstrap cluster, etc.) that might be troublesome for users to have to clean up on their own. Instead, the default for create can be to clean up on failure  based on the phase of the workflow they are in unless specified through a flag like `--skip-cleanup`. We can also make the appropriate `govc` calls to clean up VMs in case cleaning them up through the bootstrap cluster fails for us.

**Comment by abhinavmpandey08** [comment]
We already have a force-cleanup flag which some some cleanup although it doesn't do it's job properly all the time.
Going to close this issue in favor of this https://github.com/aws/eks-anywhere/issues/225 as the initial implementation for clean up is already there and the other issue captures its shortcomings in more detail
