### ISSUE TITLE
when ec2 stops, can't connect my cluster 

### ISSUE THREAD

**Issue by ataince** [aws/eks-anywhere#1696]
I created environment on cloud9 and whenever c9's ec2 stops and restarts, I'm struggling with this situation.
when i write: `kind-get-clusters`
i can see my cluster: `dev-cluster`
when i try something like: `kubectl apply -f "https://anywhere.eks.amazonaws.com/manifests/hello-eks-a.yaml"`
**i'm getting this error: The connection to the server localhost:8080 was refused - did you specify the right host or port?**
kubectl config view outputs:
`apiVersion: v1
clusters: null
contexts: null
current-context: ""
kind: Config
preferences: {}
users: null`
docker ps -a outputs: 
`CONTAINER ID   IMAGE                                                                                COMMAND                  CREATED             STATUS                     PORTS                                  NAMES
1284081148f7   public.ecr.aws/eks-anywhere/kubernetes-sigs/kind/node:v1.21.5-eks-d-1-21-9-eks-a-7   "/usr/local/bin/entr…"   About an hour ago   Up 5 minutes                                                      dev-cluster-md-0-869689bd46-cn6lz
9479e1a0434c   public.ecr.aws/eks-anywhere/kubernetes-sigs/kind/node:v1.21.5-eks-d-1-21-9-eks-a-7   "/usr/local/bin/entr…"   About an hour ago   Up 5 minutes               39655/tcp, 127.0.0.1:39655->6443/tcp   dev-cluster-dmxj6
4cedeb5c6953   public.ecr.aws/eks-anywhere/kubernetes-sigs/kind/node:v1.21.5-eks-d-1-21-9-eks-a-7   "/usr/local/bin/entr…"   About an hour ago   Up 5 minutes                                                      dev-cluster-etcd-95hsb
2baf786524dc   kindest/haproxy:v20210715-a6da3463                                                   "haproxy -sf 7 -W -d…"   About an hour ago   Exited (0) 6 minutes ago                                          dev-cluster-lb`

**Comment by abhay-krishna** [comment]
Could you try passing in the `kubeconfig` flag pointing to the workload cluster's kubeconfig?
```
kubectl --kubeconfig dev-cluster/dev-cluster-eks-a-cluster.kubeconfig apply -f "https://anywhere.eks.amazonaws.com/manifests/hello-eks-a.yaml"
```
(assuming your kubeconfig is at `dev-cluster/dev-cluster-eks-a-cluster.kubeconfig`)

**Comment by ataince** [comment]
> Could you try passing in the `kubeconfig` flag pointing to the workload cluster's kubeconfig?
> 
> ```
> kubectl --kubeconfig dev-cluster/dev-cluster-eks-a-cluster.kubeconfig apply -f "https://anywhere.eks.amazonaws.com/manifests/hello-eks-a.yaml"
> ```
> 
> (assuming your kubeconfig is at `dev-cluster/dev-cluster-eks-a-cluster.kubeconfig`)

The connection to the server 127.0.0.1:35183 was refused - did you specify the right host or port?

**Comment by danbudris** [comment]
Hey @ataince 

This is a docker cluster, right? What does your cluster configuration file look like?

If you create a fresh cluster on your instance, are you able to successfully access it?

I would be curious if we can reproduce this by creating a fresh, working cluster, restarting the instance, and observing if it becomes unavailable.

**Comment by ataince** [comment]
> Hey @ataince
> 
> This is a docker cluster, right? What does your cluster configuration file look like?
> 
> If you create a fresh cluster on your instance, are you able to successfully access it?
> 
> I would be curious if we can reproduce this by creating a fresh, working cluster, restarting the instance, and observing if it becomes unavailable.

Actually every time when open cloud9 I'm creating new fresh cluster because I can't connect the latest If my instance stops or reboots. I'm just trying to follow docs on [anywhere.eks.amazonaws.com](this site.) I think the problem about haproxy when i run `docker ps -a` it shows haproxy exited If I restart haproxy and try something I'm getting this output:
**Unable to connect to the server: EOF**

**Comment by jaxesn** [comment]
Unfortunately this is not support for the docker provider.  We will update the docs to reflect this.
