### ISSUE TITLE
Log Output should be saved to file automatically and included in support bundle

### ISSUE THREAD

**Issue by danbudris** [aws/eks-anywhere#1703]
**What would you like to be added**:
when running the eks-a CLI, log output should be automatically output to file as well as to stdout

**Why is this needed**:
in cases where an SSH connection to a mgmt machine is terminated, but the CLI is still running, there is no way to recover the log output in a reliable way; we should set up a way where this can be recovered more easily.

**Comment by vivek-koppuru** [comment]
It would be beneficial to have this also always output verbose logs so that we have that output when a user doesn't specify verbose logging.
