### ISSUE TITLE
Failed to pull image in bootstrap cluster. certificate signed by unknown authority. Custom CA

### ISSUE THREAD

**Issue by pulberg** [aws/eks-anywhere#171]
```
Error from server (NotFound): namespaces "capi-webhook-system" not found
Error from server (NotFound): namespaces "capi-kubeadm-bootstrap-system" not found
Error from server (NotFound): namespaces "capv-system" not found
Error from server (NotFound): namespaces "capi-webhook-system" not found
Error from server (BadRequest): container "cert-manager" in pod "cert-manager-webhook-56cbc8f5b8-7fhvt" is waiting to start: trying and failing to pull image
Error from server (BadRequest): container "cert-manager" in pod "cert-manager-cainjector-bb6d9bcb5-jtz48" is waiting to start: trying and failing to pull image
Error from server (BadRequest): container "cert-manager" in pod "cert-manager-5f6b885b4-pg5fh" is waiting to start: trying and failing to pull image
```

Describe failed pods shows - 
```
Failed to pull image "public.ecr.aws/eks-anywhere/jetstack/cert-manager-controller:v1.1.0-eks-a-1": rpc error: code = Unknown desc = failed to pull and unpack image "public.ecr.aws/eks-anywhere/jetstack/cert-manager-controller:v1.1.0-eks-a-1": failed to resolve reference "public.ecr.aws/eks-anywhere/jetstack/cert-manager-controller:v1.1.0-eks-a-1": failed to do request: Head "https://public.ecr.aws/v2/eks-anywhere/jetstack/cert-manager-controller/manifests/v1.1.0-eks-a-1": x509: certificate signed by unknown authority
Failed to pull image "public.ecr.aws/eks-anywhere/jetstack/cert-manager-cainjector:v1.1.0-eks-a-1": rpc error: code = Unknown desc = failed to pull and unpack image "public.ecr.aws/eks-anywhere/jetstack/cert-manager-cainjector:v1.1.0-eks-a-1": failed to resolve reference "public.ecr.aws/eks-anywhere/jetstack/cert-manager-cainjector:v1.1.0-eks-a-1": failed to do request: Head "https://public.ecr.aws/v2/eks-anywhere/jetstack/cert-manager-cainjector/manifests/v1.1.0-eks-a-1": x509: certificate signed by unknown authority
Failed to pull image "public.ecr.aws/eks-anywhere/jetstack/cert-manager-webhook:v1.1.0-eks-a-1": rpc error: code = Unknown desc = failed to pull and unpack image "public.ecr.aws/eks-anywhere/jetstack/cert-manager-webhook:v1.1.0-eks-a-1": failed to resolve reference "public.ecr.aws/eks-anywhere/jetstack/cert-manager-webhook:v1.1.0-eks-a-1": failed to do request: Head "https://public.ecr.aws/v2/eks-anywhere/jetstack/cert-manager-webhook/manifests/v1.1.0-eks-a-1": x509: certificate signed by unknown authority
```

I'm in a secure corp environment with corp CA's used for filtering all web requests.

**What happened**:
Local cluster creation times out after many minutes.

**What you expected to happen**:
Local cluster is created.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure

**Anything else we need to know?**:
macOS Big Sur 11.5.2

**Environment**:
- EKS Anywhere Release: v0.5.0
- EKS Distro Release:

**Comment by abhay-krishna** [comment]
Hello @pulberg, does your corp environment have access to `https://public.ecr.aws`?

**Comment by pulberg** [comment]
Yes, these pulled correctly - 

```
public.ecr.aws/eks-anywhere/cli-tools:v0.1.0-eks-a-1
public.ecr.aws/eks-anywhere/kubernetes-sigs/kind/node:v1.21.2-eks-d-1-21-4-eks-a-1
```

**Comment by jaxesn** [comment]
The cert manager image, along with a number of others, are pulled inside the bootstrap kind cluster whereas those other two you mentioned are pulled on the host machine. The host must have the trusted certs /ca whereas the kind cluster does not.

Not sure the best way to handle this but we can do some looking around. One option would be to do all pulling on the host and use kind's load image ability to load them into the running bootstrap container.

**Comment by antoniordz96** [comment]
> The cert manager image, along with a number of others, are pulled inside the bootstrap kind cluster whereas those other two you mentioned are pulled on the host machine. The host must have the trusted certs /ca whereas the kind cluster does not.

https://github.com/kubernetes-sigs/kind/issues/941 documents this error and provides a workaround to add the trusted cert/ca to the kind cluster. Kind does offer also the ability to mount volumes with extraMounts in the config https://github.com/kubernetes-sigs/kind/issues/1010.



> Not sure the best way to handle this but we can do some looking around. One option would be to do all pulling on the host and use kind's load image ability to load them into the running bootstrap container.

All images needed by the kind cluster could be pulled from the workstation and archived. Then it would be a simple load of the archive to kind cluster. Ref: https://kind.sigs.k8s.io/docs/user/quick-start/#loading-an-image-into-your-cluster.

**Comment by jaxesn** [comment]
Thanks @antoniordz96!

The more I think about it the more I'm not sure about the pulling images on the host approach.  That would def solve this exact problem, but if you were creating a vsphere cluster the kind cluster would be need to be able to make calls to the vcenter api, would those also be being intercepted like this and need the CA?  Technically for vcenter we can ignore cert failures by providing the thumbprint or just ignoring tls, but I wonder if in a general sense we would just be kicking the problem down the line in the process.  If you were standing up a vsphere cluster, would this custom CA be something you would want to exist in your cluster in case services are making calls to other internal services using this CA?
