### ISSUE TITLE
Docs look wrong for manual install

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-anywhere#1714]
**What happened**:
wanted to install 0.7.2 got 0.7.0 I guess, it doesn't work

**What you expected to happen**:
Install 0.7.2

**How to reproduce it (as minimally and precisely as possible)**:
Follow https://github.com/aws/eks-anywhere/blob/main/docs/content/en/docs/getting-started/install/_index.md?plain=1#L62

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by chrisdoherty4** [comment]
Stale
