### ISSUE TITLE
Use JUNIT report output as source of truth for E2E test status output

### ISSUE THREAD

**Issue by danbudris** [aws/eks-anywhere#1757]
We currently parse test results text in order to report on failed tests in the slack channel.

This is brittle and prone to error.

We should use the JUNIT report output by each test execution to determine which tests passed/succeeded, and use this as the source of truth for the test status reporting.

**Comment by chrisdoherty4** [comment]
Big fan!

**Comment by taneyland** [comment]
The python `junitparser` module is not readily available with AWS Lambda. We will either have to manually parse the junit results or use a method like [this](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-package-with-dependency).
