### ISSUE TITLE
Support Podman as a provider for local installs

### ISSUE THREAD

**Issue by thanasisk** [aws/eks-anywhere#176]
**What would you like to be added**: Podman provider, in addition to Docker.

**Why is this needed**: Fedora 3x does not natively support Docker.

**Comment by rothgar** [comment]
Fedora 3x switched to cgroups v2 which is not supported in the docker engine packaged in the default fedora repositories.

Our current supported OSs are macOS and Ubuntu as described here https://anywhere.eks.amazonaws.com/docs/getting-started/install/

We recommend using docker community edition which will give you docker 20.10 which includes cgroup v2 support. The other alternative is to switch your systemd cgroup version to v1 as described here. https://www.linuxuprising.com/2019/11/how-to-install-and-use-docker-on-fedora.html

**Comment by thanasisk** [comment]
Thanks for pointing out the alternatives. I have started work towards the addition of a Podman provider. Will a PR be welcome?

**Comment by jaxesn** [comment]
I do suspect we get more interest in such support with the recent changes announced on the Docker Desktop side.  I would probably wait to prioritize this on our side until we really see how all that plays out and what, if anything, changes with most Mac users' daily routine.

That said, we will always consider PR contributions!
