### ISSUE TITLE
CLI stuck on waiting for external etcd to be ready if vSphere user has incorrect permissions

### ISSUE THREAD

**Issue by RobertNorthard** [aws/eks-anywhere#1802]
**What happened**: 

CLI stuck on "Waiting for external etcd to be ready" as my vSphere user did not have permissions to create VMs in the resourcePool I provided as part of the VSphereMachineConfig cluster config.

**What you expected to happen**:

CLI to exit with a non zero exit code and inform the user their vSphere user is missing a permission to assign VMs to the provided resource pool.

**How to reproduce it (as minimally and precisely as possible)**:

Create EKS-A cluster using vSphere provisioner and provide resource pool in cluster config in which the vSphere user does not have permissions to create resources.

**Environment**:
- EKS Anywhere Release: 0.7.0

**Comment by jiayiwang7** [comment]
Thanks for the report. We can add an user permission check as part of the provider preflight validation and fail ahead with proper error message if the user does not have access to create VMs in the specified resource pool.
