### ISSUE TITLE
Allow to get logs without waiting for cli to fail

### ISSUE THREAD

**Issue by g-gaston** [aws/eks-anywhere#183]
**What would you like to be added**:
A mechanism to collect logs ad hoc: either with a new command, or automatically when the cli is killed

**Why is this needed**:
If during the create command, there is a problem and the cli gets stuck waiting for a component that will never come up, the cli only collects logs after a timeout is reached. If a user wants the logs, they need to wait until the cli fails, which is also not communicated in logs. This could be a long long time.

**Comment by jaxesn** [comment]
Not entirely what you are asking, but Id like to use the support feature here for grabbing logs from the bootstrap cluster instead of what we are doing now.  If that would work, we could document how to run the support bundle feature while waiting for the cli to finish.
