### ISSUE TITLE
After restarting the machine that was running the single-system method  EKS Anywhere, I lost my EKS-A Cluster.

### ISSUE THREAD

**Issue by ruiyaoOps** [aws/eks-anywhere#187]
**What happened**:
After restarting the machine that was running the single-system method  EKS Anywhere, I lost my EKS-A Cluster.

**What you expected to happen**:
After restarting the machine, the single-system method  EKS Anywhere will restart too.

**How to reproduce it (as minimally and precisely as possible)**:
Restarting the machine that was running the single-system method  EKS Anywhere.

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.5.0
- EKS Distro Release:

![image](https://user-images.githubusercontent.com/35256376/133049117-a35c51bd-c48a-44c7-bd57-da251bc64227.png)
![image](https://user-images.githubusercontent.com/35256376/133049187-75028c83-a565-4a93-8a6c-39b961fd21c4.png)

**Comment by jaxesn** [comment]
Thanks for the report.  I have added +1 to track future instances from other users.

**Comment by jaxesn** [comment]
This is fixed upstream in capi v0.4

https://github.com/kubernetes-sigs/cluster-api/pull/5021

**Comment by ganga-sah** [comment]
I am eagerly waiting for a fix for this issue. Currently EKSA on docker running on MacOS or Windows is not useful as I don't know of a way to restart EKSA cluster on docker or machine restart. Is there any workaround to restart EKSA cluster?
