### ISSUE TITLE
cloudstack external etcd machines don't have version

### ISSUE THREAD

**Issue by wongni** [aws/eks-anywhere#1889]
**What happened**:
After creating a cluster with external etcd nodes, checking machine versions doesn't show the versions of the etcd machines. The CPs and worker machines have the version correctly. 

`
❯ k get machines -A | grep "wl-6"
eksa-system   wk-wl-6-etcd-2vv26              wk-wl-6                                                        cloudstack:///15433c32-37f2-4fb6-88f3-13a312a823e8   Running   24m
eksa-system   wk-wl-6-md-0-847bd85c98-94c75   wk-wl-6   wk-wl-6-md-0-1650469863033-t7c7x                     cloudstack:///511e59db-cce4-4297-b2fd-e824d2805799   Running   24m   v1.21.9-eks-1-21-11
eksa-system   wk-wl-6-vcg28                   wk-wl-6   wk-wl-6-control-plane-template-1650469863022-q8ptq   cloudstack:///2cb82f15-64dd-40e5-8ad1-308cf7004761   Running   23m   v1.21.9-eks-1-21-11
`

![image](https://user-images.githubusercontent.com/11528277/164278155-86bdaa45-2a62-41cf-a280-a4e68c34a7ad.png)

**What you expected to happen**:

The external etcd machines should have the version as well. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster with external etcd nodes
2. kubectl get machines -A
3. Check the versions of the machines

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.8.3-custom
- EKS Distro Release:

**Comment by g-gaston** [comment]
hey @wongni!
What version would you expect to see there?
The etcd machines are not kubernetes nodes, so they are not running a kubernetes version per se.

**Comment by wongni** [comment]
The customer wanted to the ETCD version in the version column, but we don't think it's a right move to put the ETCD version in the version field reserved for k8s version. I proposed an alternative way to get the information they want. 

`kubectl -n eksa-system describe EtcdadmCluster [name-of-cluster]-etcd`
