### ISSUE TITLE
public.ecr.aws/eks-anywhere/cli-tools:v0.7.2-eks-a-8 doesn't support proxy config

### ISSUE THREAD

**Issue by worldchanger** [aws/eks-anywhere#2050]
**What happened**:  Attempting to install EKS Anywhere on a network that is behind a proxy.  The install fails because the public.ecr.aws/eks-anywhere/cli-tools:v0.7.2-eks-a-8 container can't download the helm file.  You get the following error:

Error: failed to download "oci://public.ecr.aws/isovalent/cilium" at version "1.9.13-eksa.2"

**What you expected to happen**: You expect the installer to pass the proxy config to the container  like it does public.ecr.aws/eks-anywhere/kubernetes-sigs/kind/node:v1.22.6-eks-d-1-22-4-eks-a-8.  

**How to reproduce it (as minimally and precisely as possible)**: Attempt to install EKS Anywhere behind a proxy

**Anything else we need to know?**:   I manually ran the same command it runs in in the install on the host and had the same results.  I even tried to pass the proxy config as env variables like it passes to the node container above and that doesn't work. If you do a docker inspect on the container, you can even see the proxy config being set by docker but the container still doesn't use the proxy config.  

In testing, I did a docker pull of the file on another machine that isn't behind the proxy but it's on a different network that doesn't have access to the vpshere and started up the container just like the installer starts it, ran the command and got the helm file.  

Further testing, I created a generic container on the host that is behind the proxy, installed helm on it, and then performed the same test.  This generic container is configured to use the proxy and it can pull the helm file.  

I have even tried to manually install the helm file for cilium during the install and it will spin up cilium, but the rest of the install still won't continue because things fail when it tries to download the helm file in the installer.  

**Environment**: Installer running on Ubuntu 20.4, docker 20.10.14, vSphere 7 but all of this is behind a proxy
- EKS Anywhere Release: v0.8.2
- EKS Distro Release: 1.22, 1.21

**Comment by vivek-koppuru** [comment]
Is this when running `create cluster`? This issue has been resolved as part of https://github.com/aws/eks-anywhere/pull/2032 and will make it to the next release.

**Comment by jaxesn** [comment]
released in 0.9
