### ISSUE TITLE
DNS resolver

### ISSUE THREAD

**Issue by thebigcosinus** [aws/eks-anywhere#207]
**What happened**:

How can I add a DNS resolver 8.8.8.8 in the /etc/resolv.conf of my pods using the cluster description yaml file ?
I'm using the docker provider and in the /etc/resolv.conf I have the IP og the CoreDNS Service. 

My Pods do not resolve external IPs like amazon.com

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by vignesh-goutham** [comment]
Hi @thebigcosinus thanks for trying out EKS-Anywhere. The CoreDNS has a ConfigMap where it pulls its configurations from. You can try to update that with the nameserver you would like to use. Take a look at https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/ for reference. You would have to restart the CoreDNS pods once you have updated the ConfigMap.

```export KUBECONFIG=${PWD}/${CLUSTER_NAME}/${CLUSTER_NAME}-eks-a-cluster.kubeconfig
kubectl get configmap coredns -n kube-system``` to checkout what the current config is and you can edit it with your config and apply.

**Comment by thebigcosinus** [comment]
@vignesh-goutham thanks it works
