### ISSUE TITLE
Implement Curated Packages

### ISSUE THREAD

**Issue by a-cool-train** [aws/eks-anywhere#2083]
**What would you like to be added**:
As a user, I would like the following functionalities to be added:
- Installation of curated packages as part of cluster creation
- Installation of curated packages in an existing cluster
- Generation of curated packages configurations
- Discovery of curated packages to be installed to a cluster
- CLI commands to manage the lifecycle of curated packages
- Downloading and importing curated packages artifacts to a private registry

**Why is this needed**:
As a user, I would like the ability to:
- Extend the functionalities of my kubernetes cluster

**Comment by walidshaari** [comment]
As in Day-2 packages? 
Close on-prem Registry e.g. Harbor package, Monitoring, Logging, backup, security baseline, ..etc
Also, DX, as in enabling some sort of PaaS e.g. DevFile?

**Comment by a-cool-train** [comment]
This issue has been completed and all the functionalities have been merged.
