### ISSUE TITLE
clusterconfig is not generated at all

### ISSUE THREAD

**Issue by GurayCetin** [aws/eks-anywhere#2113]
clusterconfig generate command didn't work on site demo for customer. I couldn't find any solution. 
yaml is created but it is not creating any folder containing clusterconfig file.  It's weird. 

CLUSTER_NAME=mgmt
eksctl anywhere generate clusterconfig $CLUSTER_NAME \
   --provider vsphere > eksa-mgmt-cluster.yaml

**Comment by jiayiwang7** [comment]
The `generate clusterconfig` cmd only creates the clusterconfig yaml file (in your case, `eksa-mgmt-cluster.yaml`) under the path you run the cmd. This yaml file is the cluster config file. We don't create any folder until you run `eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml` cmd.

Reference: https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/#create-an-initial-cluster

Please reply if you have more questions.
