### ISSUE TITLE
cni format in cluster yaml file 

### ISSUE THREAD

**Issue by GurayCetin** [aws/eks-anywhere#2114]
It looks cluster yaml file format is changed for cni item. 
In documentation it looks cni:"cilium", but when creating yaml file, cniConfig: cillium: {} is existed. 
Why is it different? It gave an error when creating cluster. 

documentation;

spec:
   clusterNetwork:
      cni: "cilium"

now;

spec:
  clusterNetwork:
    cniConfig:
      cilium: {}

**Comment by jiayiwang7** [comment]
Doc updated in #2119. It should be reflected in the 0.9 release soon.
