### ISSUE TITLE
Unable to get cluster config from file

### ISSUE THREAD

**Issue by GurayCetin** [aws/eks-anywhere#2156]
When I run the cluster create command, it's given me error below, is it related to connection issue to anywhere-assets url?
Why does it need the manifest file from anywhere-assets url ?

<img width="1346" alt="Screen Shot 2022-05-13 at 14 57 21" src="https://user-images.githubusercontent.com/34660613/168278529-2ef68405-a065-468e-a37e-1c8b0e208292.png">

By the way, is it possible to use another configuration yaml file that modified to cluster kubeconfig created before. kubeconfig and generated yaml file are linked with naming or is there anything to connect them behind it?

**Comment by jiayiwang7** [comment]
> is it related to connection issue to anywhere-assets url?

Yes. Double check if the host where you run the cmd have internet access to our public S3.
Reference: https://anywhere.eks.amazonaws.com/docs/reference/vsphere/vsphere-prereq/

The administrative machine and the target workload environment will need network access to:
- public.ecr.aws
- anywhere-assets.eks.amazonaws.com (to download the EKS Anywhere binaries, manifests and OVAs)
- distro.eks.amazonaws.com (to download EKS Distro binaries and manifests)
- d2glxqk2uabbnd.cloudfront.net (for EKS Anywhere and EKS Distro ECR container images)
- api.github.com (only if GitOps is enabled)

> Why does it need the manifest file from anywhere-assets url ?

To download the EKS Anywhere binaries, manifests and OVAs

> is it possible to use another configuration yaml file that modified to cluster kubeconfig created before. kubeconfig and generated yaml file are linked with naming or is there anything to connect them behind it?

Not 100% sure what you mean. Ideally you should not update the `kubeconfig` file generated by EKS Anywhere. The `kubeconfig` file generated has the cluster name, ip you specified in the cluster config file. You can use it to access the EKS anywhere cluster.
