### ISSUE TITLE
Pod CIDR in the generated spec is not used for cluster provision

### ISSUE THREAD

**Issue by gohmc** [aws/eks-anywhere#219]
The pod CIDR was updated in the generated spec:

```
clusterNetwork:
  cni: cilium
  pods:
    cidrBlocks:
    - 10.10.0.0/16
```

Despite the changed, `kubectl cluster-info dump --kubeconfig dev-cluster-eks-a-cluster.kubeconfig | grep -i cidr` reported:

```
 "io.cilium.network.ipv4-pod-cidr": "192.168.0.0/24",
                "podCIDR": "192.168.0.0/24",
                "podCIDRs": [
                    "io.cilium.network.ipv4-pod-cidr": "192.168.1.0/24",
                "podCIDR": "192.168.1.0/24",
                "podCIDRs": [
                            "--allocate-node-cidrs=true",
                            "--cluster-cidr=192.168.0.0/16",
```

Is modify the spec the correct way to configure the cluster CIDR and direct Cilium to follow the cluster CIDR?

**Comment by TerryHowe** [comment]
Did you get a cluster up?

**Comment by gohmc** [comment]
No, the default CIDR conflict with the underlying host network.

**Comment by vignesh-goutham** [comment]
The spec is the right place to configure the pods and service CIDR. You dont need to have to do anything else. Could you share the output of `kubectl --kubeconfig dev-cluster-eks-a-cluster.kubeconfig get pods -A` to check if all the pods are running? Could you also share the output of CIlium config on the cluster, you can get them with `kubectl --kubeconfig dev-cluster-eks-a-cluster.kubeconfig get cm cilium-config -n kube-system -o yaml`

**Comment by gohmc** [comment]
Since the cluster-info dump proven wrong CIDR being used, there's no point keeping it as it conflicted with host network. The cluster didn't provision successfully (some sort of CA error) but this is expected since the CIDR is incorrect. That being said, since the configuration was correct, why the cluster still provision with default 192.168.x.x CIDR?

**Comment by jaxesn** [comment]
@gohmc thanks for the report!  You are right, we are not currently respecting the pod/serviceCidr config for docker clusters.  Notice the difference between the two templates, [docker](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/docker/config/template.yaml#L10) and [vsphere](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/template.yaml#L11)

I'll add this to our current sprint to be fixed.
