### ISSUE TITLE
stuck on controlplane creation

### ISSUE THREAD

**Issue by GurayCetin** [aws/eks-anywhere#2195]
After etcd is created, cluster creation is stuck on control plane and giving timeout issue. 
What can the root cause be? 

Note: This is our second attempt to create cluster and the second time we are getting same error.

```
---------    V3      Waiting for external etcd to be ready   {"cluster": "mgmt1"}
---------    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1652785943679378777 kubectl wait --timeout 60m --for=condition=ManagedEtcdReady [clusters.cluster.x-k8s.io/mgmt1](http://clusters.cluster.x-k8s.io/mgmt1) --kubeconfig mgmt1/generated/mgmt1.kind.kubeconfig -n eksa-system"}
---------    V3      External etcd is ready
---------    V3      Waiting for control plane to be ready
---------    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1652785943679378777 kubectl wait --timeout 60m --for=condition=ControlPlaneReady [clusters.cluster.x-k8s.io/mgmt1](http://clusters.cluster.x-k8s.io/mgmt1) --kubeconfig mgmt1/generated/mgmt1.kind.kubeconfig -n eksa-system"}
```

**Comment by GurayCetin** [comment]
I could not share cluster config file, it's from customer installation. However it's not different from vsphere config files. 
How can I get capi/capv logs?  and when i get the support bundle, how can i check the file?

**Comment by vincentni** [comment]
You can get more information on how to retrieve logs from https://anywhere.eks.amazonaws.com/docs/tasks/troubleshoot/troubleshooting/.  As for the support bundle, please refer to https://anywhere.eks.amazonaws.com/docs/tasks/troubleshoot/supportbundle/ for how to generate and analyze it. Thank you!

**Comment by GurayCetin** [comment]
Hi again, I obtained the bundle zip. 
When i checked the **capi-kubeadm-control-plane-controller-manager.log**, it shows;

**APIServerPodHealthy condition, machine mgmt1-nlbcw does not have ControllerManagerPodHealthy condition, machine mgmt1-nlbcw does not have SchedulerPodHealthy condition**

What is your opinion for issue? 
Please let me know which logs are also needed for further investigation.

`
controller/kubeadmcontrolplane "msg"="Reconcile KubeadmControlPlane" "cluster"="mgmt1" "name"="mgmt1" "namespace"="eksa-system" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane" 
controller/kubeadmcontrolplane 
`

`
"msg"="Scaling up control plane" "cluster"="mgmt1" "name"="mgmt1" "namespace"="eksa-system" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane" "Desired"=3 "Existing"=1
`

`
"msg"="Waiting for control plane to pass preflight checks" "cluster-name"="mgmt1" "name"="mgmt1" "namespace"="eksa-system" "failures"="[machine mgmt1-nlbcw does not have **APIServerPodHealthy condition, machine mgmt1-nlbcw does not have ControllerManagerPodHealthy condition, machine mgmt1-nlbcw does not have SchedulerPodHealthy condition**]"
`

`controller/kubeadmcontrolplane "msg"="Failed to update KubeadmControlPlane Status" "error"="failed to create remote cluster client: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"eksa-system/mgmt1\": Get \"https://***HIDDEN***:6443/api?timeout=10s\": dial tcp ***HIDDEN***:6443: connect: no route to host" "cluster"="mgmt1" "name"="mgmt1" "namespace"="eksa-system" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane" `

`controller/kubeadmcontrolplane "msg"="Reconciler error" "error"="failed to create remote cluster client: error creating client and cache for remote cluster: error creating dynamic rest mapper for remote cluster \"eksa-system/mgmt1\": Get \"https://***HIDDEN***:6443/api?timeout=10s\": dial tcp ***HIDDEN***:6443: connect: no route to host" "name"="mgmt1" "namespace"="eksa-system" "reconciler group"="controlplane.cluster.x-k8s.io" "reconciler kind"="KubeadmControlPlane" 
`


**capi-controller-manager.log;**


`controller/machine "msg"="Bootstrap provider is not ready, requeuing" "cluster"="mgmt1" "name"="mgmt1-md-0-788d799b56-pccwr" "namespace"="eksa-system" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" 
`

`controller/machine "msg"="Infrastructure provider is not ready, requeuing" "cluster"="mgmt1" "name"="mgmt1-md-0-788d799b56-pccwr" "namespace"="eksa-system" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine"
` 

`controller/machine "msg"="Cannot reconcile Machine's Node, no valid ProviderID yet" "cluster"="mgmt1" "machine"="mgmt1-md-0-788d799b56-pccwr" "name"="mgmt1-md-0-788d799b56-pccwr" "namespace"="eksa-system" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Machine" 
`

**Comment by vincentni** [comment]
> Get \"https://***HIDDEN***:6443/api?timeout=10s\": dial tcp ***HIDDEN***:6443: connect: no route to host"
It looks like a network/IP table issue

**Comment by GurayCetin** [comment]
So how can i resolve this issue?

**Comment by vincentni** [comment]
Check your DNS and iptable setup to make sure the HIDDEN part from `https://***HIDDEN***:6443/` needs to be resolvable and reachable from the various pods.

**Comment by vincentni** [comment]
You can find a lot more resources on dns and iptable online. Here is what I find that might help you get started.
