### ISSUE TITLE
list images command does not work with --bundles-override flag

### ISSUE THREAD

**Issue by wongni** [aws/eks-anywhere#2213]
**What happened**:

```
eksctl anywhere list images -f my-cluster.yaml --bundles-override=manifest.yaml
Error: unknown flag: --bundles-override
```

**What you expected to happen**:

`list images' command with `--bundles-override` flag should list images found in the overridden bundle manifest file

**How to reproduce it (as minimally and precisely as possible)**:

Run `eksctl anywhere list images` with `--bundles-override` flag

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.9.1
- EKS Distro Release: 0.80.0

**Comment by vincentni** [comment]
`--bundles-override` is valid for cluster creation only at this moment.
