### ISSUE TITLE
Add survey link to eksctl anywhere output

### ISSUE THREAD

**Issue by jicowan** [aws/eks-anywhere#2255]
**What would you like to be added**:
Output a link to a customer satisfaction survey after EKS-A is installed. 

**Why is this needed**:
To capture customers feedback.

You can add the following after this [line](https://github.com/aws/eks-anywhere/blob/3b76b611965e50fb1ad91dac6ff335dce04800ad/cmd/eksctl-anywhere/cmd/createcluster.go#L210) in the createcluster.go file: 
```go
fmt.Fprintln("\nThank you for installing EKS-A. Please take a moment to tell us about your experience! https://link-to-survey")
```

**Comment by mitalipaygude** [comment]
Adding a 👍🏼 to gauge interest.

**Comment by mitalipaygude** [comment]
Adding to our backlog.
