### ISSUE TITLE
Add docs to explain management and workload clusters

### ISSUE THREAD

**Issue by abhinavmpandey08** [aws/eks-anywhere#2257]
**What would you like to be added**:
Docs explaining what management and workload clusters are and the use cases for each.

**Why is this needed**:
The docs for [creating production cluster](https://anywhere.eks.amazonaws.com/docs/getting-started/production-environment/) currently just mention management and workload clusters but don't really describe them which makes it confusing for users installing EKS Anywhere for the 1st time.

**Comment by chrisnegus** [comment]
A new [Cluster topologies](https://anywhere.eks.amazonaws.com/docs/concepts/cluster-topologies/) page was added to satisfy this request. See [PR #4070](https://github.com/aws/eks-anywhere/pull/4070) for details.
