### ISSUE TITLE
Collect workload cluster support bundle on control plane wait failure

### ISSUE THREAD

**Issue by jaxesn** [aws/eks-anywhere#2265]
**What happened**:
During cluster creation failure if a failure happens after between [here](https://github.com/aws/eks-anywhere/blob/a908ea1269a594def5fc79be4cce5fccf20c60e5/pkg/clustermanager/cluster_manager.go#L255) and [here](https://github.com/aws/eks-anywhere/blob/a908ea1269a594def5fc79be4cce5fccf20c60e5/pkg/clustermanager/cluster_manager.go#L266) when collectdiagtask is run [here](https://github.com/aws/eks-anywhere/blob/a908ea1269a594def5fc79be4cce5fccf20c60e5/pkg/workflows/create.go#L201) the workloadcluster is not set on the context. This results in the call to collect being skipped due to [this](https://github.com/aws/eks-anywhere/blob/a908ea1269a594def5fc79be4cce5fccf20c60e5/pkg/clustermanager/cluster_manager.go#L659)

**What you expected to happen**:

Any failure after [this](https://github.com/aws/eks-anywhere/blob/a908ea1269a594def5fc79be4cce5fccf20c60e5/pkg/clustermanager/cluster_manager.go#L250) should generate a support bundle from the workload cluster.

Talking with @g-gaston the quickest, most reasonable, change would be to move the cp wait and move extra objects calls to a new method, returning from createworkloadcluster immediately after getting a kubeconfig.  [CreateWorkloadCluster](https://github.com/aws/eks-anywhere/blob/a908ea1269a594def5fc79be4cce5fccf20c60e5/pkg/workflows/create.go#L196) would then call the new method to wait for the cp and apply extraobjects.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by vivek-koppuru** [comment]
Need to either support the newer version of troubleshoot or refactor the code to not always default to running the crd collectors. Will implement the refactoring first and then merge #2431 , and then upgrade troubleshoot to support podspec in our collectors.
