### ISSUE TITLE
`aws-iam-authenticator` pulling `busybox` from docker.io

### ISSUE THREAD

**Issue by g-gaston** [aws/eks-anywhere#2317]
**What happened**:

The `iam-authenticator` DS we install has a init container that pulls `busybox` from docker.io

**What you expected to happen**:

All images should come from public ECR
Change https://github.com/aws/eks-anywhere/blob/2c8ce23c55cbd68e26267abe27abe0699a43c276/pkg/awsiamauth/config/aws-iam-authenticator.yaml#L160
to point to our ecr account, preferably taking the image from the bundle and templating it into the yaml file as opposed to hardcoding it.

Note: we don't need `busybox`, it can be any lightweight image that can run this command:
https://github.com/aws/eks-anywhere/blob/2c8ce23c55cbd68e26267abe27abe0699a43c276/pkg/awsiamauth/config/aws-iam-authenticator.yaml#L161

**How to reproduce it (as minimally and precisely as possible)**:

Create a docker cluster with awsiam identity provider and describe the iam-auth daemon set

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.9.1
- EKS Distro Release: all of them

**Comment by abhay-krishna** [comment]
/close
Fixed by #2356
