### ISSUE TITLE
Enabling Proxy Config with Credentails

### ISSUE THREAD

**Issue by vipulsha22** [aws/eks-anywhere#2325]
**What would you like to be added**: proxy config with username and password

**Why is this needed**: some proxies work only with username and password

**Comment by TerryHowe** [comment]
I've added a 👍 so interested parties can vote on this. Seems like a reasonable request, but I don't recall anyone else requesting this.

**Comment by vipulsha22** [comment]
Thanks  , I am stuck at a particular step for some days now. This will help in ruling out proxy related issues as my other proxy requires credentials to use.

**Comment by markapruett** [comment]
In the 0.12 release you can do this for Ubuntu on both vSphere and bare metal. If you want bottlerocket support, that's coming in the next release. Closing this out.
