### ISSUE TITLE
Bundles CRD change adding version to spec breaks upgrade

### ISSUE THREAD

**Issue by smarsh-tim** [aws/eks-anywhere#2373]
**What happened**:
The bundles.anywhere.eks.amazonaws.com/v1alpha1 CRD does not have a `version:`. This was added here: https://github.com/aws/eks-anywhere/commit/2269ffd0d695a9f7d8447f09eb3e1c492312bf7c

However, the newer versions of `eksctl anywhere` require that field to exist when executing an upgrade.

Since it's not there, this occurs:
```
   ...
Upgrading Cilium        {"oldVersion": "", "newVersion": "v1.9.13-eksa.2"}
   ...
Error: failed to upgrade cluster: invalid version for Cilium in current spec: invalid major version in semver : strconv.ParseUint: parsing "": invalid syntax
```

Which makes sense because the `oldVersion` is an empty string.

**What you expected to happen**:

I expect the newer version of `eksctl anywhere` to be backwards compatible. Potentially just assuming that an upgrade is required when the `oldVersion` is missing instead of failing entirely.

**How to reproduce it (as minimally and precisely as possible)**:

```sh
eksctl anywhere upgrade cluster \
   -f foo-bar/foo-bar-eks-a-cluster.yaml \
   --kubeconfig foo-bar/foo-bar-eks-a-cluster.kubeconfig 
   -v 5
```

**Anything else we need to know?**:

The temporary work-around I've found is to manually update the Bundles CustomResourceDefinition to add the version key. Then update my specific Bundle CustomResource with the version.

After doing so, the same `eksctl anywhere upgrade` command now finds the version:
```
Upgrading Cilium        {"oldVersion": "v1.9.10-eksa.1", "newVersion": "v1.9.13-eksa.2"}
```

**Environment**:
- EKS Anywhere Release: `v0.9.1`
- EKS Distro Release: `v1.21.2-eks-1-21-5` upgrading to `v1.21.9-eks-1-21-13`

**Comment by abhay-krishna** [comment]
Thanks for opening this issue @smarsh-tim. We will look into it and get back.

**Comment by mitalipaygude** [comment]
Any updates to the above requested information?

**Comment by smarsh-tim** [comment]
@g-gaston I don't have the Bundles details, but I do have the template versions. I've noticed that the templates seem to be closely related (almost dependent) on the EKS-a CLI release I use.  If I'm correct, this should help:

- [old] ubuntu-v1.21.2-kubernetes-1-21-eks-5-amd64
- [new] ubuntu-v1.21.9-eks-d-1-21-13-eks-a-10-amd64

**Comment by g-gaston** [comment]
@smarsh-tim That seems to be a very very old eks-a version, based on the eks-d version installed it seems like `v0.5.0`. We only support upgrading one minor version at a time. So in your case:
- `v0.6.1`
- `v0.7.2`
- `v0.8.2`
- `v0.9.2`
- `v0.10.0`

**Comment by smarsh-tim** [comment]
> @smarsh-tim That seems to be a very very old eks-a version, based on the eks-d version installed it seems like `v0.5.0`. We only support upgrading one minor version at a time. So in your case:
> 
> * `v0.6.1`
> * `v0.7.2`
> * `v0.8.2`
> * `v0.9.2`
> * `v0.10.0`

Thank you! https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-upgrades/#minor-version-upgrades - I skimmed right past that section.

**Comment by smarsh-tim** [comment]
@g-gaston It does seem that these versions of eks-d are tightly correlated to the template image that we use.

How do you recommend finding the appropriate template to pull down? This document only references artifacts that can be used using the latest version of `eksctl anywhere`: https://anywhere.eks.amazonaws.com/docs/reference/artifacts/

So if I'm currently on eks-d version `v0.5.0`, and I want to step through to `v0.10.0`, how can I find which template versions to use for each upgrade?  Assuming I'm currently on `ubuntu-v1.21.2-kubernetes-1-21-eks-5-amd64`.

**Comment by smarsh-tim** [comment]
I found it! Took me a bit to find the bundle `manifest.yaml`, I didn't realize it would be there. Once I found it, that manifest includes all the templates for both bottlerocket and ubuntu for 1.20, 1.21, and 1.22.

Manifests:
- https://anywhere-assets.eks.amazonaws.com/releases/bundles/6/manifest.yaml
    - https://anywhere-assets.eks.amazonaws.com/releases/bundles/6/artifacts/ova/1-21/ubuntu-v1.21.5-eks-d-1-21-8-eks-a-6-amd64.ova
- https://anywhere-assets.eks.amazonaws.com/releases/bundles/7/manifest.yaml
    - https://anywhere-assets.eks.amazonaws.com/releases/bundles/7/artifacts/ova/1-21/ubuntu-v1.21.5-eks-d-1-21-9-eks-a-7-amd64.ova
- https://anywhere-assets.eks.amazonaws.com/releases/bundles/8/manifest.yaml
    - https://anywhere-assets.eks.amazonaws.com/releases/bundles/8/artifacts/ova/1-21/ubuntu-v1.21.9-eks-d-1-21-11-eks-a-8-amd64.ova
- https://anywhere-assets.eks.amazonaws.com/releases/bundles/9/manifest.yaml
    - https://anywhere-assets.eks.amazonaws.com/releases/bundles/9/artifacts/ova/1-21/ubuntu-v1.21.9-eks-d-1-21-13-eks-a-9-amd64.ova
- https://anywhere-assets.eks.amazonaws.com/releases/bundles/10/manifest.yaml
    - https://anywhere-assets.eks.amazonaws.com/releases/bundles/10/artifacts/ova/1-21/ubuntu-v1.21.9-eks-d-1-21-13-eks-a-10-amd64.ova
- https://anywhere-assets.eks.amazonaws.com/releases/bundles/11/manifest.yaml
    - https://anywhere-assets.eks.amazonaws.com/releases/bundles/11/artifacts/ova/1-21/ubuntu-v1.21.13-eks-d-1-21-15-eks-a-11-amd64.ova
- https://anywhere-assets.eks.amazonaws.com/releases/bundles/12/manifest.yaml
    - https://anywhere-assets.eks.amazonaws.com/releases/bundles/12/artifacts/ova/1-21/ubuntu-v1.21.13-eks-d-1-21-16-eks-a-12-amd64.ova

---

Closing this issue as confirmed the problem is upgrading non-sequentially.
