### ISSUE TITLE
eks anywhere cluster creation hung

### ISSUE THREAD

**Issue by sagarkundral24** [aws/eks-anywhere#244]
**What happened**:
Cluster creation is hung. No logs or any errors on the sysout 

**What you expected to happen**:
Expected the cluster to be created
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

root@nirmata:~# cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

root@nirmata:~# docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:27 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

root@nirmata:~# df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                               7.8G     0  7.8G   0% /dev
tmpfs                              1.6G  1.3M  1.6G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   20G   14G  5.0G  74% /
tmpfs                              7.9G     0  7.9G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/loop0                          56M   56M     0 100% /snap/core18/2128
/dev/loop2                          71M   71M     0 100% /snap/lxd/21029
/dev/loop1                          62M   62M     0 100% /snap/core20/1081
/dev/loop3                          33M   33M     0 100% /snap/snapd/12704
/dev/loop4                          68M   68M     0 100% /snap/lxd/21545
/dev/loop5                          33M   33M     0 100% /snap/snapd/12883
/dev/sda2                          976M  107M  803M  12% /boot
overlay                             20G   14G  5.0G  74% /var/lib/docker/overlay2/78cda5c1f3d705a92419c60512c56e905ba8a73021d74cc0a32fc496f6b26b81/merged
tmpfs                              1.6G     0  1.6G   0% /run/user/0
overlay                             20G   14G  5.0G  74% /var/lib/docker/overlay2/fa411746d377028f5cb5aeff2d20f323b4f0d0906157ffd92c48cd103b2c8364/merged

root@nirmata:~# free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi       2.8Gi       7.7Gi        21Mi       5.1Gi        12Gi
Swap:         3.8Gi          0B       3.8Gi

root@nirmata:~# nproc
4  

- EKS Anywhere Release: v0.5.0
- EKS Distro Release: 0.66.0

**Comment by vignesh-goutham** [comment]
Hello @sagarkundral24! Thanks for trying out EKS-Anywhere. Could you share the command that you ran which hung?  Please also try running the command with `-v=4` for more verbosity, and share the output.

**Comment by sagarkundral24** [comment]
[eksctl-anywhere-cluster-create.log](https://github.com/aws/eks-anywhere/files/7188533/eksctl-anywhere-cluster-create.log)

**Comment by sagarkundral24** [comment]
I have attached the log file with -v 9. And here is the command that I ran

eksctl anywhere create cluster -f $CLUSTER_NAME.yaml --force-cleanup -v 9

**Comment by sagarkundral24** [comment]
Please find attached the log file with max verbosity. 
[eks-anywhere-cluster-create.log](https://github.com/aws/eks-anywhere/files/7188621/eks-anywhere-cluster-create.log)

**Comment by vignesh-goutham** [comment]
Thanks for sharing the output. It looks like it's waiting for the control plane to be ready. It takes sometime at this point for the cluster to come up.

You can check if pods are coming up on the cluster with
`kubectl --kubeconfig dev-cluster/dev-cluster-eks-a-cluster.kubeconfig get pods -A`

**Comment by sagarkundral24** [comment]
Hi, thanks for checking. Its been like this for more than 30 minutes.

root@nirmata:~# kubectl --kubeconfig dev-cluster/dev-cluster-eks-a-cluster.kubeconfig get pods -A
error: stat dev-cluster/dev-cluster-eks-a-cluster.kubeconfig: no such file or directory

root@nirmata:~# ls -lrth dev-cluster
total 4.0K
drwxr-xr-x 3 root root 4.0K Sep 17 21:44 generated

**Comment by vignesh-goutham** [comment]
Can you check on the pods on kind cluster. You can run `kubectl --kubeconfig dev-cluster/generated/dev-cluster.kind.kubeconfig get pods -A`? Sometimes this happens when docker doesnt have enough memory. You could check that with `docker info --format '{{json .MemTotal}}'`. You can also check on the resources the containers are consuming with `docker stats --all`. If there arent enough resources, you can clean up the host with `docker system prune`

**Comment by gohmc** [comment]
`2021-09-17T21:44:49.529Z	V6	Executing command	{"cmd": "/usr/bin/docker run -i --network host -v /root:/root -w /root -v /var/run/docker.sock:/var/run/docker.sock --entrypoint kubectl public.ecr.aws/eks-anywhere/cli-tools:v0.1.0-eks-a-1 wait --timeout 60m --for=condition=ControlPlaneReady clusters.cluster.x-k8s.io/dev-cluster --kubeconfig dev-cluster/generated/dev-cluster.kind.kubeconfig -n eksa-system"}`

Same incident to https://github.com/aws/eks-anywhere/issues/221

**Comment by sagarkundral24** [comment]
@vignesh-goutham Here is the output from the command. 

root@nirmata:~# kubectl --kubeconfig dev-cluster/generated/dev-cluster.kind.kubeconfig get pods -A
NAMESPACE                           NAME                                                              READY   STATUS    RESTARTS   AGE
capd-system                         capd-controller-manager-659dd5f8bc-c8t4p                          2/2     Running   0          85m
capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-69889cb844-ldlxk        2/2     Running   0          85m
capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-6ddc66fb75-8ctjh    2/2     Running   0          85m
capi-system                         capi-controller-manager-db59f5789-qszsn                           2/2     Running   0          85m
capi-webhook-system                 capi-controller-manager-64b8c548db-9cwss                          2/2     Running   0          85m
capi-webhook-system                 capi-kubeadm-bootstrap-controller-manager-68b8cc9759-j7pnr        2/2     Running   0          85m
capi-webhook-system                 capi-kubeadm-control-plane-controller-manager-7dc88f767d-9spv7    2/2     Running   0          85m
cert-manager                        cert-manager-5f6b885b4-k6sjf                                      1/1     Running   0          86m
cert-manager                        cert-manager-cainjector-bb6d9bcb5-t8bwx                           1/1     Running   0          86m
cert-manager                        cert-manager-webhook-56cbc8f5b8-6f9w6                             1/1     Running   0          86m
kube-system                         coredns-7c68f85774-tl82g                                          1/1     Running   0          86m
kube-system                         coredns-7c68f85774-v4gcl                                          1/1     Running   0          86m
kube-system                         etcd-dev-cluster-eks-a-cluster-control-plane                      1/1     Running   0          86m
kube-system                         kindnet-2bn8q                                                     1/1     Running   0          86m
kube-system                         kube-apiserver-dev-cluster-eks-a-cluster-control-plane            1/1     Running   0          86m
kube-system                         kube-controller-manager-dev-cluster-eks-a-cluster-control-plane   1/1     Running   0          86m
kube-system                         kube-proxy-xt7dk                                                  1/1     Running   0          86m
kube-system                         kube-scheduler-dev-cluster-eks-a-cluster-control-plane            1/1     Running   0          86m
local-path-storage                  local-path-provisioner-666bfc797f-jbmh2                           1/1     Running   0          86m

root@nirmata:~# docker info --format '{{json .MemTotal}}'
16791515136


However my cluster creation is still stuck at below point. I also tried to do a docker system prune before starting over again. Not sure if its a resource issue or something else. 

2021-09-18T02:12:46.119Z        V3      Waiting for control plane to be ready
2021-09-18T02:12:46.119Z        V6      Executing command       {"cmd": "/usr/bin/docker run -i --network host -v /root:/root -w /root -v /var/run/docker.sock:/var/run/docker.sock --entrypoint kubectl public.ecr.aws/eks-anywhere/cli-tools:v0.1.0-eks-a-1 wait --timeout 60m --for=condition=ControlPlaneReady clusters.cluster.x-k8s.io/dev-cluster --kubeconfig dev-cluster/generated/dev-cluster.kind.kubeconfig -n eksa-system"}

**Comment by sagarkundral24** [comment]
@vignesh-goutham Please let me know if I need to provide any more information...

**Comment by gohmc** [comment]
@sagarkundral24, if you can provide the info mentioned here https://github.com/aws/eks-anywhere/issues/221#issuecomment-923185912 to @jaxesn will be great.

**Comment by sagarkundral24** [comment]
I found below error in the /var/log/syslog, so I manually pulled that image on the host by doing docker login. That fixed the problem for me.


Error from syslog: 

Unable to find image 'kindest/haproxy:v20210715-a6da3463' locally
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.

**Comment by sagarkundral24** [comment]
Issue resolved

**Comment by gauravmittal80** [comment]
Hi Team,

I am also getting the same error and the script is failing as below. As per this blog i have checked there are enough resources available. and also checked the syslog and i have not get any error.

Creating new workload cluster
collecting cluster diagnostics
collecting management cluster diagnostics
⏳ Collecting support bundle from cluster, this can take a while        {"cluster": "bootstrap-cluster", "bundle": "eks2/generated/bootstrap-cluster-2022-03-21T17:56:39+05:30-bundle.yaml", "since": 1647861999765407215, "kubeconfig": "eks2/generated/eks2.kind.kubeconfig"}
Support bundle archive created  {"path": "support-bundle-2022-03-21T12_26_40.tar.gz"}
Analyzing support bundle        {"bundle": "eks2/generated/bootstrap-cluster-2022-03-21T17:56:39+05:30-bundle.yaml", "archive": "support-bundle-2022-03-21T12_26_40.tar.gz"}
Analysis output generated       {"path": "eks2/generated/bootstrap-cluster-2022-03-21T17:58:18+05:30-analysis.yaml"}
collecting workload cluster diagnostics
Error: failed to create cluster: error checking availability of kubeconfig secret: kubeconfig secret does not exist
airvana@svt-admin-machine:~$
