### ISSUE TITLE
Support different OS families for vSphere machines

### ISSUE THREAD

**Issue by abhay-krishna** [aws/eks-anywhere#246]
We currently support only a single OS family across all vSphere machine nodes - controlplane, worker and `etcd`. It would be nice to allow customers to specify different combinations of OS families for vSphere machines per their requirements.

**Comment by abhay-krishna** [comment]
Closed since this is already taken care of.

**Comment by vignesh-goutham** [comment]
CAPI & kubeadm works in a way where worker join will pull `initConfiguration` from the cluster. In order to support different os families, we should make sure the `initConfiguration's` fields are compatible and valid across the different families.
