### ISSUE TITLE
Operation not permitted docker provider

### ISSUE THREAD

**Issue by ayushghosh** [aws/eks-anywhere#249]
Tried to create the cluster in local docker provider

**What you expected to happen**:
Create a cluster in local

**How to reproduce it (as minimally and precisely as possible)**:

Just followed the docs.

**Anything else we need to know?**:
OS: MACOS 11.6
Docker Desktop 3.6.0

**Environment**:
- EKS Anywhere Release:

Output/Error:
➜  eks eksctl anywhere create cluster -f $CLUSTER_NAME.yaml

Performing setup and validations
Warning: The docker infrastructure provider is meant for local development and testing only
✅ Docker Provider setup is valid
Creating new bootstrap cluster
Error: failed to create cluster: error creating bootstrap cluster: error executing create cluster: ERROR: failed to create cluster: error reading file: open dev-cluster/generated/kind_tmp.yaml: operation not permitted
, try rerunning with --force-cleanup to force delete previously created bootstrap cluster

**Comment by ayushghosh** [comment]
works from /tmp seems issue with the volume mount issue

**Comment by TerryHowe** [comment]
It almost sounds like it was able to write the file, but not read it. What is your `umask` set to? Mine is 022 which I think is default. You running zsh?

**Comment by TerryHowe** [comment]
Yes, 10m sounds about right. You are constrained by local resources, so more RAM would probably speed things up. The docker cluster goes through all the work that you would do for a production cluster, so it isn't much faster than that. I normally get around 13m for a prod cluster.

So, I take it you got a cluster up

**Comment by ayushghosh** [comment]
Yeah it worked like a charm once I tried from /tmp

Thanks!
