### ISSUE TITLE
Failed creating library for template when there are more than one datacenter in vsphere

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#2614]
**What happened**:

CLI fails when creating a vsphere cluster for vCenter with multiple datacenters, without `template` field specified.

:x: Validation failed  {"validation": "vsphere Provider setup is valid", "error": "failed setting default values for vsphere machine configs: failed creating library for new template: creating library eks-a-templates: govc: please specify a datacenter\n", "remediation": ""}

**What you expected to happen**:

CLI to successfully create library.

**How to reproduce it (as minimally and precisely as possible)**:

1. Not specifying `template` field in `vspheremachineconfig`
2. vCenter with more than one datacenters and the user has access to all of them.

Run `eksctl anywhere create cluster` cmd

**Anything else we need to know?**:

Cause: https://github.com/aws/eks-anywhere/blob/main/pkg/executables/govc.go#L287-L292

When user does not specify the template, EKS-A creates a library and then imports template from upstream. `CreateLibrary` method does not specify which datacenter to use, thus preflight validation fails when there are multiple datacenters.

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by vivek-koppuru** [comment]
Might be as simple as adding a `GOVC_DATACENTER` env var to our commands, trying that as a potential solution

**Comment by jaxesn** [comment]
Can we use the datacenter from the spec instead of introducing a new env var?

**Comment by vivek-koppuru** [comment]
This is regarding the env var to pass into `govc`, not a new user specified env var. We would populate that env var from what you are suggesting.
