### ISSUE TITLE
deploy cluster stuck in control-plane prepare on vsphere 7u2

### ISSUE THREAD

**Issue by kengkunnutthanon** [aws/eks-anywhere#265]
Hello.
I deployed eks on vsphere 7u2 but when control plane node created and wait to complete, It's always stuck until time out.
I tried many times with bottlerocket or ubuntu image but not worked.
In verbose console show status like this and then I wait until timeout.
2021-09-21T15:45:08.973Z        V0      Creating new workload cluster
2021-09-21T15:45:08.974Z        V6      Executing command       {"cmd": "/usr/bin/docker run -i --network host -v /root:/root -w /root -v /var/run/docker.sock:/var/run/docker.sock --entrypoint kubectl public.ecr.aws/eks-anywhere/cli-tools:v0.1.0-eks-a-1 apply -f keng-eks6/generated/keng-eks6-eks-a-cluster.yaml --namespace eksa-system --kubeconfig keng-eks6/generated/keng-eks6.kind.kubeconfig"}
2021-09-21T15:45:10.421Z        V5      Retry execution successful      {"retries": 1, "duration": "1.446800782s"}
2021-09-21T15:45:10.421Z        V3      Waiting for control plane to be ready
2021-09-21T15:45:10.421Z        V6      Executing command       {"cmd": "/usr/bin/docker run -i --network host -v /root:/root -w /root -v /var/run/docker.sock:/var/run/docker.sock --entrypoint kubectl public.ecr.aws/eks-anywhere/cli-tools:v0.1.0-eks-a-1 wait --timeout 60m --for=condition=ControlPlaneReady clusters.cluster.x-k8s.io/keng-eks6 --kubeconfig keng-eks6/generated/keng-eks6.kind.kubeconfig -n eksa-system"}

And in vcenter ui 4 vms created as picture below (I set config file for deploy 3 masters and 3 workers).

![image](https://user-images.githubusercontent.com/91147153/134210719-66978899-53e0-405a-a8ff-c226495c0e32.png)

**Environment**:
- EKS Anywhere Release: 
- EKS Distro Release: eksdRelease:kubernetes-1-21-eks-4

**Comment by bnrjee** [comment]
Hi,
Thanks for trying out eks-anywhere and creating this issue. 
Is it a transient issue or are you still seeing this?
To debug further on this, we might need some more data.
We would typically look into the manager containers of the following pods of kind cluster.
capd-controller-manager 
capi-kubeadm-bootstrap-controller-manager
capi-kubeadm-control-plane-controller-manager
capi-controller-manager-849cc49d99-wwht7   
You can find the kubeconfig for this in <cluster_name>/generated directory. Alternatively you can check if you have the <cluster_name>/logs directory created. You can get some of those logs from there as well.
We would also like to see the output of the kubectl describe machines command on the control-plane (keng-eks6-ch4t7 in this case). 
The next step would be to log into the vsphere nodes and look into some of these control plane logs as mentioned here.
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/
Would it be possible for you to share some of these information? This would help us debug this problem.
We also have a eksa-anywhere troubleshooting page, in case you want to debug it further.
https://anywhere.eks.amazonaws.com/docs/tasks/troubleshoot/_troubleshooting/

**Comment by bnrjee** [comment]
> Hi,
> Thanks for trying out eks-anywhere and creating this issue.
> Is it a transient issue or are you still seeing this?
> To debug further on this, we might need some more data.
> We would typically look into the manager containers of the following pods of kind cluster.
> capv-controller-manager
> capi-kubeadm-bootstrap-controller-manager
> capi-kubeadm-control-plane-controller-manager
> capi-controller-manager-849cc49d99-wwht7
> You can find the kubeconfig for this in <cluster_name>/generated directory. Alternatively you can check if you have the <cluster_name>/logs directory created. You can get some of those logs from there as well.
> We would also like to see the output of the kubectl describe machines command on the control-plane (keng-eks6-ch4t7 in this case).
> The next step would be to log into the vsphere nodes and look into some of these control plane logs as mentioned here.
> https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/
> Would it be possible for you to share some of these information? This would help us debug this problem.
> We also have an eksa-anywhere troubleshooting page, in case you want to debug it further.
> https://anywhere.eks.amazonaws.com/docs/tasks/troubleshoot/_troubleshooting/

Hi @kengkunnutthanon,
Would it be possible for you to provide us with these data?

**Comment by sagarkundral24** [comment]
#244

**Comment by kengkunnutthanon** [comment]
> > Hi,
> > Thanks for trying out eks-anywhere and creating this issue.
> > Is it a transient issue or are you still seeing this?
> > To debug further on this, we might need some more data.
> > We would typically look into the manager containers of the following pods of kind cluster.
> > capv-controller-manager
> > capi-kubeadm-bootstrap-controller-manager
> > capi-kubeadm-control-plane-controller-manager
> > capi-controller-manager-849cc49d99-wwht7
> > You can find the kubeconfig for this in <cluster_name>/generated directory. Alternatively you can check if you have the <cluster_name>/logs directory created. You can get some of those logs from there as well.
> > We would also like to see the output of the kubectl describe machines command on the control-plane (keng-eks6-ch4t7 in this case).
> > The next step would be to log into the vsphere nodes and look into some of these control plane logs as mentioned here.
> > https://kubernetes.io/docs/tasks/debug-application-cluster/debug-cluster/
> > Would it be possible for you to share some of these information? This would help us debug this problem.
> > We also have an eksa-anywhere troubleshooting page, in case you want to debug it further.
> > https://anywhere.eks.amazonaws.com/docs/tasks/troubleshoot/_troubleshooting/
> 
> Hi @kengkunnutthanon,
> Would it be possible for you to provide us with these data?

Hello.
I will provide this information to you on next Monday.
Sorry for any inconvenience.
Regards.

**Comment by kengkunnutthanon** [comment]
Hello,

I attached container log file and log file from generated folder of kind cluster. Noted that I deleted keng-eks6 vm already so I used keng-eks7 cluster instead.
I will upload control-plane machine log of keng-eks7-9c7gw to you later.
Regards.
[logs.zip](https://github.com/aws/eks-anywhere/files/7233581/logs.zip)
[Container log.zip](https://github.com/aws/eks-anywhere/files/7233582/Container.log.zip)

**Comment by kengkunnutthanon** [comment]
Hi.
When I run kubectl cmd on node keng-eks7-9c7gw, I got this error

kubectl get pod -A -o wide
The connection to the server localhost:8080 was refused - did you specify the right host or port?

Regards.

**Comment by abhay-krishna** [comment]
> Hi.
> When I run kubectl cmd on node keng-eks7-9c7gw, I got this error
> 
> kubectl get pod -A -o wide
> The connection to the server localhost:8080 was refused - did you specify the right host or port?
> 
> Regards.

Can you try passing in the kubeconfig file of your EKS-A cluster using the `--kubeconfig` arg (recommended) or by setting the env variable `KUBECONFIG`?
