### ISSUE TITLE
WorkerNodeGroupConfiguration.count default to 1

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#2657]
**What happened**:

https://github.com/aws/eks-anywhere/blob/main/pkg/api/v1alpha1/cluster_types.go#L233

We claim to default the `workerNodeGroupConfiguration.count` to 1 but the current code sets `machinedeployment.spec.replicas` = 0 if count not specified.

**What you expected to happen**:

We should
1. set `workerNodeGroupConfiguration.count` default to 1
2. add validation logic: `workerNodeGroupConfiguration.count != 0` or the cluster creation fails with cert manager not able to be installed on workload cluster since by default it's deployed to worker node.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by taneyland** [comment]
#2728
