### ISSUE TITLE
Validation process does not stop on error

### ISSUE THREAD

**Issue by wongni** [aws/eks-anywhere#2717]
**What happened**:
When there are multiple validation steps the validation process continues the remaining validation steps even after one of the steps returns an error. 

For example, there are two validation steps for the upgrade cluster command.

```
func (s *setupAndValidateTasks) validations(ctx context.Context, commandContext *task.CommandContext) []validations.Validation {
	return []validations.Validation{
		func() *validations.ValidationResult {
			return &validations.ValidationResult{
				Name: fmt.Sprintf("%s Provider setup is valid", commandContext.Provider.Name()),
				Err:  commandContext.Provider.SetupAndValidateUpgradeCluster(ctx, commandContext.ManagementCluster, commandContext.ClusterSpec),
			}
		},
		func() *validations.ValidationResult {
			return &validations.ValidationResult{
				Name: "upgrade preflight validations pass",
				Err:  commandContext.Validations.PreflightValidations(ctx),
			}
		},
	}
}
```

Even after the first validation step fails the second validation step is executed and the final message does not contain the error from the first step. 

```
Performing setup and validations
❌ Validation failed    {"validation": "cloudstack Provider setup is valid", "error": "validating environment variables: EKSA_CLOUDSTACK_B64ENCODED_SECRET is not set or is empty", "remediation": ""}
✅ Validate certificate for registry mirror
✅ Control plane ready
✅ Worker nodes ready
✅ Nodes ready
✅ Cluster CRDs ready
✅ Cluster object present on workload cluster
✅ Upgrade cluster kubernetes version increment
❌ Validation failed    {"validation": "upgrade preflight validations pass", "error": "validation failed with 1 errors: spec.controlPlaneConfiguration.endpoint is immutable", "remediation": ""}
Error: failed to upgrade cluster: validations failed
```

The first validation failed message is the real validation failure and the last failed message is still printed even though the last validation step passes. 

**What you expected to happen**:

The validation process stops on any error from a validation step. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.10.1
- EKS Distro Release: v0.82.0

**Comment by vivek-koppuru** [comment]
Why don't we want all the validations to run through? This gives the user more information rather than having the run the command again. This was done by design.
