### ISSUE TITLE
Machine health check support for multi worker node group

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#2722]
**What happened**:

When adding machine health check for snow provider: #2721, I realize all the other providers do not support multi worker node group machine health check.

https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/machine-health-check-template.yaml#L12
The template only generate one worker machine health check for machine that has the hardcoded label `cluster.x-k8s.io/deployment-name: "{{.clusterName}}-md-0"`. This machine might not even exist if user specify a custom worker node group name other that the default `md-0`.

**What you expected to happen**:

We should generate machine health check for every single worker node group / machine deployment. #2721 covers most of the logic but the API builder is not widely used in other provider than snow yet.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by taneyland** [comment]
#2751
