### ISSUE TITLE
Replace kube-vip with MetalLB to expose Tinkerbell services

### ISSUE THREAD

**Issue by abhinavmpandey08** [aws/eks-anywhere#2745]
For EKS-A baremetal, we expose Tinkerbell services using kube-vip loadbalancer. We recently released MetalLB curated package and that will be the default LB so we need to migrate the Tinkerbell services to use that instead

**Comment by DavidSpek** [comment]
May I ask why MetalLB was chosen over kube-vip? As I mentioned [here](https://github.com/aws/eks-anywhere/issues/550#issuecomment-985632635), one benefit of kube-vip is that it can load balance services as well as the Kubernetes API.

**Comment by abhinavmpandey08** [comment]
This is for an internal dependency of Tinkerbell stack that is used for creating bare-metal clusters. We did decide to stick with kube-vip actually so ignore this issue
