### ISSUE TITLE
AWS IAM Authenticator for bare-metal clusters

### ISSUE THREAD

**Issue by pokearu** [aws/eks-anywhere#2749]
### Description
EKS-A provides integration for `aws-iam-authenticator`. We need to enable and validate the integration for bare-metal cluster creation workflow.

**Comment by SeungyeopShin** [comment]
Hi @pokearu 
I'm trying to install EKS-A for bare-metal on own bare-metal cluster with aws-iam-authenticator.
Does EKS-A for bare-meta not yet support aws-iam-authenticator?

**Comment by helloyeops** [comment]
Hi @pokearu
I'm trying to install EKS-A for bare-metal on own bare-metal cluster with aws-iam-authenticator.
Does EKS-A for bare-meta not yet support aws-iam-authenticator?

**Comment by pokearu** [comment]
@helloyeops Hi, apologies for the late response. We are currently working to add IAM Authenticator integrated support for bare metal clusters in the upcoming release.
