### ISSUE TITLE
Issue trying to set controlPlaneConfiguration.Endpoint.Host

### ISSUE THREAD

**Issue by robbo10** [aws/eks-anywhere#2789]
**What happened**:
When trying to run `eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml` we get the following error:

 ❌ Validation failed    {"validation": "vsphere Provider setup is valid", "error": "cluster controlPlaneConfiguration.Endpoint.Host <X.X.X.X> is already in use, please provide a unique IP", "remediation": ""}

However the IP we are trying to use if free and does not respond to ping. 

**What you expected to happen**:
To get past this error and the control plane get assigned an IP

**How to reproduce it (as minimally and precisely as possible)**:
Run `eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml`

**Anything else we need to know?**:
We are running this from local laptop to a VSphere 7 cluster, the network we are using is VDS.  We did configure a DHCP server but its currently powered off, this was to see if we could get past this error.

The network which we are using within our VSphere 7 cluster is using VDS.  We have stopped the DHCP server running to see if it could get past this stage but no joy.
**Environment**:
- EKS Anywhere Release:

**Comment by TerryHowe** [comment]
This validation would be done from the administrative machine and if there is an IP listening on ssh or http ports, that validation is going to fail. It does not test for ICMP, so your ping test does not replicate the ping test https://github.com/aws/eks-anywhere/blob/main/pkg/networkutils/networkutils.go#L33

**Comment by abhinavmpandey08** [comment]
To add to what Terry mentioned, if you are confident that the IP is not taken, you can skip the validation using `--skip-ip-check` flag in the `eksctl anywhere create cluster` command.

**Comment by robbo10** [comment]
Thanks @TerryHowe @abhinavmpandey08 , this moved us forward 🙂
