### ISSUE TITLE
Support bundle hangs for more than 60m for cloudstack

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#2794]
**What happened**:

When create/upgrade CLI fails for cloudstack provider, generating support bundle step takes longer than 60m.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by maxdrib** [comment]
Given some logs from the user's environment, the issue appears to be resolved.
