### ISSUE TITLE
Update doc to use the new import images command

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#2834]
**What would you like to be added**:

We deprecated a couple of CLI commands: https://github.com/aws/eks-anywhere/blob/main/designs/air-gapped.md#deprecated-commands in favor of the new `import images` command. We need to reflect it in our official doc: https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/optional/registrymirror/#import-images-into-a-private-registry

**Why is this needed**:

**Comment by hitsub2** [comment]
According to the docs, the following command returns an error:

```
eksctl anywhere import images -i eks-anywhere-images.tar
Error: required flag(s) "bundles", "registry" not set
```
For bundles, how can we got that? Is there any documentation?

**Comment by TerryHowe** [comment]
What @jiayiwang7 posted
```
eksctl anywhere import images \
    -i artifacts.tar.gz \
    -r $REGISTRY_IP:443 \
    --bundles ./bundle-release.yaml \
    --insecure=true
```
