### ISSUE TITLE
download images command does not work with proxy

### ISSUE THREAD

**Issue by wongni** [aws/eks-anywhere#2837]
**What happened**:

```
$ eksctl anywhere download images  --output artifacts.tar
Pulling images from origin, this might take a while
Writing images to disk
Pulling images from origin, this might take a while
Writing images to disk
Saving helm chart to disk	{"chart": "public.ecr.aws/eks-anywhere/eks-anywhere-packages:0.1.13-eks-a-12"}
Error: downloading chart [public.ecr.aws/eks-anywhere/eks-anywhere-packages:0.1.13-eks-a-12] from registry: Error: failed to do request: Head "https://public.ecr.aws/v2/eks-anywhere/eks-anywhere-packages/manifests/0.1.13-eks-a-12": dial tcp 99.83.145.10:443: connect: connection timed out
```

**What you expected to happen**:
The command should work with proxy

**How to reproduce it (as minimally and precisely as possible)**:
Run `eksctl anywhere download images  --output artifacts.tar` with proxy

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.10.1
- EKS Distro Release: 0.106.0

**Comment by jiayiwang7** [comment]
We did fix the issue of passing proxy ENVs from clusterSpec into helm executable: https://github.com/aws/eks-anywhere/pull/2032

But since `download images` command does not use clusterSpec, we need to pass the proxy ENVs from the user environment instead, to run helm commands.
