### ISSUE TITLE
add documentation around manual cluster reconciliation pause

### ISSUE THREAD

**Issue by sleterrier** [aws/eks-anywhere#2846]
**What would you like to be added**: Explicit documentation about pausing cluster reconciliation.

We recently needed to manually pause cluster reconciliation to perform an extended maintenance on our underlying ESX cluster (during which the vSphere Virtual Machines had to stay down). Here is what we learned in the process:

* CAPI defines [spec.paused](https://pkg.go.dev/sigs.k8s.io/cluster-api/api/v1beta1?utm_source=godoc#ClusterSpec)  to prevent CAPI controllers from processing the cluster and all its associated objects.
* Annotation `anywhere.eks.amazonaws.com/paused: "true"` must be added to the parent EKS-A cluster object (`clusters.anywhere.eks.amazonaws.com`) to prevent eksa-controller-manager from reverting `spec.paused` on managed CAPI cluster object (`clusters.cluster.x-k8s.io`).

  Example:
  ```
  export WORKLOAD_CLUSTER_NAME="workload-cluster"
  export WORKLOAD_CLUSTER_NAMESPACE="default"
  
  kubectl --kubeconfig mgmt-cluster/mgmt-cluster-eks-a-cluster.kubeconfig patch clusters.anywhere.eks.amazonaws.com -n ${WORKLOAD_CLUSTER_NAMESPACE} ${WORKLOAD_CLUSTER_NAME} --type merge -p '{"metadata":{"annotations":{"anywhere.eks.amazonaws.com/paused": "true"}}}'
  
  kubectl --kubeconfig mgmt-cluster/mgmt-cluster-eks-a-cluster.kubeconfig patch clusters.cluster.x-k8s.io -n eksa-system $WORKLOAD_CLUSTER_NAME --type merge -p '{"spec":{"paused": true}}'
  ```

It took a few detours to find out about the `anywhere.eks.amazonaws.com/paused: "true"` annotation, having it clearly documented under "Cluster management" section would have been handy. https://anywhere.eks.amazonaws.com/docs/tasks/cluster/etcd-backup-restore/ briefly touches on pausing CAPI reconciliation, but only for `etcdadmclusters` objects.

**Comment by jiayiwang7** [comment]
https://github.com/aws/eks-anywhere/pull/3069
