### ISSUE TITLE
aws-iam-authenticator not working in baremtal

### ISSUE THREAD

**Issue by helloyeops** [aws/eks-anywhere#2885]
**What happened**:
`aws-iam-authenticator` pods are not working with error as below.
```bash
$ kubectl -n kube-system logs aws-iam-authenticator-5qtf
...
W0729 07:36:06.265507       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-07-29T07:36:06Z" level=info msg="starting mapper \"EKSConfigMap\""
time="2022-07-29T07:36:06Z" level=fatal msg="could not load/generate a certificate" error="read /var/aws-iam-authenticator/cert.pem: is a directory"
```
It seems like that the files(`kubeconfig.yaml`, `cert.pem`, `key.pem`) are normally not generated.
And I got some find related issues.

- https://github.com/aws/eks-anywhere/pull/1803
- #2749 

Is working the workflow for `aws-iam-athutenticator` in baremetal?

**What you expected to happen**:
`aws-iam-authenticator` pods' state will be running.

**How to reproduce it (as minimally and precisely as possible)**:
EKS-A deploy a new cluster with `aws-iam-authenticator`
https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-iam-auth/

**Anything else we need to know?**:
Thanks

**Environment**:
- EKS Anywhere Release: 0.10.1
- EKS Distro Release:  1.22-9

**Comment by pokearu** [comment]
@helloyeops Hi, IAM Authenticator integration is not supported for bare metal at the moment. We are working to add support in the upcoming release.

**Comment by SeungyeopShin** [comment]
Thanks for reply.

**Comment by helloyeops** [comment]
Thanks for reply.

**Comment by danbudris** [comment]
Look for this functionality in the next minor release, which will be available soon
