### ISSUE TITLE
Let EKS anywhere make use of fargate compute in your aws acount/accounts

### ISSUE THREAD

**Issue by RichardChester** [aws/eks-anywhere#2905]
**What would you like to be added**: I would like the ability to still make use of fargate compute inside my aws account while using EKS anywhere 

**Why is this needed**: It would provide a good option for hybrid cloud solutions allowing me to use my on-prem nodes for either tasks that have to be done on-prem or leverage specific existing hardware but also take advantage of the saleability of aws fargate nodes for anything that doesn't need to be on-prem.

**Comment by TerryHowe** [comment]
There is this support, but I haven't tried it https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/optional/iamauth/

**Comment by RichardChester** [comment]
Sorry I might not of been clear, in regular EKS you can use fagate like a node, run your pods on it and manage that using the regular EKS control pane. 

It looks like that link you've provided would let me use IAM to authorise a workload to interact with the fargate api in my account (which to be fair I hadn't seen but is really usefull) but not have that fargate instance (and pod's deployed to it) managed directly by EKS

**Comment by danbudris** [comment]
Hey @RichardChester, I'm going to 👍 this issue, tag it as a feature request, and keep it open in order to collect more info about other users who are interested in this functionality.
