### ISSUE TITLE
simulated cluster issue

### ISSUE THREAD

**Issue by fdaforno** [aws/eks-anywhere#291]
**What happened**:

In our dev environment, we tested the procedure to build up a new cluster. This tool is very useful compared with others (kube-admin, kubespray etc).

 My environment is based on 3 CP nodes and 4 workers.
I tested vertical and horizontal scaling by changing the number of nodes on configuration yml, and running 
`eksctl anywhere upgrade cluster` to apply the changes. This procedure works fine.

Since we have more than a hundred nodes (on-prem and on cloud), I wanted to simulate a cluster malfunction deleting a worker from the Vcenter console.
The worker disappears immediately from the inventory of k8s `kubectl get nodes` and that is fine.
I was expecting to start `eksctl anywhere upgrade cluster` again in order to recreate the evicted node but unfortunately i get this error:

`❌ Validation failed	{"validation": "upgrade preflight validations pass", "error": "validation failed with 1 errors: machine deployment is in ScalingUp phase", "remediation": ""}
Error: failed to upgrade cluster: validations failed`

I think this scenario could happen in production and the tool must be able to realign the cluster to be compliant with the cluster.yml manifest

**Environment**:
- EKS Anywhere Release: latest
- EKS Distro Release: latest

**Comment by jaxesn** [comment]
Awesome test! What should happen in that case is once you delete the node the cluster should automatically detect it being gone and create a new one to replace it. I believe that's kind of what you are seeing here in that error message. The machine deployment is already trying to "scale" back up.

Did a new node end up coming back online?

**Comment by fdaforno** [comment]
nope ! :-(
 As you can see, even if in cfg.yml the desiderata is 4 nodes, I'll continue to see only 3 workers on the cluster


![image](https://user-images.githubusercontent.com/91257884/134513235-a2f17577-6225-4cf0-8505-ce26ad6386cd.png)

`
![image](https://user-images.githubusercontent.com/91257884/134513133-5ecccc43-f5e5-493b-a35f-2337cc5c9db9.png)

`

**Comment by jaxesn** [comment]
We will do some checking on our end to see if we can replicate the issue.  If you can, the capv-manager or capi-manager logs could have some interesting clues if you want to send those over.

**Comment by mdsgabriel** [comment]
Hello @fdaforno,

This PR should fix this issue https://github.com/aws/eks-anywhere/pull/303.

Could you please share the result of the following command?

```
 kubectl --kubeconfig <clsuter name>/<cluster name>-eks-a-cluster.kubeconfig get machinehealthchecks -A
 
 For example:
 kubectl --kubeconfig prod/prod-eks-a-cluster.kubeconfig get machinehealthchecks -A
```

**Comment by fdaforno** [comment]
`

> Hello @fdaforno,
> 
> This PR should fix this issue #303.
> 
> Could you please share the result of the following command?
> 
> ```
>  kubectl --kubeconfig <clsuter name>/<cluster name>-eks-a-cluster.kubeconfig get machinehealthchecks -A
>  
>  For example:
>  kubectl --kubeconfig prod/prod-eks-a-cluster.kubeconfig get machinehealthchecks -A
> ```
mmmm I get `No resources found`

**Comment by abhay-krishna** [comment]
Hey @fdaforno! Are you still seeing this issue? Any new developments?

**Comment by TerryHowe** [comment]
Sounds like this may be resolved. Please reopen if you are still seeing this.
