### ISSUE TITLE
Install `packagecontroller` command isnt correct.

### ISSUE THREAD

**Issue by elamaran11** [aws/eks-anywhere#2975]
**What happened**: The below command to install `packagecontroller` isnt correct. So it failes to install package controller.

**What you expected to happen**: Installing `packagecontroller` on EKSA Cluster.

**How to reproduce it (as minimally and precisely as possible)**: By running the command `eksctl anywhere install packagecontroller -f $CLUSTER_NAME.yaml`

**Anything else we need to know?**: Correct command should be `eksctl anywhere install packagecontroller --kube-version 1.22`

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by TerryHowe** [comment]
This sounds like a docs issue. We'll get to this very soon.

**Comment by a-cool-train** [comment]
With the last release, the command has been changed to `eksctl anywhere install packagecontroller -f $CLUSTER_NAME.yaml` I believe the docs contain the update command but I can double check.

**Comment by TerryHowe** [comment]
Yeh, this was fixed
