### ISSUE TITLE
Cron Job should not be created when package installation is not needed

### ISSUE THREAD

**Issue by a-cool-train** [aws/eks-anywhere#3039]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by TerryHowe** [comment]
https://github.com/aws/eks-anywhere-packages/pull/440

**Comment by TerryHowe** [comment]
If we create the cronjob, then if the customer adds their secrets, it will work. The PR avoid should make it fail gracefully if there are not creds. If the user tries to install a package then the lack of a image pull secret will come up and debug from there
