### ISSUE TITLE
EKS Anywhere Cluster creation does not create a GitHub repo for Flux gitops if the repo doesnt exist.

### ISSUE THREAD

**Issue by elamaran11** [aws/eks-anywhere#3124]
Documentation on [this](https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-flux/) page says  If you specify a repo in your FluxConfig which does not exist EKS Anywhere will create it for you. 

EKS Anywhere Cluster creation does not create a GitHub repo for Flux gitops if the repo doesnt exist,

**Comment by g-gaston** [comment]
Hey @elamaran11, thanks for the heads up, let me look into it and will get back to you!

**Comment by g-gaston** [comment]
@elamaran11 could you provide your eks-a cluster yaml config?

**Comment by ndeksa** [comment]
@elamaran11 , please provide logs and cluster specs if the issue still persists in your test env.
