### ISSUE TITLE
Curated Packages and cert manager are not installed in child workload cluster.

### ISSUE THREAD

**Issue by elamaran11** [aws/eks-anywhere#3131]
Curated Packages and cert manager are not installed in child workload cluster. Geting this error.

--------------------------------------------------------------------------------------
The Amazon EKS Anywhere Curated Packages are only available to customers with the
Amazon EKS Anywhere Enterprise Subscription
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
Curated packages cannot be installed as cert-manager is not present in the cluster.
This is most likely caused by an action to install curated packages at a workload
cluster. Refer to https://anywhere.eks.amazonaws.com/docs/tasks/troubleshoot/packages/
for how to resolve this issue.
--------------------------------------------------------------------------------------

**Comment by lewisdiamond** [comment]
This is currently the expected behavior as a manual step is required for packages to be deployed on workload clusters today. This will change in the future and the message will no longer be displayed.
