### ISSUE TITLE
Support specifying `VSphereDatacenterConfig.network` by 'network segment ID'/'LogicalSwitch UUID'/'ManagedObject ID'

### ISSUE THREAD

**Issue by etungsten** [aws/eks-anywhere#3163]
**What would you like to be added**:
I would like the cluster creation pre-flight validation to account for 'network segment ID'/'LogicalSwitch UUID'/'ManagedObject ID' when checking whether an VM network is valid as opposed to only checking the network inventory path and seeing if anything returns.

https://github.com/aws/eks-anywhere/blob/3ca04dd71a63edced0e5aae19a1a9eaee456025e/pkg/executables/govc.go#L676-L698

**Why is this needed**:
I am using NSX for vSphere and my network inventory name resolves to multiple vSphere managed objects. i.e.
```
$ govc ls /SDDC-Datacenter/network/sddc-cgw-network-2
/SDDC-Datacenter/network/sddc-cgw-network-2
/SDDC-Datacenter/network/sddc-cgw-network-2

$ govc object.collect /SDDC-Datacenter/network/sddc-cgw-network-2 summary
govc: 2 objects at path "/SDDC-Datacenter/network/sddc-cgw-network-2": [OpaqueNetwork:network-o1008 DistributedVirtualPortgroup:dvportgroup-3588]
```

If I try to disambiguate the network specification by using the Port Group's network segment ID, the `eksctl-anywhere`'s preflight validation checks fails.
For example, I specified `/infra/tier-1s/cgw/segments/sddc-cgw-network-2` as the `VSphereDatacenterConfig.network` in my cluster config.
```
$ eksctl anywhere create cluster -f eksa-cluster.yaml                                   
Performing setup and validations                                 
✅ Connected to server                                                                                                             
✅ Authenticated to vSphere                                                                                                        
✅ Datacenter validated                                                                                                            
❌ Validation failed    {"validation": "vsphere Provider setup is valid", "error": "failed checking if network '/SDDC-Datacenter/ne
twork//infra/tier-1s/cgw/segments/sddc-cgw-network-2' exists: govc: /SDDC-Datacenter/network/infra/tier-1s/cgw/segments not found\n
", "remediation": ""}                                                                                                              
✅ Validate certificate for registry mirror                                                                                        
✅ Validate authentication for git provider                                                                                        
✅ Create preflight validations pass                                                                                               
Error: validations failed
```

Adding this support would match `govc`'s behavior with `vm.create`, `vm.network.add`. See govc's changes to support this https://github.com/vmware/govmomi/commit/6209be5b5c0bd5d81078fdc82eb4001f202f90e7

If we can create VMs via `govc` by specifying the network segment ID to reference the VM network, then `eksctl-anywhere` should let me do so as well.

**Comment by vivek-koppuru** [comment]
Faced this issue in the past, which we had to resolve this way: https://kb.vmware.com/s/article/86380

**Comment by vivek-koppuru** [comment]
Need to see if this is supported in capv

**Comment by lewisdiamond** [comment]
@etungsten Did the provided link resolve your issue?

**Comment by etungsten** [comment]
> @etungsten Did the provided link resolve your issue?

Yes, it did! Although I was able to work around the problem, I think there is still a difference in behavior between `govc` and `eksctl-anywhere` when specifying the VM network when creating VMs. So I'm not sure if this issue should be left open. I'll leave that decision up to someone else. Thanks!

**Comment by vivek-koppuru** [comment]
This doesn't seem to be supported in CAPV so closing for now unless other users request it as well
