### ISSUE TITLE
Allow customization of cilium CNI

### ISSUE THREAD

**Issue by jacobweinstock** [aws/eks-anywhere#3182]
**What would you like to be added**: I would like to be able to customize the Cilium CNI deployment. Specifically, I would like to be able to use Cilium's [native routing](https://docs.cilium.io/en/v1.10/concepts/networking/routing/#native-routing) functionality.

**Why is this needed**: By default cilium uses encapsulation for network traffic and that adds overhead and latency. For latency sensitive workloads this is required.

**Comment by chrisdoherty4** [comment]
Reopened as docs are outstanding.
