### ISSUE TITLE
Port patches for upstream cluster-api to `v1beta1`

### ISSUE THREAD

**Issue by g-gaston** [aws/eks-anywhere#328]
Port all the patches made to upstream cluster-api to `v1beta` CRDs and new controller’s code (build on top of latest patch of `v1.0.1`)

**Comment by mrajashree** [comment]
Ported all BR+etcd patches to v1.0.1 tag to this branch https://github.com/mrajashree/cluster-api/commits/branch-1.0.1
Going forward we'll use this fork to create patches and use those in build-tooling repo
