### ISSUE TITLE
Support for authenticated local/private registry 

### ISSUE THREAD

**Issue by ptrivedi** [aws/eks-anywhere#3349]
**What would you like to be added**:
Allow for authenticated pulls from local/private registry using credentials.  If the private registry has password-based authentication credentials set up, EKS Anywhere should allow configuration of those credentials and be able to pull from it.

**Why is this needed**:
EKS Anywhere currently supports local/private registry configuration, but only allows for unauthenticated pulls.

**Comment by Paulius0112** [comment]
Hi. Is it currently possible to pass a self-signed registry certificate in bare metal bottlerocket? We need it for pulling images from private registry, since providing certificate under `registryMirrorConfiguration.caCertContent` doesn't solve this problem.
