### ISSUE TITLE
Release tags for self-built ubuntu based images 

### ISSUE THREAD

**Issue by thecloudgarage** [aws/eks-anywhere#3355]
Since starting EKS Anywhere v.0.11 (I am running v0.11.2) automatic distribution of ubuntu releases is stopped., I have followed the procedure to the tee https://anywhere.eks.amazonaws.com/docs/reference/artifacts/#building-ubuntu-based-node-images to create the ubuntu image

Everything is setup and my ubuntu OVA template is now in my vSphere. The template is named as ubuntu-2004-kube-v1.21.14 Now for the most crucial part of tagging the template. The OS tag is applied with the value of ubuntu

MY QUESTION: How do I find out what is the value for the eksdRelease tag. I have highlighted in ???? the value that I am unable to locate anywhere on your documentation site.

govc tags.create -c eksdRelease eksdRelease:kubernetes-1-21-eks-????? (what should be ?????)

**Comment by vivek-koppuru** [comment]
We definitely need to better document this after moving to this approach which you highlighted, but a way to find the right tag in the meantime is to attempt the cluster creation/upgrade, and the validations should fail mentioning which tag it expects. Let me know if that works for you.

**Comment by thecloudgarage** [comment]
Also notice that there is a bug in the overall process to build and then deploy a cluster based on that ubuntu OVA. 

My setup
EKS Anywhere installed with v0.11.2 ( I have NO CLUE which EKSD Release was associated with this version of EKS Anywhere install)
My ubuntu OVA was built by the image-builder scripts using the EKSD latest release of 18 .. See the log snippets

Command to create the build

![image](https://user-images.githubusercontent.com/39495790/190334637-445c46d7-2be0-4b93-8ad8-a4b56897aaff.png)

Logs indicating that the image builder is using the Latest EKSD release of 18

![image](https://user-images.githubusercontent.com/39495790/190334731-2e5fbf54-0281-4aba-8ebd-2416102f67c7.png)

And then I followed the entire procedure and finally tagged my OVA template with the two tags for os and EKSD Release
govc tags.create -c os os:ubuntu
govc tags.attach os:ubuntu /IAC-SSC/vm/Templates/ubuntu-2004-kubernetes-1-21-eks-18

Now since the image builder used the latest EKSD release of 18 ., so naturally the value of the EKSD Release tag as per my understanding will be kubernetes-1-21-eks-18. Accordingly, I created this tag and applied it to my ubuntu template

govc tags.category.create -t VirtualMachine eksdRelease
govc tags.create -c eksdRelease eksdRelease:kubernetes-1-21-eks-18
govc tags.attach eksdRelease:kubernetes-1-21-eks-18 /IAC-SSC/vm/Templates/ubuntu-2004-kubernetes-1-21-eks-18

Both these tags were successfully applied on the OVA template. 

I can successfully see them in vSphere web client too. 

![image](https://user-images.githubusercontent.com/39495790/190335800-eb8d26a3-d138-47a4-a749-ecef532c3565.png)

Now I create the cluster using my template... Here is a snippet of the machine config where the template is mentioned

![image](https://user-images.githubusercontent.com/39495790/190336046-5e32d623-6e0a-4f99-b89e-b28ebb176f6f.png)

And the result is an error stating that the ❌ Validation failed    {"validation": "vsphere Provider setup is valid", "error": "template /IAC-SSC/vm/Templates/ubuntu-2004-kubernetes-1-21-eks-18 is missing tag eksdRelease:kubernetes-1-21-eks-17", "remediation": ""}

Why is the validation process checking for EKSD Release 17 (eksdRelease:kubernetes-1-21-eks-17) tag and not EKSD release tag of 18 (eksdRelease:kubernetes-1-21-eks-18), which is anyway specified on the template and as per the image builder logs., since it has used EKSD release 18 to build the image, I am assuming myself to be correct in having 18 as the EKSD release number in the tag applied

Nevertheless, I changed the tag on my template as per the error 

![image](https://user-images.githubusercontent.com/39495790/190336715-d89788a2-3232-4925-8240-9aa65c632069.png)

And then apply the new tag as per error log
govc tags.create -c eksdRelease eksdRelease:kubernetes-1-21-eks-17
![image](https://user-images.githubusercontent.com/39495790/190337085-e596a0d9-ead6-43c8-a89f-a96555b3f794.png)

And then without ANY CHANGES to my cluster file, I create the cluster and it's successfully created.

ubuntu@ubuntu-virtual-machine:~$ eksctl anywhere create cluster -f brewtest.yaml
Warning: VSphereDatacenterConfig configured in insecure mode
Performing setup and validations
Warning: VSphereDatacenterConfig configured in insecure mode
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Control plane and Workload templates validated
Provided control plane sshAuthorizedKey is not set or is empty, auto-generating new key pair...
Private key saved to brewtestnew/eks-a-id_rsa. Use 'ssh -i brewtestnew/eks-a-id_rsa <username>@<Node-IP-Address>' to login to your cluster node
✅ Vsphere Provider setup is valid
✅ Validate certificate for registry mirror
✅ Validate authentication for git provider
✅ Create preflight validations pass
Creating new bootstrap cluster
Provider specific pre-capi-install-setup on bootstrap cluster
Installing cluster-api providers on bootstrap cluster
Provider specific post-setup
Creating new workload cluster
^[^[[3~Installing networking on workload cluster
Installing storage class on cluster
Creating EKS-A namespace
Installing cluster-api providers on workload cluster
Installing EKS-A secrets on workload cluster
Installing resources on management cluster
Moving cluster management from bootstrap to workload cluster
Installing EKS-A custom components (CRD and controller) on workload cluster
Installing EKS-D components on workload cluster
Creating EKS-A CRDs instances on workload cluster
Installing GitOps Toolkit on workload cluster
GitOps field not specified, bootstrap flux skipped
Writing cluster config file
Deleting bootstrap cluster
🎉 Cluster created!
--------------------------------------------------------------------------------------
The Amazon EKS Anywhere Curated Packages are only available to customers with the
Amazon EKS Anywhere Enterprise Subscription
--------------------------------------------------------------------------------------
Installing curated packages controller on management cluster
Installing helm chart on cluster        {"chart": "eks-anywhere-packages", "version": "0.2.2-eks-a-16"}
Warning: No AWS key/license provided. Please be aware this will prevent the package controller from installing curated packages.
job.batch/eksa-auth-refresher created

Snip of the cluster nodes as seen in vsphere web console

![image](https://user-images.githubusercontent.com/39495790/190342263-db2e3a51-b894-4c26-8ad8-603ff95551ca.png)

**Comment by thecloudgarage** [comment]
Finally figured it out., and what an overwhelming experience... hopefully the attached document helps and someday this can go into official documentation 
[EKSD-Release-Tag-ubuntu-template.pdf](https://github.com/aws/eks-anywhere/files/9576874/EKSD-Release-Tag-ubuntu-template.pdf)

**Comment by thecloudgarage** [comment]
See the attached documentation in the previous comment of how to resolve this issue.

**Comment by vivek-koppuru** [comment]
Hey @thecloudgarage, you have identified an issue with our builds that we had discussed internally that we needed to fix. I totally get why this might be frustrating, so hopefully we will have something figured out on this front. Thanks for calling it out!
