### ISSUE TITLE
/tmp permission denied for image-builder user

### ISSUE THREAD

**Issue by thecloudgarage** [aws/eks-anywhere#3368]
Followed the documented procedure to the tee to create the ubuntu build via a sudo user named image-builder. However, the default documented procedure receives errors for image-builder user to write into /tmp directory

Follow the error log and the workaround applied

######################################################################################################################################
sudo adduser image-builder
sudo usermod -aG sudo image-builder
sudo visudo
Added the image-builder user to have all sudo permissions in /etc/sudoers.tmp file also

######################################################################################################################################
Logged out and logged in as image-builder user

image-builder@my-desktop:~$ sudo more /etc/sudoers
[sudo] password for image-builder:
snipped output to highlight the included permissions
root    ALL=(ALL:ALL) ALL
image-builder ALL=(ALL:ALL) ALL

######################################################################################################################################

Ran the image builder command and it errored with the message "mkdir: cannot create directory ‘/tmp/eks-image-builder-cni’: Permission denied"

image-builder build --os ubuntu --hypervisor vsphere --release-channel 1-21 --vsphere-config vsphere-connection.json

+ export PLUGINS_ASSET_BASE_URL=https://distro.eks.amazonaws.com/kubernetes-1-21/releases/18/artifacts/plugins
+ PLUGINS_ASSET_BASE_URL=https://distro.eks.amazonaws.com/kubernetes-1-21/releases/18/artifacts/plugins
++ build::eksd_releases::get_eksd_component_version cni-plugins 1-21
++ local -r component=cni-plugins
++ local -r release_branch=1-21
++ oldopt=huxB
++ set +x
+ export CNI_VERSION=v0.8.7
+ CNI_VERSION=v0.8.7
+ TMP_CNI=/tmp/eks-image-builder-cni
+ mkdir -p /tmp/eks-image-builder-cni
mkdir: cannot create directory ‘/tmp/eks-image-builder-cni’: Permission denied
make: *** [Makefile:182: setup-packer-configs-ova] Error 1
make: Leaving directory '/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder'
2022/09/16 14:12:15 Error executing image-builder for vsphere hypervisor: failed to run command: exit status 2

######################################################################################################################################

Checked the permissions and found that /tmp is owned by root:root

image-builder@my-desktop:~$ ls -al /
total 2097240
drwxr-xr-x  20 root root       4096 Jul 27 19:45 .
drwxr-xr-x  20 root root       4096 Jul 27 19:45 ..
lrwxrwxrwx   1 root root          7 Jul 27 19:44 bin -> usr/bin
drwxr-xr-x   4 root root       4096 Sep 16 06:15 boot
drwxrwxr-x   2 root root       4096 Jul 27 19:45 cdrom
drwxr-xr-x  18 root root       4180 Sep 13 06:27 dev
drwxr-xr-x 134 root root      12288 Sep 16 13:51 etc
drwxr-xr-x   5 root root       4096 Sep 16 13:37 home
lrwxrwxrwx   1 root root          7 Jul 27 19:44 lib -> usr/lib
lrwxrwxrwx   1 root root          9 Jul 27 19:44 lib32 -> usr/lib32
lrwxrwxrwx   1 root root          9 Jul 27 19:44 lib64 -> usr/lib64
lrwxrwxrwx   1 root root         10 Jul 27 19:44 libx32 -> usr/libx32
drwx------   2 root root      16384 Jul 27 19:43 lost+found
drwxr-xr-x   3 root root       4096 Jul 29 13:54 media
drwxr-xr-x   2 root root       4096 Aug  1  2020 mnt
drwxr-xr-x   3 root root       4096 Jul 29 14:47 opt
dr-xr-xr-x 388 root root          0 Jul 29 14:13 proc
drwx------   6 root root       4096 Jul 29 19:11 root
drwxr-xr-x  39 root root       1220 Sep 16 13:40 run
lrwxrwxrwx   1 root root          8 Jul 27 19:44 sbin -> usr/sbin
drwxr-xr-x  12 root root       4096 Sep 16 13:45 snap
drwxr-xr-x   2 root root       4096 Aug  1  2020 srv
-rw-------   1 root root 2147483648 Jul 27 19:43 swapfile
dr-xr-xr-x  13 root root          0 Jul 29 14:13 sys
drwxr-xr-x  26 root root       4096 Sep 16 13:56 tmp
drwxr-xr-x  14 root root       4096 Aug  1  2020 usr
drwxr-xr-x  14 root root       4096 Aug  1  2020 var

######################################################################################################################################

Changed the ownership of /tmp to image-builder user

image-builder@my-desktop:~$ sudo chown -R image-builder /tmp

image-builder@my-desktop:~$ ls -al /
total 2097240
drwxr-xr-x  20 root          root       4096 Jul 27 19:45 .
drwxr-xr-x  20 root          root       4096 Jul 27 19:45 ..
lrwxrwxrwx   1 root          root          7 Jul 27 19:44 bin -> usr/bin
drwxr-xr-x   4 root          root       4096 Sep 16 06:15 boot
drwxrwxr-x   2 root          root       4096 Jul 27 19:45 cdrom
drwxr-xr-x  18 root          root       4180 Sep 13 06:27 dev
drwxr-xr-x 134 root          root      12288 Sep 16 13:51 etc
drwxr-xr-x   5 root          root       4096 Sep 16 13:37 home
lrwxrwxrwx   1 root          root          7 Jul 27 19:44 lib -> usr/lib
lrwxrwxrwx   1 root          root          9 Jul 27 19:44 lib32 -> usr/lib32
lrwxrwxrwx   1 root          root          9 Jul 27 19:44 lib64 -> usr/lib64
lrwxrwxrwx   1 root          root         10 Jul 27 19:44 libx32 -> usr/libx32
drwx------   2 root          root      16384 Jul 27 19:43 lost+found
drwxr-xr-x   3 root          root       4096 Jul 29 13:54 media
drwxr-xr-x   2 root          root       4096 Aug  1  2020 mnt
drwxr-xr-x   3 root          root       4096 Jul 29 14:47 opt
dr-xr-xr-x 388 root          root          0 Jul 29 14:13 proc
drwx------   6 root          root       4096 Jul 29 19:11 root
drwxr-xr-x  39 root          root       1220 Sep 16 13:40 run
lrwxrwxrwx   1 root          root          8 Jul 27 19:44 sbin -> usr/sbin
drwxr-xr-x  12 root          root       4096 Sep 16 13:45 snap
drwxr-xr-x   2 root          root       4096 Aug  1  2020 srv
-rw-------   1 root          root 2147483648 Jul 27 19:43 swapfile
dr-xr-xr-x  13 root          root          0 Jul 29 14:13 sys
drwxr-xr-x  26 image-builder root       4096 Sep 16 13:56 tmp
drwxr-xr-x  14 root          root       4096 Aug  1  2020 usr
drwxr-xr-x  14 root          root       4096 Aug  1  2020 var

######################################################################################################################################

Re-ran the image builder command after removing the stale directory

rm -rf /home/image-builder/eks-anywhere-build-tooling/
image-builder build --os ubuntu --hypervisor vsphere --release-channel 1-21 --vsphere-config vsphere-connection.json

Final snip after the build was successful with ONE CHANGE., i.e. change the ownership of /tmp to image-builder user

==> vsphere (shell-local): Running local shell script: /tmp/packer-shell3948951980
Build 'vsphere' finished after 24 minutes 53 seconds.

==> Wait completed after 24 minutes 53 seconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere: ubuntu-2004-kube-v1.21.14
--> vsphere: ubuntu-2004-kube-v1.21.14
--> vsphere: ubuntu-2004-kube-v1.21.14
--> vsphere: ubuntu-2004-kube-v1.21.14
--> vsphere: ubuntu-2004-kube-v1.21.14
make[1]: Leaving directory '/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi'
make: Leaving directory '/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder'
2022/09/16 15:02:29 Image Build Successful
 Please find the output artifact at /home/image-builder/ubuntu.ova
2022/09/16 15:02:29 Moving artifacts from build directory to current working directory
2022/09/16 15:02:29 Cleaning up cache build files
2022/09/16 15:02:30 Build Successful. Output artifacts located at current working directory

**Comment by vivek-koppuru** [comment]
Closing this issue with a tracking issue opened: https://github.com/aws/eks-anywhere/issues/3383

Feel free to reopen this or comment on that issue for further comments.
