### ISSUE TITLE
Generate Bottlerocket default network interface configuration

### ISSUE THREAD

**Issue by zmrow** [aws/eks-anywhere#3411]
In [this line](https://github.com/aws/eks-anywhere/blob/8e9a55b1392fb9cfabb20a57bf80d6129666a6f7/pkg/api/v1alpha1/tinkerbelltemplateconfig_defaults.go#L18) of Tinkerbell template configuration, the default network interface is set to `eno1` for all users of Bottlerocket on metal.  Considering the vast amount of hardware in the wild, this default is going to be incorrect a decent percentage of the time, leaving a user immediately in a broken state when trying to spin up a new cluster.

As of [this PR](https://github.com/bottlerocket-os/bottlerocket/pull/2622), Bottlerocket is able to configure network interfaces via MAC address.  It would be very helpful to users if a working default network configuration could be generated from the MAC address supplied in the hardware CSV manifest.

**Comment by zmrow** [comment]
Commenting to keep this alive

**Comment by jacobweinstock** [comment]
PR opened for this. https://github.com/aws/eks-anywhere-build-tooling/pull/2185
