### ISSUE TITLE
Control Plane Node missing no schedule taint

### ISSUE THREAD

**Issue by junshun** [aws/eks-anywhere#3420]
**What happened**:
Created cluster with provided dev-cluster.yaml (Default generated by CLI with only change of kubernetesVersion from 1.23 -> 1.22). After cluster creation checking the taints on the nodes 
```
/local/home/junshun/DockerCluster kubectl get nodes -o custom-columns=NAME:.metadata.name,TAINTS:.spec.taints           
NAME                                TAINTS
dev-cluster-md-0-6dd8979879-f5d6j   <none>
dev-cluster-ml9r9                   <none>
```
Built eks-a binary out of main as of commit (5efbd99bfc2cfa8dcdeeb40172bd12b33ad65754)

**What you expected to happen**:
With 11.3 release release, control plane nodes are tainted with no schedule as expected with same cluster spec.
```
/local/home/junshun/DockerCluster kubectl get nodes -o custom-columns=NAME:.metadata.name,TAINTS:.spec.taints
NAME                                TAINTS
dev-cluster-757w5                   [map[effect:NoSchedule key:node-role.kubernetes.io/master]]
dev-cluster-md-0-7dbf5658dc-cw4cw   <none>
```
**How to reproduce it (as minimally and precisely as possible)**:
Build main and create cluster with dev-cluster.yaml
**Anything else we need to know?**:
Issue first seen with vsphere and reproduced with docker.

[dev-cluster.yaml.txt](https://github.com/aws/eks-anywhere/files/9625861/dev-cluster.yaml.txt)

Main branch build create cluster log with v6
[main-dev-cluster.log](https://github.com/aws/eks-anywhere/files/9625866/main-dev-cluster.log)

11.3 release create cluster log with v6
[11-3-dev-cluster.log](https://github.com/aws/eks-anywhere/files/9625867/11-3-dev-cluster.log)

**Comment by chrisdoherty4** [comment]
@d8660091 Could this be related to the work you're doing for single node clusters?

**Comment by d8660091** [comment]
Yes, I think it has some relations. I'm investigating it with Steven

**Comment by drewvanstone** [comment]
@d8660091 has this been resolved?

**Comment by d8660091** [comment]
I think so, I'll close this issue after double checking with junshun
