### ISSUE TITLE
Documentation unclear about vSphere resources

### ISSUE THREAD

**Issue by echel0n** [aws/eks-anywhere#3444]
Could someone please clear up what the documentation means by "The main differences are that you must have a new cluster name and cannot use the same vSphere resources.", what specifically is it referring to when it says "vSphere resources", this is for when creating a management cluster and workload clusters managed by the other cluster.

Thanks!

**Comment by jiayiwang7** [comment]
Good suggestion! Agree the "vSphere resources" are confusing. Updated the doc to be more explicit.

**Comment by echel0n** [comment]
Thanks, just to clarify, the same resourcePool is ok ?

**Comment by jiayiwang7** [comment]
> resourcePool

Yes, management and workload clusters can use the same resourcePool.
