### ISSUE TITLE
Option to choose cilium image registry?

### ISSUE THREAD

**Issue by vincentmli** [aws/eks-anywhere#3506]
**What would you like to be added**:

eks-a is pulling cilium image from `"public.ecr.aws/isovalent"` registry where the cilium version is maintained by isovalent, in  https://github.com/cilium/cilium/issues/21486#issuecomment-1262641784, it is explained why isovalent does not build most recent Cilium open source community version and publish in `"public.ecr.aws/isovalent"`, that is reasonable. from eks-a, could we give early eks-a and cilium adopters/developers option to explore Cilium open source community version with eks-a? for example, can we make  `ciliumContainerRegistry := "public.ecr.aws/isovalent"` configurable in https://github.com/aws/eks-anywhere/blob/main/release/pkg/bundles/cilium.go#L39-L87, to give  early esk-a/cilium users an option to  pull cilium image from `https://github.com/cilium/cilium/releases` ? 

**Why is this needed**:

make cilium image registry configurable to pull image from `https://github.com/cilium/cilium/releases`

**Comment by jiayiwang7** [comment]
Thanks for the feedback. We will use this issue to track the request. Currently supporting upstream / custom cilium is not on our roadmap.

**Comment by vincentmli** [comment]
@jiayiwang7 that is fine. I am curious, for my own test use and hack, if I simply change to `ciliumContainerRegistry := "https://github.com/cilium/cilium/releases"` and build eks-a myself, would that work?

**Comment by jiayiwang7** [comment]
You can certainly try. We generate cilium manifests that will be applied to the cluster from `helm generate` which uses specific cilium versions and build by EKS-A. You might run into issues if using upstream.
