### ISSUE TITLE
Clarification on vSphere DRS and HA for EKS-A

### ISSUE THREAD

**Issue by echel0n** [aws/eks-anywhere#3586]
Does EKS-A work with a vSphere cluster running DRS and HA services enabled and is it recommended or preferred enabled/disabled ?

I am asking as I could not find anything in the EKS-A documentation about it nor could I find any other people talking on it that use EKS-A and just wanted to know if there is any more information surrounding it, I currently have both disabled right now.

Thanks!

**Comment by vincentni** [comment]
Thanks for reaching out to us! It seems requires vMotion which hasn't been tested yet. So the current recommendation is to disable both.

**Comment by echel0n** [comment]
@vincentni thanks for the recommendation on that, I had run both HA and DRS and found pods getting stuck in creation due to PVC's already being in use, is it also recommend to shutdown the EKS VM before moving it over to a different vSphere node ?

**Comment by vincentni** [comment]
We haven't tested EKS-A with a vSphere cluster running DRS and HA, so don't expect users to do so. Unfortunately, I can't give any recommendations on unsupported use cases, but what you plan to do sounds reasonable.

**Comment by echel0n** [comment]
@vincentni I bring this up cause when performing a cluster update, it places the new VM in vSphere randomly it would seem, this can cause resource issues if to many of the VMs end up on the same vSphere node, is there a way to prevent this, like anti-affinity rules or ?

**Comment by abhinavmpandey08** [comment]
Hi @echel0n! Thanks for reaching out! 
EKS-A can utilize vSphere's DRS and HA services.
You can use a [resourcePool](https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/vsphere/#resourcepool-required) that spans across multiple ESXI hosts to ensure the VMs are distributed evenly among your ESXI hosts.

**Comment by echel0n** [comment]
Well I tried using DRS again and not sure if its related or not to https://github.com/aws/eks-anywhere/issues/896 but I started having volume attachment issues on upgrades and randomly when pods restarted after an upgrade, I've turned off DRS and manually moved VMs around for now.
