### ISSUE TITLE
Allow eksctl to generate TinkerbellTemplateConfig

### ISSUE THREAD

**Issue by Cajga** [aws/eks-anywhere#3588]
**What would you like to be added**: It would be really helpful if we could generate a TinkerbellTemplateConfig and be able to edit that. Or to have an option for `eksctl anywhere generate clusterconfig $CLUSTER_NAME --provider tinkerbell` to include TinkerbellTemplateConfig into the generated clusterconfig yaml.

**Why is this needed**: As discussed in multiple bottlerocket os issues ([first](https://github.com/bottlerocket-os/bottlerocket/issues/2469), [second](https://github.com/bottlerocket-os/bottlerocket/issues/2293) ) it is extremely likely that eno1 will not be the network interface name of the metal server but this is hard-coded into the current template. As such, we have to include TinkerbellTemplateConfig(s) in most of the cases.

However, the [documentation](https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/baremetal/#advanced-bare-metal-cluster-configuration) includes an old example. The images listed there are outdated compared to what is really generated at cluster create.
In documentation the stream image action is using:
```https://anywhere-assets.eks.amazonaws.com/releases/bundles/11/artifacts/raw/1-22/bottlerocket-v1.22.10-eks-d-1-22-8-eks-a-11-amd64.img.gz```
But latest version of eks-anywhere is using:
```https://anywhere-assets.eks.amazonaws.com/releases/bundles/18/artifacts/raw/1-23/bottlerocket-v1.23.9-eks-d-1-23-5-eks-a-18-amd64.img.gz```

As a workaround, I've created a cluster and copied the template from $CLUSTER_NAME/generated/$CLUSTER_NAME-eks-a-cluster.yaml and edited that, then recreated the cluster with the proper template. But this is very inconvenient.

**Comment by vincentni** [comment]
Thank you for reaching out to us! Forward your request to our internal team for discussions.

**Comment by gwesterfieldjr** [comment]
@Cajga we can do this. I'm adding it to our backlog.

**Comment by Cajga** [comment]
Although the default is more flexible now, this would be still very useful to have.
We are planning to use bonding for networking (we are on baremetal) as well as dedicated network catds for storage. As such we have to modify the templates.

**Comment by Cajga** [comment]
Just reiterating to keep this issue live: for bare metal users this would be a huge help as we need to use TinkerbellTemplateConfig in many real life use cases (dedicated network card for storage, bonding, use different interface for network than the one which was determined etc.)
