### ISSUE TITLE
Equinix Metal Provider support

### ISSUE THREAD

**Issue by displague** [aws/eks-anywhere#3598]
**What would you like to be added**:

Support for CAPP (Equinix Metal) would allow for the use of Equinix Metal's hosted images (such as Ubuntu) and network configuration helpers specific to the Equinix Metal environment.

**Why is this needed**:

In a recent workshop, https://github.com/equinix-labs/terraform-equinix-metal-eks-anywhere/#eks-a-baremetal-on-equinix-metal (CAPT + bottlerocket) was deployed hundreds of times. Many of these deployments were redeployments due to snags in provisioning, many of which could be traced back to (https://github.com/bottlerocket-os/bottlerocket/issues/2469). 

Supporting CAPP would provide a smoother experience in Equinix Metal which would reduce the overhead of provisioning a new environment. This approach would leverage existing well-supported projects. 

Questions:
* Would the EKS-A Admin node become optional? (replaced by wherever `eksctl` is run)

**Comment by vincentni** [comment]
Thanks for reaching out to us! I'll forward the request to our internal team.

**Comment by drewvanstone** [comment]
Thank you for the feature request. We'll use thumbs-up to track this issue and prioritize it accordingly.
