### ISSUE TITLE
Add validations to cluster name and other resource names

### ISSUE THREAD

**Issue by vivek-koppuru** [aws/eks-anywhere#361]
**What happened**:

As seen in https://github.com/aws/eks-anywhere/issues/331#issuecomment-930061424, specifying a period character in the cluster name resulted in the resources trimming everything after. 

If cluster name is `eks-a-1.20`, the underlying VM hostname shows up as `eks-a-1`.

**What you expected to happen**:

This should instead throw an error when validating for the cluster name. 

**How to reproduce it (as minimally and precisely as possible)**:

Include unsupported characters (such as periods) in cluster name

**Anything else we need to know?**:

Check what other validations need to be made

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by gwesterfieldjr** [comment]
@vivek-koppuru Hello! I'm gonna pick this one up. I have reproduced the issue. Looks like we validate cluster name during generate command but not during create so if the user provides invalid cluster name in the yaml directly is when this causes an issue. I'll ping you on PR when its ready!

**Comment by vivek-koppuru** [comment]
@gwesterfieldjr That's awesome, thanks for picking this up!
