### ISSUE TITLE
Set hostname on Bottlerocket nodes during bootstrap process

### ISSUE THREAD

**Issue by vignesh-goutham** [aws/eks-anywhere#3629]
**What would you like to be added**:
Set hostname on Bottlerocket nodes during kubeadm bootstrap process. Bottlerocket now as an api that exposes setting to set the hostname. 

**Why is this needed**:
Hostname of a node is usually set during kubeadm bootstrap process as a pre/post kubeadm command. This is used to identify nodes with ease. This is also the name that gets populated when running `kubectl get nodes`. In addition to this, the node name also gets used for sending DHCP requests.

**Comment by ahreehong** [comment]
https://github.com/aws/eks-anywhere-build-tooling/pull/1858
