### ISSUE TITLE
When executing `download images` with --include-packages `no basic auth credentials` error occurs

### ISSUE THREAD

**Issue by wongni** [aws/eks-anywhere#3836]
**What happened**:

```
2022-10-25T15:57:09.198Z	V6	Executing command	{"cmd": "/usr/bin/docker pull 783794618700.dkr.ecr.us-west-2.amazonaws.com/harbor/harbor-log@sha256:68b259ff53a56280004ee40b8f4d466b10b288564de1bd53e0e3711207462e5b"}
2022-10-25T15:57:09.231Z	V9	docker	{"stderr": "Error response from daemon: Get \"https://783794618700.dkr.ecr.us-west-2.amazonaws.com/v2/adot/aws-observability/aws-otel-collector/manifests/sha256:34b9ab82bda4996858e16baa2878dcd8ff5eec9365ca183292d4601d7a97260b\": no basic auth credentials\n"}
```

```
eksa-packages                       eks-anywhere-packages-65b47d55c5-nhqlq                            0/1     ImagePullBackOff   0             75m
eksa-packages                       eksa-auth-refresher-nn9kd                                         0/1     ImagePullBackOff   0             75m
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

eksctl anywhere download images --output artifacts.tar --include-packages

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.12.0
- EKS Distro Release:

**Comment by a-cool-train** [comment]
Can you please authenticate through this mechanism: https://anywhere.eks.amazonaws.com/docs/tasks/packages/

**Comment by wongni** [comment]
> Can you please authenticate through this mechanism: https://anywhere.eks.amazonaws.com/docs/tasks/packages/

@a-cool-train I followed the steps in the link but I got this error. 

```
$ export AWS_ACCESS_KEY_ID=“REDACTED"
$ export AWS_SECRET_ACCESS_KEY=“REDACTED"
$ aws sts get-caller-identity
{
    "UserId": "AIDAUTO4IU75CBCHA77SM",
    "Account": "316678907898",
    "Arn": "arn:aws:iam::316678907898:user/ecr-reader"
}
$ aws ecr get-login-password |docker login --username AWS --password-stdin 783794618700.dkr.ecr.us-west-2.amazonaws.com
Error response from daemon: login attempt to https://783794618700.dkr.ecr.us-west-2.amazonaws.com/v2/ failed with status: 400 Bad Request
```

**Comment by wongni** [comment]
> > Can you please authenticate through this mechanism: https://anywhere.eks.amazonaws.com/docs/tasks/packages/
> 
> @a-cool-train I followed the steps in the link but I got this error.
> 
> ```
> $ export AWS_ACCESS_KEY_ID=“REDACTED"
> $ export AWS_SECRET_ACCESS_KEY=“REDACTED"
> $ aws sts get-caller-identity
> {
>     "UserId": "AIDAUTO4IU75CBCHA77SM",
>     "Account": "316678907898",
>     "Arn": "arn:aws:iam::316678907898:user/ecr-reader"
> }
> $ aws ecr get-login-password |docker login --username AWS --password-stdin 783794618700.dkr.ecr.us-west-2.amazonaws.com
> Error response from daemon: login attempt to https://783794618700.dkr.ecr.us-west-2.amazonaws.com/v2/ failed with status: 400 Bad Request
> ```

Self answer: I found that I had to set the region to `us-west-2` using `aws configure`. I think adding this step to the documentation would be great.

**Comment by wongni** [comment]
@a-cool-train 
I am getting this error
```
Error: loading docker image mover source: image processor worker failed, rest of jobs were aborted: Error response from daemon: pull access denied for 783794618700.dkr.ecr.us-west-2.amazonaws.com/harbor/harbor-db, repository does not exist or may require 'docker login': denied: User: arn:aws:iam::316678907898:user/ecr-reader is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:us-west-2:783794618700:repository/harbor/harbor-db because no resource-based policy allows the ecr:BatchGetImage action
```

**Comment by TerryHowe** [comment]
Has your account been added?

**Comment by TerryHowe** [comment]
Reopen if this is still an issue, but at the time, you didn't have access.
