### ISSUE TITLE
Customize Ubuntu OVA workflow is broken after Self creation of Ubuntu images

### ISSUE THREAD

**Issue by thecloudgarage** [aws/eks-anywhere#3840]
I can confirm the following:

Step-1
Created the Ubuntu image using the image-builder process and tagged it appropriately

Step-2 Result
Created a cluster using the above self created ubuntu image and cluster was created successfully. Deployed test workloads and everything works fine

Step-2 
Used the above image as a vm template and followed the procedure given here https://anywhere.eks.amazonaws.com/docs/reference/vsphere/customize-ovas/ to the tee and multiple times also ensuring that the machine-id reset steps are also followed. Ensured that the new custom OVA is also tagged appropriately.

Step-2 results
All validation steps are reporting success during the cluster creation log.
Cluster fails to come up, 3 etcd nodes are created and the cluster creation process is hung at the condition waiting for the etcd. 

Log where the cluster creation process is hung. Verbosity used "6"
2022-10-26T18:04:50.633+0800    V6      Executing command       {"cmd": "/usr/bin/docker exec -i eksa_1666778512116048323 kubectl wait --timeout 3600.00s --for=condition=ManagedEtcdReady clusters.cluster.x-k8s.io/argotestnew --kubeconfig argotestnew/generated/argotestnew.kind.kubeconfig -n eksa-system"}

Web console log from one of the etcd nodes that reports failure
![image](https://user-images.githubusercontent.com/39495790/198001729-7911a0dc-9abc-484c-bd20-5d9dd18938a7.png)

After performing SSH into the same etcd node, I could see the failure indicating the script run issues

root@cloud-vm:/var/lib/cloud/data# more result.json
{
 "v1": {
  "datasource": "DataSourceVMware",
  "errors": [
   "('scripts-user', RuntimeError('Runparts: 1 failures (runcmd) in 1 attempted commands'))"
  ]
 }
}

root@cloud-vm:/var/lib/cloud/data# more status.json
{
 "v1": {
  "datasource": "DataSourceVMware",
  "init": {
   "errors": [],
   "finished": 1666778758.730749,
   "start": 1666778756.8893015
  },
  "init-local": {
   "errors": [],
   "finished": 1666778755.2330544,
   "start": 1666778754.740572
  },
  "modules-config": {
   "errors": [],
   "finished": 1666778760.2267852,
   "start": 1666778759.7797961
  },
  "modules-final": {
   "errors": [
    "('scripts-user', RuntimeError('Runparts: 1 failures (runcmd) in 1 attempted commands'))"
   ],
   "finished": 1666778763.3037732,
   "start": 1666778760.6180775
  },
  "modules-init": {
   "errors": [],
   "finished": null,
   "start": null
  },
  "stage": null
 }
}

Checked the logs, etcd processes are failing due to user scripts failure. All 3 etcd machines have received their DHCP IP addresses, and they are all different. If I SSH into the etcd machines, I can ping the vSphere API end point and the other etcd peers without any problem.

And this is the SYSLOG excerpt from the etcd machine. The below log appears in a recurring pattern with the eventual 3600 seconds elapsed and cluster creation fails as ETCD nodes are not created successfully.

Oct 26 10:06:39 cloud-vm systemd[1]: Starting etcd...
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=https:
//172.24.167.100:2379
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_CERT_FILE=/etc/etcd/pki/serv
er.crt
Oct 26 10:06:39 cloud-vm etcd[1084]: [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' f
lag instead
Oct 26 10:06:39 cloud-vm etcd[1084]: [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' f
lag instead
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_CIPHER_SUITES=TLS_ECDHE_RSA_
WITH_AES_128_GCM_SHA256
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_CLIENT_CERT_AUTH=true
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=
https://172.24.167.100:2380
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_INITIAL_CLUSTER=cloud-vm=htt
ps://172.24.167.99:2380,cloud-vm=https://172.24.167.100:2380
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existi
ng
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_KEY_FILE=/etc/etcd/pki/serve
r.key
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=https://1
72.24.167.100:2379,https://127.0.0.1:2379
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=https://172
.24.167.100:2380
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_NAME=cloud-vm
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_PEER_CERT_FILE=/etc/etcd/pki
/peer.crt
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_PEER_CLIENT_CERT_AUTH=true
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_PEER_KEY_FILE=/etc/etcd/pki/
peer.key
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_PEER_TRUSTED_CA_FILE=/etc/et
cd/pki/ca.crt
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_STRICT_RECONFIG_CHECK=true
Oct 26 10:06:39 cloud-vm etcd[1084]: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/etcd/pk
i/ca.crt
Oct 26 10:06:39 cloud-vm etcd[1084]: etcd Version: 3.4.18
Oct 26 10:06:39 cloud-vm etcd[1084]: Git SHA: 14dd1a3ac
Oct 26 10:06:39 cloud-vm etcd[1084]: Go Version: go1.15.15
Oct 26 10:06:39 cloud-vm etcd[1084]: Go OS/Arch: linux/amd64
Oct 26 10:06:39 cloud-vm etcd[1084]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Oct 26 10:06:39 cloud-vm etcd[1084]: the server is already initialized as member before, starting as etcd membe
r...
Oct 26 10:06:39 cloud-vm etcd[1084]: peerTLS: cert = /etc/etcd/pki/peer.crt, key = /etc/etcd/pki/peer.key, trus
ted-ca = /etc/etcd/pki/ca.crt, client-cert-auth = true, crl-file =
Oct 26 10:06:39 cloud-vm etcd[1084]: name = cloud-vm
Oct 26 10:06:39 cloud-vm etcd[1084]: data dir = /var/lib/etcd
Oct 26 10:06:39 cloud-vm etcd[1084]: member dir = /var/lib/etcd/member
Oct 26 10:06:39 cloud-vm etcd[1084]: heartbeat = 100ms
Oct 26 10:06:39 cloud-vm etcd[1084]: election = 1000ms
Oct 26 10:06:39 cloud-vm etcd[1084]: snapshot count = 100000
Oct 26 10:06:39 cloud-vm etcd[1084]: advertise client URLs = https://172.24.167.100:2379
Oct 26 10:06:39 cloud-vm etcd[1084]: cannot fetch cluster info from peer urls: could not retrieve cluster infor
mation from the given URLs
Oct 26 10:06:39 cloud-vm systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Oct 26 10:06:39 cloud-vm systemd[1]: etcd.service: Failed with result 'exit-code'.
Oct 26 10:06:39 cloud-vm systemd[1]: Failed to start etcd.
Oct 26 10:06:45 cloud-vm systemd[1]: etcd.service: Scheduled restart job, restart counter is at 8.
Oct 26 10:06:45 cloud-vm systemd[1]: Stopped etcd.
Oct 26 10:06:45 cloud-vm systemd[1]: Starting etcd...

Something is broken somewhere due to which etcd cluster is not able to establish peer connectivity and the etcd cluster readiness is failing.

Please investigate at your end, by customizing a sample ubuntu image.

thanks,

Ambar

**Comment by TerryHowe** [comment]
Someone else will look at this, but it might help if you paste in your cluster config yaml

**Comment by thecloudgarage** [comment]
No problem with that... the same config works perfect with a successful cluster creation with the Template name refering to the self-built ubuntu image before any customization.

ubuntu@eksa-admin:~$ more argotestnew-eks-a-cluster.yaml
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
 name: argotestnew
spec:
  clusterNetwork:
    cni: cilium
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 2
    endpoint:
      host: "172.24.165.15"
    machineGroupRef:
      kind: VSphereMachineConfig
      name: argotestnew-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: argotestnew-dcconfig
  externalEtcdConfiguration:
    count: 3
    machineGroupRef:
      kind: VSphereMachineConfig
      name: argotestnew-etcd
  kubernetesVersion: "1.21"
  managementCluster:
    name: argotestnew
  workerNodeGroupConfigurations:
  - count: 2
    machineGroupRef:
      kind: VSphereMachineConfig
      name: argotestnew-wk
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: argotestnew-dcconfig
spec:
  datacenter: "IAC-SSC"
  insecure: true
  network: "iac_pg"
  server: "vc.iac.ssc"
  thumbprint: "F7:A3:92:55:2D:73:B1:BA:1C:77:A8:AC:A3:AD:F3:62:8A:E0:53:CE"

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: argotestnew-cp
spec:
  datastore: "CommonDS"
  diskGiB: 25
  folder: "eks-anywhere"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  template: "ubuntu-2004-kube-v1.21.14-custom"
  resourcePool: "Test"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: argotestnew-wk
spec:
  datastore: "CommonDS"
  diskGiB: 25
  folder: "eks-anywhere"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  template: "ubuntu-2004-kube-v1.21.14-custom"
  resourcePool: "Test"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: argotestnew-etcd
spec:
  datastore: "CommonDS"
  diskGiB: 25
  folder: "eks-anywhere"
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  template: "ubuntu-2004-kube-v1.21.14-custom"
  resourcePool: "Test"
  users:
  - name: capv
    sshAuthorizedKeys:
    - ""

---

**Comment by thecloudgarage** [comment]
Additional log from the etcd machine from /var/log/cloud-init-output.log

[2022-10-26 10:06:01] [certificates] Generated etcdctl-etcd-client certificate and key.
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="creating a new client certificate for the api
server calling etcd"
[2022-10-26 10:06:01] [certificates] Generated apiserver-etcd-client certificate and key.
[2022-10-26 10:06:01] [certificates] valid certificates and keys now exist in "/etc/etcd/pki"
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="[membership] Checking if this member was adde
d"
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="[membership] Generating etcd client with endp
oints [https://172.24.167.99:2379]"
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="[membership] Member was not added"
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="Removing existing data dir \"/var/lib/etcd\""
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="[membership] Adding member"
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="[membership] Checking if member was started"
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="[membership] Member was not started"
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="[membership] Removing existing data dir \"/va
r/lib/etcd\""
[2022-10-26 10:06:01] time="2022-10-26T10:06:01Z" level=info msg="[install] extracting etcd archive /var/cache/
etcdadm/etcd/v3.4.18/etcd-v3.4.18-linux-amd64.tar.gz to /tmp/etcd056049375\n"
[2022-10-26 10:06:02] time="2022-10-26T10:06:02Z" level=info msg="[install] verifying etcd 3.4.18 is installed
in /usr/bin\n"
[2022-10-26 10:06:03] time="2022-10-26T10:06:03Z" level=fatal msg="[start] error starting etcd: failed to start
 service: exit status 1"
[2022-10-26 10:06:03] Cloud-init v. 22.2-0ubuntu1~20.04.3 running 'modules:final' at Wed, 26 Oct 2022 10:06:00
+0000. Up 8.97 seconds.
[2022-10-26 10:06:03] 2022-10-26 10:06:03,217 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user
(scripts in /var/lib/cloud/instance/scripts)
[2022-10-26 10:06:03] 2022-10-26 10:06:03,218 - util.py[WARNING]: Running module scripts-user (<module 'cloudin
it.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
[2022-10-26 10:06:03] Cloud-init v. 22.2-0ubuntu1~20.04.3 finished at Wed, 26 Oct 2022 10:06:03 +0000. Datasour
ce DataSourceVMware.  Up 11.65 seconds

**Comment by vignesh-goutham** [comment]
Thank for sharing all the details needed for debugging. Did at least one of the three etcd come up? From the logs you shared it looks like it failed at trying to start etcd. Can you check what `systemctl status etcd` says? Also `journalctl -u etcd` might have more information on why it failed to come up.

**Comment by thecloudgarage** [comment]
I guess the problem could be the documentation prescribes using a metadata.yaml file that sets the instance-id and local-hostname as cloud-vm. I can see that all the 3 etcd nodes bear the same DNS name of cloud-vm after being created. 

I can also see that all tge etcd nodes try to use the same value for the environmental variable ETCD_NAME=cloud-vm. Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_NAME=cloud-vm. 

**Can that be causing a conflict?** If yes, how do we reset the DNS name to be dynamic once the OVA is customized

Please check the below logs from the journalctl -u etcd command. This pattern of stopping etcd and restarting and failing goes on forever in the log.

Oct 27 02:11:21 cloud-vm systemd[1]: Starting etcd...
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=https://172.24.167.124:2379
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_CERT_FILE=/etc/etcd/pki/server.crt
Oct 27 02:11:21 cloud-vm etcd[1941]: [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
Oct 27 02:11:21 cloud-vm etcd[1941]: [WARNING] Deprecated '--logger=capnslog' flag is set; use '--logger=zap' flag instead
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_CIPHER_SUITES=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_CLIENT_CERT_AUTH=true
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=https://172.24.167.124:2380
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_INITIAL_CLUSTER=cloud-vm=https://172.24.167.116:2380,cloud-vm=https://172>
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_KEY_FILE=/etc/etcd/pki/server.key
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=https://172.24.167.124:2379,https://127.0.0.1:2379
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=https://172.24.167.124:2380
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_NAME=cloud-vm
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_PEER_CERT_FILE=/etc/etcd/pki/peer.crt
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_PEER_CLIENT_CERT_AUTH=true
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_PEER_KEY_FILE=/etc/etcd/pki/peer.key
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd/pki/ca.crt
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_STRICT_RECONFIG_CHECK=true
Oct 27 02:11:21 cloud-vm etcd[1941]: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/etcd/pki/ca.crt
Oct 27 02:11:21 cloud-vm etcd[1941]: etcd Version: 3.4.18
Oct 27 02:11:21 cloud-vm etcd[1941]: Git SHA: 14dd1a3ac
Oct 27 02:11:21 cloud-vm etcd[1941]: Go Version: go1.15.15
Oct 27 02:11:21 cloud-vm etcd[1941]: Go OS/Arch: linux/amd64
Oct 27 02:11:21 cloud-vm etcd[1941]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Oct 27 02:11:21 cloud-vm etcd[1941]: the server is already initialized as member before, starting as etcd member...
Oct 27 02:11:21 cloud-vm etcd[1941]: peerTLS: cert = /etc/etcd/pki/peer.crt, key = /etc/etcd/pki/peer.key, trusted-ca = /etc/etcd/pki/ca.crt, client-cert-au>
Oct 27 02:11:21 cloud-vm etcd[1941]: name = cloud-vm
Oct 27 02:11:21 cloud-vm etcd[1941]: data dir = /var/lib/etcd
Oct 27 02:11:21 cloud-vm etcd[1941]: member dir = /var/lib/etcd/member
Oct 27 02:11:21 cloud-vm etcd[1941]: heartbeat = 100ms
Oct 27 02:11:21 cloud-vm etcd[1941]: election = 1000ms
Oct 27 02:11:21 cloud-vm etcd[1941]: snapshot count = 100000
Oct 27 02:11:21 cloud-vm etcd[1941]: advertise client URLs = https://172.24.167.124:2379
Oct 27 02:11:21 cloud-vm etcd[1941]: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs
Oct 27 02:11:21 cloud-vm systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Oct 27 02:11:21 cloud-vm systemd[1]: etcd.service: Failed with result 'exit-code'.
Oct 27 02:11:21 cloud-vm systemd[1]: Failed to start etcd.
Oct 27 02:11:26 cloud-vm systemd[1]: etcd.service: Scheduled restart job, restart counter is at 42.
Oct 27 02:11:26 cloud-vm systemd[1]: Stopped etcd.

**Comment by thecloudgarage** [comment]
CONFIRMED: The documented procedure on the eks anywhere website for customizing OVAs is faulty and does not work.

I am finally able to get it working with the below workarounds

In the metadata.yaml do not include any other configuration except the instance-id line

Once the virtual machine is ready, SSH and make whatever changes required. Once done., execute the below steps. The main step is to change the cloud.cfg entry for hostname preservation from true to false)

sudo su
echo -n > /etc/machine-id
rm /var/lib/dbus/machine-id
ln -s /etc/machine-id /var/lib/dbus/machine-id
sudo cloud-init clean
sudo cloud-init clean -l
sudo nano /etc/hostname (delete the entry of localhost) 
rm -rf  /etc/netplan/50-cloud-init.yaml
nano /etc/cloud/cloud.cfg (change preserve hostname to false)

Once done, we can exit the virtual machine and convert it to the template and tag it respectively.

Now the cluster creation occurs with the customized ubuntu OVA.

EKS Anywhere team, please test this at your end and make it an official process documented appropriately. The downside of not doing this is that customers can only resort to bottlerocket without any alternatives to use ubuntu (as there will be customizations required ssl-certs, additional packages, etc.)

**Comment by vignesh-goutham** [comment]
Perfect, thanks for testing this at your end. This makes sense where you have to change the hostname preservation to false. We will test these suggestions and change the official documentation around this.
