### ISSUE TITLE
Revisit "upgrade needed" logic

### ISSUE THREAD

**Issue by g-gaston** [aws/eks-anywhere#399]
Currently, we only trigger CP and Workers upgrade if the new cluster config (including cluster crd and some of provider specific ones) differs from the one installed in the cluster.

This could be problematic:
* Since we set some defaults for certain fields in the config if the user hasn't provided them, we could be triggering upgrades that are not desired if those default values change from create to upgrade
* Even if the cluster config doesn't change, there could components that need to be upgraded that are only reflected in the specs generated by the providers (think kube-vip, BR bootstrap, etc.)

We should revisit this logic. Do we keep what we have and add more logic to handle components upgrades? Do we change the approach? How do we make this more future proof/less fragile against changes in default fields?

**Comment by jiayiwang7** [comment]
> * e.g. If default memory changes from 8192 to 4096, then we do NOT need to trigger the upgrade

Chatted with Guillermo offline. we should treat default value as it was during create. Let `kubectl apply` merge changes for us.
