### ISSUE TITLE
Artifacts on docs show v0.12.1 to use 1-23-eks-22 but should be 1-23-eks-7

### ISSUE THREAD

**Issue by ronpichardo** [aws/eks-anywhere#4093]
**What happened**:
Using eksa v0.12.1
According to the docs the EKS-D Release for 1.23 is “eksdRelease:kubernetes-1-23-eks-22” but fails because the tag should have actually been “eksdRelease:kubernetes-1-23-eks-7” instead
https://anywhere.eks.amazonaws.com/docs/reference/artifacts/

```shell
Validation failed     {"validation": "vsphere Provider setup is valid", "error": "template /********/Templates/bottlerocket-v1.23.22-eks-d-1-23-22 is missing tag eksdRelease:kubernetes-1-23-eks-7", "remediation": ""}
```

**Environment**:
- EKS Anywhere Release: v0.12.1
- EKS Distro Release: 0.118.0

**Comment by mitalipaygude** [comment]
hi Ron, thank you for bringing this up to our attention, we will update the docs.

**Comment by mitalipaygude** [comment]
Once this [PR](https://github.com/aws/eks-anywhere/pull/4144) merges, the docs will be updated.

**Comment by mitalipaygude** [comment]
Hey @ronpichardo , this is resolved from our side. Please let me know if you are good to go and I can close this issue out.

**Comment by danbudris** [comment]
Doc update is merged and public docs reflect this
