### ISSUE TITLE
Allow users to have specify different templates in `VSphereMachineConfig`

### ISSUE THREAD

**Issue by abhinavmpandey08** [aws/eks-anywhere#4255]
**What would you like to be added**:
Currently, for vSphere provider, all the machine configs are required to have the same template config. If you try to provide a different template, the CLI fails with the preflight `all VSphereMachineConfigs must have the same template specified`

**Why is this needed**:
Users may want to configure templates with specific settings for specific node groups which can be propagated down to the cloned VMs. The same template shouldn't be required as long as the K8S version and osFamily of the template are the same.

**Comment by chrisdoherty4** [comment]
Are we able to gather some insights into what kind of settings are being tweaked?

**Comment by abhinavmpandey08** [comment]
> Are we able to gather some insights into what kind of settings are being tweaked?

This specific ask was for `sched.swap.vmxSwapEnabled=FALSE` but there are some other advanced VM level settings that other users might have configure.

**Comment by nickperry** [comment]
This restriction also precludes use of EKS Anywhere within my organization.

**Comment by abhinavmpandey08** [comment]
Hi @nickperry, can you explain the use-case for using different templates in your org if you don't mind?
Just trying to collect all the data points here to determine the priority of this issue. Thanks!

**Comment by nickperry** [comment]
We would like to be able to deliver OVAs with additional pre-pulled container images.

We also just fundamentally don't like having unnecessary restrictions imposed in vendor product abstractions over an underlying more flexible technology (CAPV in this case).

**Comment by jiayiwang7** [comment]
Feature will be included in the upcoming v0.17.0 release. Closing issue.
