### ISSUE TITLE
GitOps with CodeCommit in FluxConfig with git configuration fails in validation stage

### ISSUE THREAD

**Issue by prakkie-others** [aws/eks-anywhere#4290]
**What happened**:

I wanted to use CodeCommit repository as GitRepository source for Flux and followed instructions mentioned [here](https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-flux/#getting-started-with-eks-anywhere-gitops-with-any-git-source). RepoURL is not accepted in any form. I have tested the same RepoURL format directly from admin machine and it is accessible. Same configuration works fine for GitHub RepoURL. 

Cluster creation throws below error

```
2022-12-05T17:01:26.568Z        V6      Executing command       {"cmd": "/usr/bin/docker run -d --name eksa_1670259686399887634 --network host -w /home/ssm-user/gw2 -v /var/run/docker.sock:/var/run/docker.sock -v /root/.ssh:/root/.ssh -v /root/.ssh:/root/.ssh -v /home/ssm-user/gw2:/home/ssm-user/gw2 -v /home/ssm-user/gw2:/home/ssm-user/gw2 --entrypoint sleep public.ecr.aws/eks-anywhere/cli-tools:v0.12.2-eks-a-21 infinity"}
2022-12-05T17:01:26.840Z        V3      Validating git setup    {"repoUrl": "ssh://APKAEIBAERJR2EXAMPLE@git-codecommit.us-west-2.amazonaws.com/v1/repos/eksa-gitops"}
Error: connecting with remote origin for repository: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Observed username hardcoded to git at this [line of gitfactory.go](https://github.com/aws/eks-anywhere/blob/9f4e7f794737f0f07dc5353ab71380df75915c04/pkg/git/factory/gitfactory.go#L135)

**What you expected to happen**:

Git configuration of FluxConfig should accept RepoURL format of CodeCommit. CodeCommit repository URL format for SSH access is `ssh://<SSH Key ID>@git-codecommit.<REGION>.amazonaws.com/v1/repos/<REPO NAME>`. For example: `ssh://APKAEIBAERJR2EXAMPLE@git-codecommit.us-west-2.amazonaws.com/v1/repos/eksa-gitops`

Note that CodeCommit SSH access is through SSH Key ID which acts like username. For GitHub git is a standard user.

**How to reproduce it (as minimally and precisely as possible)**:

Create a FluxConfig as shown below and try upgrading cluster

```
 gitOpsRef:
    kind: FluxConfig
    name: gw2-cluster-gitops

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: gw2-cluster-gitops
spec:
    git:
      repositoryUrl: ssh://APKAEIBAERJR2EXAMPLE@git-codecommit.us-west-2.amazonaws.com/v1/repos/eksa-gitops
      sshKeyAlgorithm: rsa
```

**Anything else we need to know?**:

**Environment**: Ubuntu - vSphere
- EKS Anywhere Release: 0.12.2

**Comment by danbudris** [comment]
Thanks for the report, we'll take a look at this ASAP

**Comment by Paulius0112** [comment]
Is this issue solved?
