### ISSUE TITLE
Upgrade Control Plane then worker nodes in controller

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#432]
**What would you like to be added**:

**Why is this needed**:

To support etcd machine upgrade

**Comment by mrajashree** [comment]
quick update from recent discussions: etcd machineconfig upgrade does work even when controlplane and worker nodes are upgraded at the same time from the controller.
But the upgrade from k8s 1.20 to 1.21 needs the upgrade to happen in the order (more details [here](https://github.com/aws/eks-anywhere/pull/16))
