### ISSUE TITLE
Expose kube-scheduler and kube-controller-manager metrics

### ISSUE THREAD

**Issue by Cajga** [aws/eks-anywhere#4405]
**What would you like to be added**:
We would like to be able to scrape the kube-scheduler and the kube-controller-manager metrics which are important to understand the state of the cluster. Both of these services are exporting Prometheus metrics but by default, we cannot scrape them in EKS Anywhere as these services are only listening on localhost (at least on Bare Metal installations... I do not have EKS-A on other platform to verify this).

A simple way would be to modify the `/etc/kubernetes/manifests/kube-scheduler.yaml` and the `/etc/kubernetes/manifests/kube-controller-manager.yaml` files to have `--bind-address=0.0.0.0` in them (manually modifying these files on the masters is my workaround at the moment).

**Why is this needed**:
As mentioned above, these are important metrics to understand the state of the cluster and set up proper alerting/visualisation in a production environment.

**Comment by g-gaston** [comment]
Thanks for the suggestion @Cajga, we will look into it!
