### ISSUE TITLE
Installing kubectl is missing from manual linux instructions.

### ISSUE THREAD

**Issue by raykrueger** [aws/eks-anywhere#4482]
**What would you like to be added**:

The manual Mac and Linux instructions [here](https://anywhere.eks.amazonaws.com/docs/getting-started/install/) do not include installing Kubectl.

**Why is this needed**:
For completeness, when installing the tools manually via curl, there is nothing that will install kubectl.

**Comment by TerryHowe** [comment]
Thanks, ideally we'd be pulling kubectl from EKS-D, but probably easier to do it some other way.

**Comment by raykrueger** [comment]
PR is up, if you'd like me to go another route let me know.
