### ISSUE TITLE
update vsphere-csi-driver to min 2.5.4

### ISSUE THREAD

**Issue by janre** [aws/eks-anywhere#4626]
To use persistent storage with eksa, we lack the latest version (min 2.5.4) of the vsphere-csi-driver.
Problem: If a pv is attatched to a node and this node is deleted, the existing volume cannot be attatched to a new node. There is a fix for this in the vsphere-csi-driver, which was merged into version 2.5.4
issue: https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/359 
fixed with PR: https://github.com/kubernetes-sigs/vsphere-csi-driver/pull/1879
VMware vSphere Container Storage Plug-in 2.5 Release Notes: https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.5/rn/vmware-vsphere-container-storage-plugin-25-release-notes/index.html

**Comment by TerryHowe** [comment]
```
cat ../eks-anywhere-build-tooling/projects/kubernetes-sigs/vsphere-csi-driver/GIT_TAG 
v2.2.0
```
