### ISSUE TITLE
Feat: Support GitOps for Baremetal cluster

### ISSUE THREAD

**Issue by Cajga** [aws/eks-anywhere#4639]
**What would you like to be added**:
As it [turned out](https://github.com/aws/eks-anywhere/issues/4601#issuecomment-1382135702) GitOps is not supported for Baremetal clusters. It is also "Noted" in the [documentation](https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-flux/).

**Why is this needed**:
We are managing our clusters, add-ons and applications on top of kubernetes exclusively through GitOps. EKS-A GitOps integration is awesome and we would love to use it in our Baremetal clusters.

**Comment by lewisdiamond** [comment]
This feature is already planned. Closing, we will track this internally.

**Comment by Cajga** [comment]
@lewisdiamond could you please provide us an update of the status of this? We are really looking forward to have this implemented.
