### ISSUE TITLE
Allow users to pass custom trusted cert bundle to Bottlerocket

### ISSUE THREAD

**Issue by abhinavmpandey08** [aws/eks-anywhere#4761]
In Bottlerocket, this can be configured through here: https://github.com/bottlerocket-os/bottlerocket#custom-ca-certificates-settings
```
  pki.my-trusted-bundle.data="W3N..." \
  pki.my-trusted-bundle.trusted=true 
```

- [x] Update CAPI on our fork here: https://github.com/abhay-krishna/cluster-api
- [x] Update CAPI as a patch on eks-anywhere-build-tooling: https://github.com/aws/eks-anywhere-build-tooling
- [x] Make relevant changes on eks-anywhere as necessary: https://github.com/aws/eks-anywhere
- [x] Make relevant changes on etcd repos as necessary: https://github.com/aws/etcdadm-bootstrap-provider, https://github.com/aws/etcdadm-controller
- [ ] Add E2E tests if needed
- [ ] Update docs if needed

**Comment by Paulius0112** [comment]
We have the same problem with fully private cluster. Unable to pull docker images once bottlerocket is booted, since our self-signed certificate is not trusted
