### ISSUE TITLE
Need better documentation on Curated Packages setup after cluster creation

### ISSUE THREAD

**Issue by raykrueger** [aws/eks-anywhere#4832]
**What would you like to be added**:
We need a clearly defined page, or addition to the setup page for curated packages, that explains how to set everything up *after* cluster creation.

**Why is this needed**:
We have a troubleshooting [guide here](https://anywhere.eks.amazonaws.com/docs/tasks/packages/troubleshoot/#error-imagepullbackoff-on-package-or-package-controller) that explains the steps. However, setting up curated packages *after* cluster creation is the most common path. In addition, the `crt image pull` is simply not valid and doesn't help clarify.

**Comment by raykrueger** [comment]
I would like to tweak the [main page](https://anywhere.eks.amazonaws.com/docs/tasks/packages/) so that we cover the before and after cluster creation usecases.

**Comment by TerryHowe** [comment]
Currently, the only mention to copy packages is https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/optional/registrymirror/

**Comment by TerryHowe** [comment]
I'm going to leave the `ctr image pull` in there for now because that will work once the kubelet credential helper is in there which will be in 3 weeks or so.

**Comment by TerryHowe** [comment]
> I'm going to leave the `ctr image pull` in there for now because that will work once the kubelet credential helper is in there which will be in 3 weeks or so.

I'm back pedaling on that. Created PR above
