### ISSUE TITLE
Clarification of supported Linux distros

### ISSUE THREAD

**Issue by bencehornak** [aws/eks-anywhere#4852]
**What would you like to be added**: I would like to see it clearly in the [Getting started guide](https://anywhere.eks.amazonaws.com/docs/getting-started/install/), what distros are also supported.

**Why is this needed**: According to the 'Administrative machine prerequisites' only Ubuntu 20.04.2 LTS is supported. However, a paragraph later instructions are given for Ubuntu 21.10 and 22.04. So are these also supported versions? What about other distros, like Debian, SUSE, RHEL, ...? Are there any known issues with these?

**Comment by jiayiwang7** [comment]
We shall maintain a matrix of OS version supported for each EKS-A version in doc.

**Comment by jiayiwang7** [comment]
We will also need to run a sanity check over the entire EKS-A doc site (especially in the Artifacts section) and provide clear guidance on which image versions (for each OS) are supported for each EKS-A version.

**Comment by chrisnegus** [comment]
This is a good callout. We should also make clear that different operating systems and versions are supported for the Admin machine, as well as each provider. For example, although RHEL is supported for some providers, it is not currently supported on the Admin machine.
