### ISSUE TITLE
Support `node-labels`

### ISSUE THREAD

**Issue by g-gaston** [aws/eks-anywhere#486]
Add the ability to specify node labels for the different machine groups (CP and worker groups) in the eks-a cluster config. They should be retained through node restart and kubernetes upgrades.

[Design doc](https://github.com/aws/eks-anywhere/blob/main/designs/node-labels.md)

- [x] Add support for node labels on worker nodes (docker & ubuntu)
- [x] Add support for node labels on cp nodes (docker & ubuntu) (https://github.com/aws/eks-anywhere/pull/929)
- [x] Add support for node labels with Bottlerocket (https://github.com/mrajashree/cluster-api/pull/6)
- [x] #1053

**Comment by danbudris** [comment]
https://github.com/aws/eks-anywhere/pull/929

**Comment by danbudris** [comment]
https://github.com/mrajashree/cluster-api/pull/6
