### ISSUE TITLE
Call to K8S version API for the EKS cluster in ap-northeast-2 (seoul) is failing with unauthorized code 401.

### ISSUE THREAD

**Issue by sp-rackware** [aws/eks-anywhere#4893]
- We are calling the K8S API to get version of the cluster. The URL is https://<endpointIP>:443/version . 
- But the HTTP request is failing with this error - GET request to the remote host failed [HTTP-Code: 401]: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
- This call is working in other AWS regions for ex us-east-2(ohio), us-east-1, ap-south-1 etc. But specifically failing in this region.
- I have checked IAM console this region is enables for STS service
- While calling the K8S API we are passing STS token (with standard AWS signature calculation). 

So I am not getting why it is failing in only a specific region?

**Comment by raykrueger** [comment]
Hi @sp-rackware, this repository is related to EKS Anywhere the open source distribution of EKS Distro that runs on on-premises hardware. It looks like your question is about AWS EKS in the cloud. You may want to open a support question in that case. Also, take a look at your Configmap, make sure the IAM user has permissions https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

**Comment by jacobweinstock** [comment]
Thanks @raykrueger. @sp-rackware, please do reach out to EKS proper for help with this!
