### ISSUE TITLE
[CAPC Provider] EKSA Controller unable to reconcile new worker group config CRD changes

### ISSUE THREAD

**Issue by jacobweinstock** [aws/eks-anywhere#4926]
**What would you like to be added**:
It has been requested for the Cloudstack provider to be able to create a new workernode group directly on the custom resource, and then when editing the "cluster" custom resource later to scale/use the new workernodegroup that should end up creating the workers, vm, etc.

**Why is this needed**:

**Comment by chrisdoherty4** [comment]
This issue should be resolved with the release of cluster lifecycle 
CloudStack support in v0.16.
