### ISSUE TITLE
How do I list my eksctl anywhere clusters? e.g. `eksctl anywhere list clusters`

### ISSUE THREAD

**Issue by jtele2** [aws/eks-anywhere#4949]
**What would you like to be added**:
`eksctl anywhere list clusters`

**Why is this needed**:
I lost access to my cluster - the config file is not working. `kubectl get po -A` returns this: 
```
E0214 15:18:37.242109   13360 memcache.go:238] couldn't get current server API group list: Get "https://127.0.0.1:44681/api?timeout=32s": dial tcp 127.0.0.1:44681: connect: connection refused
```

I need to check the cluster to see if it is running - but there is no way to list clusters created locally with the ekcstl anywhere command. I followed the [AWS eksctl anywhere local setup directions](https://anywhere.eks.amazonaws.com/docs/getting-started/local-environment/).

**Comment by TerryHowe** [comment]
If you have your kubeconfig pointed to your management cluster, you can run `kubectl get clusters`. Since your api server is on local host, maybe you are running a docker provider cluster?

**Comment by TerryHowe** [comment]
Just run `docker ps` and see if any containers are running?

**Comment by jtele2** [comment]
> 



> Just run `docker ps` and see if any containers are running?

I just did that... also did see that it was a kind cluster. I'll close the issue, would be nice if it was in the docs though. Maybe I'll submit a pull request for the docs.
