### ISSUE TITLE
Copy packages command only pulls from us-west-2

### ISSUE THREAD

**Issue by raykrueger** [aws/eks-anywhere#4984]
**What happened**:
In environments that are restricted to specific regions (such as us-east-1), the copy packages command will fail.

**What you expected to happen**:
I expected EKSA_AWS_REGION or AWS_REGION to be respected.

**How to reproduce it (as minimally and precisely as possible)**:
Set your IAM user permissions resource to us-east-1 and try `eksctl anywhere copy packages`

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.14.1
- EKS Distro Release:

**Comment by raykrueger** [comment]
Additionally it seems to be pulling from the packageDevDomain location. https://github.com/aws/eks-anywhere/blob/main/pkg/curatedpackages/reader.go#L28

```
Error: registry copy: GET https://857151390494.dkr.ecr.us-west-2.amazonaws.com/v2/adot/aws-observability/aws-otel-collector/manifests/sha256:c6c5db250d6590dcea15a1634254395c37bdb9d60f8d36720a9040a941e50677: credential required for basic auth
 ```

**Comment by binyamz** [comment]
> 

Hi Ray, can you share the version of the CLI that is pulling from Dev repo? You can run `eksctl anywhere version` to get the version.

**Comment by TerryHowe** [comment]
https://github.com/aws/eks-anywhere/pull/5007

**Comment by raykrueger** [comment]
Disregard my comment above, as Terry pointed out that was a mistake on my part.

**Comment by TerryHowe** [comment]
https://dev-release-assets.eks-anywhere.model-rocket.aws.dev/eks-anywhere/v0.0.0-dev-build.5969/eks-a-cli/darwin/amd64/eksctl-anywhere-v0.0.0-dev-build.5969-darwin-amd64.tar.gz dev build
