### ISSUE TITLE
Package troubleshooting guide "Error: ImagePullBackOff on Package or Package Controller" resulted in failed jobs

### ISSUE THREAD

**Issue by hendryanw** [aws/eks-anywhere#5003]
**What happened**: 
Packages troubleshooting guides on section *Error: ImagePullBackOff on Package or Package Controller* resulted in failed jobs due to mismatched secret key name used in the job and troubleshooting guide.

**What you expected to happen**:
Troubleshooting guide should be fixed to help customers during troubleshooting process.

**How to reproduce it (as minimally and precisely as possible)**:
- Run a bare-metal cluster on v1.24 without packages setup in the beginning of cluster creation
- Acquire access to EKS-A Curated Packages
- Setup the packages following this docs: https://anywhere.eks.amazonaws.com/docs/tasks/packages/
- Deploy a package into the cluster e.g. metrics-server
- metrics-server pods would not run due to failed image pull
- Follow this troubleshooting guide to troubleshoot the issue: https://anywhere.eks.amazonaws.com/docs/tasks/packages/troubleshoot/#error-imagepullbackoff-on-package-or-package-controller
- Issue still persists

**Anything else we need to know?**:
- The issue can be fixed by investigating the pod spawned from the job created during the troubleshooting process. It describes secret key name used during the job execution cannot be found. The secret key name are: 
  - `AWS_ACCESS_KEY_ID` instead of `ID` in the troubleshooting guide
  - `AWS_SECRET_ACCESS_KEY` instead of `SECRET` in the troubleshooting guide
  - By changing the secret key name, the issue is then fixed and the packages can be deployed successfully.
- I haven't yet investigated why the packages setup following this doc: https://anywhere.eks.amazonaws.com/docs/tasks/packages/ also resulted in failed package deployment. Perhaps there's also mismatched env variable name / secret name within the code.

**Environment**:
- EKS Anywhere Release: v1.24
- EKS Distro Release: N/A

**Comment by hendryanw** [comment]
Looking forward for team's feedback. I might be able to submit a pull request to fix at least the docs.

**Comment by ivyostosh** [comment]
@hendryanw Thanks for the feedback. We will look into the issue and circle back.

**Comment by vincentni** [comment]
Thanks for reaching out to us! The documentation is a bit out-of-dated, and we'll update the secret key names soon.

**Comment by ivyostosh** [comment]
@hendryanw The doc site has been updated.

**Comment by TerryHowe** [comment]
https://github.com/aws/eks-anywhere/pull/5020 Should fix this issue, reopen if there are any concerns, thanks!
