### ISSUE TITLE
IRSA Support for Snow

### ISSUE THREAD

**Issue by evdevr** [aws/eks-anywhere#5009]
**What would you like to be added**: IRSA Support for Snow clusters

**Why is this needed**: Users with Snow clusters want to send metrics back to AWS using ADOT w/IRSA.

Today, if a user tries to add a serviceAccountIssuer in their cluster spec, it's not passed through to the kube-api config so the pod-identity-webhook does not work.

**Comment by jiayiwang7** [comment]
@evdevr We do pass the serviceAccountIssuer arg in cluster spec to create KCP for snow provider.

I just tested IRSA for snow and it works:

```
bash-4.2# aws amp list-workspaces --region=us-west-2
{
    "workspaces": [
        {
            "alias": "adot-amp-test",
            "arn": "arn:aws:aps:us-west-2:xxxxxxxx:workspace/ws-xxxxxxxx",
            "createdAt": "2023-02-22T14:17:39.353000+00:00",
            "status": {
                "statusCode": "ACTIVE"
            },
            "tags": {},
            "workspaceId": "ws--xxxxx"
        }
    ]
}
```

Notice there is a bug in `amazon-eks-pod-identity-webhook` repo where to fix it temporarily you need to manually create the mutation webhook and test again. REF: https://github.com/aws/amazon-eks-pod-identity-webhook/issues/176

Feel free to test out. Closing the issue.
