### ISSUE TITLE
Upgrade Cilium to v1.13.0

### ISSUE THREAD

**Issue by drewvanstone** [aws/eks-anywhere#5030]
**What would you like to be added**:
Following [these instructions](https://github.com/aws/eks-anywhere-build-tooling/tree/main/projects/cilium/cilium#updating), let's bump Cilium to the latest versions.

**Why is this needed**:
We need this for security patches, support and for new features.

**Comment by bmike78** [comment]
This would be great!  I've been waiting for a newer version of Cilium on EKS-A for observability features utilizing eBPF that need at least Cilium 1.13.0 or higher.

**Comment by chrisdoherty4** [comment]
v1.13 has been made available at https://gallery.ecr.aws/isovalent/cilium so we should now be able to do the upgrade work.

**Comment by raymond-zhang00** [comment]
completed
