### ISSUE TITLE
Customise cilium IPAM

### ISSUE THREAD

**Issue by Paulius0112** [aws/eks-anywhere#5052]
**What would you like to be added**:

Please include the functionality to kustomize how cilium provides IP addresses to pods. Our underlying infrastructure is running on VRF configuration and cilium has an IPAM configuration that supports the underlying VRF. However with EKS, it's impossible to implement as of now. For example: https://docs.cilium.io/en/v1.12/concepts/networking/ipam/kubernetes/

**Why is this needed**:

We want out pods to be in the same CIDR as underlying nodes (nodes use VRF for IP assignment)

**Comment by Paulius0112** [comment]
For now, if I specify the same CIDR as the VRF, the healthcheck fails for worker nodes and they never come up healthy. Here's is the error message from the kubelet service inside the worker
```cni plugin not initialized```

**Comment by jonathanmeier5** [comment]
@Paulius0112 what virtualization provider are you using? vsphere? or none with bare metal?

**Comment by Paulius0112** [comment]
We are only using bare metal

**Comment by chrisdoherty4** [comment]
@Paulius0112 What's the motivation for having Pods reside on the same subnet as nodes as opposed to using Services?
