### ISSUE TITLE
Allow customization of kube API Server load balancer

### ISSUE THREAD

**Issue by jacobweinstock** [aws/eks-anywhere#5056]
**What would you like to be added**:
I would like to be able to customize the deployment of the kubernetes api server load balancer, including disabling the deployment entirely.

**Why is this needed**:
The current offering for the kubernetes api server load balancer is kubevip using layer 2 arp mode. This is not always permissible in a network. Kubevip can be deployed using BGP (layer 3). Adding customization to this deployment would allow the load balancer to use only layer 3 networking to load balance the kube api server and ultimately make it more flexible to fit the wide variety of networks in which EKSA runs. Being able to disable the deployment of kubevip entirely would add to the flexibility needed to meet the variety of networks in which we deploy. This would allow external load balancers to be used or allow a custom load balancer solution to be deployed instead. Again, more flexibility.

**Comment by d8660091** [comment]
For tinkerbell, it should be relatively easy.
1. allow users to put kube-vip env variables in the cluster yaml file
2. inject the kube-vip env variables https://github.com/aws/eks-anywhere/blob/main/pkg/providers/tinkerbell/config/template-cp.yaml#L185

**Comment by d8660091** [comment]
https://github.com/aws/eks-anywhere/pull/5641
