### ISSUE TITLE
IdentityRef failed for Snow provider

### ISSUE THREAD

**Issue by yxinchen** [aws/eks-anywhere#5082]
**What happened**:
IdentityRef failed for Snow provider
```
E0227 17:07:34.503728       1 awssnowmachine_controller.go:274]  "msg"="failed to retrieve credentials from IdentityRef" "error"="Access Key Id or secret access key does not exist" "aWSSnowMachine"={"name":"chy-test-md-0-1-gbzzf","namespace":"eksa-system"} "cluster"="chy-test" "controller"="awssnowmachine" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controllerKind"="AWSSnowMachine" "machine"="chy-test-md-0-58489656b-9whj8" "name"="chy-test-md-0-1-gbzzf" "namespace"="eksa-system" "reconcileID"="a73fd5b2-0e60-4826-9140-ef1099be47e0"
```

The Root cause is both of the credentials and ca_bundles data in `<cluster-name>-snow-credentials` secret are double base64 encoded

**What you expected to happen**:
The secret data should be only base64 encoded once.

**How to reproduce it (as minimally and precisely as possible)**:
Create a snow cluster, and check capas pod logs. 
Manually get the `<cluster-name>-snow-credentials` secret data, run `base64 -d` <secret data string> will return another base64 encoded string, and run `base64 -d <secret data string> | base64 -d` will return the decoded credentials/ca-bundles string.
Did not include the secret data since it has aws credentials.

**Anything else we need to know?**:
Need to have this fixed in next v0.14.3 patch release

**Environment**:
- EKS Anywhere Release: v0.14.2
- EKS Distro Release: v1.23.16-eks-1-23-14

**Comment by jiayiwang7** [comment]
It is a false alarm: snow has a script to autogen creds/certs for the users and the code is missing a space https://github.com/aws-samples/aws-snow-tools-for-eks-anywhere/blob/main/setup-tools/create-creds-and-certs-files.sh#L129
`aws_access_key_id=` while CAPAS has a strict rule to look for `aws_access_key_id =` so it failed

Closing as there is no eks-a issue.
