### ISSUE TITLE
DOC - Harbor proxy for ECR private endpoint guide is outdated

### ISSUE THREAD

**Issue by hendryanw** [aws/eks-anywhere#5100]
**What happened**:
Following the documentation to setup ECR Private proxy using Harbor package resulted in error not being able to register the endpoint.
https://anywhere.eks.amazonaws.com/docs/workshops/packages/harbor/#proxy-a-private-amazon-elastic-container-registry-ecr-repository

**What you expected to happen**:
The documentation should be fixed to ensure new users / customers can get up to speed using Harbor curated package to proxy their private ECR repository.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup EKS-A Cluster (Mine is 1.24 Bare Metal)
2. Install Harbor curated package
3. Follow this guide https://anywhere.eks.amazonaws.com/docs/workshops/packages/harbor/#proxy-a-private-amazon-elastic-container-registry-ecr-repository
4. During new registry endpoint, the creation will fail with error "endpoint is unhealthy"

**Anything else we need to know?**:
The issue is caused by endpoint used in the guide is wrong / outdated. Recent PR in the Harbor reflected that the endpoint should be selected from the drop-down: https://github.com/goharbor/harbor/pull/17645

Additionally, when you install Harbor with "harbor-tls-secret" as secretKey name using another guide here: https://anywhere.eks.amazonaws.com/docs/tasks/packages/harbor/ - the new registry endpoint will also fail with "internal server error". This is caused by "harbor-tls-secret" is a 17 characters key, while Harbor expected exact 16 characters key.

**Environment**:
- EKS Anywhere Release: 1.24 Bare Metal
- EKS Distro Release: N/A

**Comment by vincentni** [comment]
Thanks for reaching out to us! 1) for the endpoint, could you please double check if you specify the right region in the endpoint? I'm not able to reproduce the issue you ran into on my side. 2) for the secretKey, the `harbor-tls-secret` in the doc is referring to the name of the secret resource you may want to create, not the secretKey itself. In fact, the doc uses `use-a-secret-key` and that does conform to the 16-character key requirement.

**Comment by vincentni** [comment]
Also, for your first issue, you may want to check the log of the `harbor-core` pod. To increase the verbose level, try to set up `logLevel` when you install the Harbor package (https://anywhere.eks.amazonaws.com/docs/reference/packagespec/harbor/v2.5.1/).

**Comment by hendryanw** [comment]
Hi @vincentni , thanks for your response. To clarify, I have resolved the issue on my end, and would like to report it to improve the docs for other users.

Double-checking:
1) > for the endpoint, could you please double check if you specify the right region in the endpoint? I'm not able to reproduce the issue you ran into on my side. 

If you follow the docs at https://anywhere.eks.amazonaws.com/docs/workshops/packages/harbor/#proxy-a-private-amazon-elastic-container-registry-ecr-repository - on the section after creating IAM user for the Harbor IAM access.
Quoted from the docs:
> Navigate to Registries on the left panel, and then click on NEW ENDPOINT button. Choose Aws ECR as Provider, and enter private-ecr as Name, https://[ACCOUNT NUMBER].dkr.ecr.us-west-2.amazonaws.com/ as Endpoint URL, use the access key ID part of the generated access key as Access ID, and use the secret access key part of the generated access key as Access Secret. Save it by click on OK.

The endpoint used in the docs is wrong, it should be https://api.ecr.[REGION].amazonaws.com. Can you please double check?

> 2) for the secretKey, the harbor-tls-secret in the doc is referring to the name of the secret resource you may want to create, not the secretKey itself. In fact, the doc uses use-a-secret-key and that does conform to the 16-character key requirement.

I've double-check the secretKey usage. You're right - I did mixed up the usage of the secretKey (which is supposed to be used only for internal core encryption) with the `harbor-tls-secret` secretName which was supposed to be only used for TLS. 
Quoted from this doc: https://anywhere.eks.amazonaws.com/docs/tasks/packages/harbor/
> TLS is enabled by default for connections to Harbor web portal, and a secret resource named harbor-tls-secret is required for that purpose. It can be provisioned through cert-manager or manually with the following command using self-signed certificate:
`kubectl create secret tls harbor-tls-secret --cert=[path to certificate file] --key=[path to key file] -n eksa-packages`

So, no issue for number 2. Just a confusion. Thanks for the clarifications!

**Comment by vincentni** [comment]
Hi @hendryanw , glad that you are able to resolve the issue. I went through the [ecr doc](https://docs.aws.amazon.com/general/latest/gr/ecr.html), and the one mentioned in current doc is for OCI clients to pull and push images. I also tried the other endpoint you are using, but faced the `Failed to ping endpoint` error.
