### ISSUE TITLE
IRSA support for Nutanix

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#5117]
Snow, vSphere, CloudStack providers all support pod IRSA. But this is missing from Nutanix code.

The implementation should be straightforward, we will need to add https://github.com/aws/eks-anywhere/blob/main/pkg/clusterapi/extraargs.go#L57 in
https://github.com/aws/eks-anywhere/blob/main/pkg/providers/nutanix/template.go#L129
when building the KCP template. Refer to vSphere and Cloudstack template builder code for reference.

We should test the feature following: https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/optional/irsa/

**Comment by thunderboltsid** [comment]
/assign @thunderboltsid 
PR(WIP): https://github.com/aws/eks-anywhere/pull/5698
