### ISSUE TITLE
Documentation about using `kubectl` to create workload clusters

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#5119]
As EKS-A officially supports cluster full lifecycle for vSphere, Snow providers. User can now create a workload cluster directly with `kubectl apply -f workload-cluster-spec.yaml --kubeconfig mgmt.kubeconfig`. 

Though this way of managing workload clusters is not documented in EKS-A doc site. We have 
- manage a cluster w GitOps: https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-flux/
- manage a cluster w terraform: https://anywhere.eks.amazonaws.com/docs/tasks/cluster/cluster-terraform/

Sometimes it is not obvious to all users that we can also use `kubectl` or any native Kubernetes API to manage EKS-A clusters.

**Comment by chrisnegus** [comment]
One way to handle this documentation is to add a "Cluster operations" concept page to the docs, describing different ways to create and manage an EKS Anywhere cluster.

This page would be there mostly to highlight the ability to use Lifecycle API approaches to manage a cluster with kubectl. But we would mention other supported cluster operations methods as well.

**Comment by ddjjia** [comment]
@chrisnegus @jiayiwang7 If we already decide to add kubectl in 0.16.0, then it should be removed from this [pr](https://github.com/aws/eks-anywhere/pull/5302/files)

**Comment by chrisnegus** [comment]
@jiayiwang7 Please let me know if [PR #5302](https://github.com/aws/eks-anywhere/pull/5302) is enough to address this issue.
