### ISSUE TITLE
A validation or health status check for the Management cluster would be useful

### ISSUE THREAD

**Issue by raykrueger** [aws/eks-anywhere#5131]
**What would you like to be added**:
I would like some sort of `eksctl anywhere validate cluster` like command that can be pointed at the management cluster to validate that all capi and eks-a components are installed and ready.

**Why is this needed**:
If the management cluster is missing any capi or eks-a controllers an attempt to deploy a workload cluster will silently fail. For example, machines might be created but they won't be formed up into a cluster.

**Comment by jiayiwang7** [comment]
Duplicate issue: #5268

**Comment by jiayiwang7** [comment]
Duplicate issue, closing in favor of https://github.com/aws/eks-anywhere/issues/5268
