### ISSUE TITLE
Taints and labels support for Nutanix provider

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#5172]
Add support for node taints and node labels for Nutanix provider.

Taints are used to mark a node as unsuitable for certain pods. A taint consists of a key, value, and an effect. When a node is tainted with a certain key-value pair and effect, Kubernetes will not schedule any pods that do not have a matching toleration for that taint.

Labels, are used to organize and select objects in Kubernetes, like pods, services, and nodes. A label is a key-value pair that can be attached to any object in the cluster. Labels are used to group related objects together, and to allow selectors to find and operate on specific objects based on their labels. 

More details around this feature:
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

This feature already exists for the other providers like vSphere, Tinkerbell etc. Here are some links from vsphere provider for reference

[cp-taint](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/tinkerbell/config/template-cp.yaml#L136-L149)
[worker-taint](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/tinkerbell/config/template-md.yaml#L101-L111)

Reference of a PR for adding support for [Taints and labels for Tinkerbell](https://github.com/aws/eks-anywhere/pull/2480)

**Comment by thunderboltsid** [comment]
PR for adding support https://github.com/aws/eks-anywhere/pull/5282
