### ISSUE TITLE
image-builder os rhel baremetal BuildImage index out of range [0] with length 0

### ISSUE THREAD

**Issue by oraclefoo** [aws/eks-anywhere#5186]
**What happened**: HPE DL360 (server dedicated to image-builder) running RHEL8.7. Follow https://anywhere.eks.amazonaws.com/docs/reference/artifacts/#build-bare-metal-node-images 

{
  "iso_url": "file:///home/image-builder/rhel-8.7-x86_64-boot.iso",
  "iso_checksum": "47e5dbb37b5970f583d0852973af86cc1b522ee1f1e2374c59204583c14717fa",
  "iso_checksum_type": "sha256",
  "rhel_username": "<user>",
  "rhel_password": "<pwd>",
  "extra_rpms": "NetworkManager"
}

<user> = actual rhel user, <pwd> = actual rhel user password (is this clear text?)

(tried with unix path to iso url - same index out of range error)
-rw-r--r--.  1 image-builder image-builder 902823936 Mar  7 10:19 rhel-8.7-x86_64-boot.iso
(does image-builder requires the full DVD (11GB) iso?)

image-builder build --os redhat --hypervisor baremetal --release-channel 1-24 --baremetal-config baremetal.json
....
make[1]: Entering directory '/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi'
Makefile:168: warning: undefined variable 'FOREGROUND'
Makefile:175: warning: undefined variable 'ON_ERROR_ASK'
Makefile:184: warning: undefined variable 'SSH_PRIVATE_KEY_FILE'
Makefile:188: warning: undefined variable 'SSH_PUBLIC_KEY_FILE'
Makefile:194: warning: undefined variable 'DEBUG'
hack/ensure-ansible.sh
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
hack/ensure-packer.sh
hack/ensure-goss.sh
Right version of binary present
packer build -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/config/kubernetes.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/config/cni.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/config/containerd.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/config/ansible-args.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/config/goss-args.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/config/common.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/config/additional_components.json"  -force -color=true -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi/packer/raw/raw-rhel-8.json" -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/_output/1-24/raw/ubuntu/config/kubernetes.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/_output/1-24/raw/ubuntu/config/common.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/_output/1-24/raw/ubuntu/config/cni.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/_output/1-24/raw/ubuntu/config/additional_components.json"  -var-file="/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/packer/config/baremetal.json"  packer/raw/packer.json
0 0
make[1]: Leaving directory '/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder/image-builder/images/capi'
make: Leaving directory '/home/image-builder/eks-anywhere-build-tooling/projects/kubernetes-sigs/image-builder'
2023/03/07 12:14:07 Moving artifacts from build directory to current working directory
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/aws/eks-anywhere-build-tooling/image-builder/builder.(*BuildOptions).BuildImage(0x993f40)
	github.com/aws/eks-anywhere-build-tooling/image-builder/builder/builder.go:254 +0x22c6
github.com/aws/eks-anywhere-build-tooling/image-builder/cmd.glob..func1(0x98b340?, {0x741289?, 0x8?, 0x8?})
	github.com/aws/eks-anywhere-build-tooling/image-builder/cmd/build.go:36 +0xb7
github.com/spf13/cobra.(*Command).execute(0x98b340, {0xc000220680, 0x8, 0x8})
	github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x98b5c0)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/aws/eks-anywhere-build-tooling/image-builder/cmd.Execute(...)
	github.com/aws/eks-anywhere-build-tooling/image-builder/cmd/root.go:24
main.main()
	github.com/aws/eks-anywhere-build-tooling/image-builder/main.go:10 +0x25

**What you expected to happen**: Image-builder to generate the rhel eks-a iso

**How to reproduce it (as minimally and precisely as possible)**: image-builder build --os redhat --hypervisor baremetal --release-channel 1-24 --baremetal-config baremetal.json

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.14
- EKS Distro Release: 1-24  (tried 1-25 same index of range error)

**Comment by abhay-krishna** [comment]
Hey @oraclefoo, thanks for filing this issue! Could you provide more logs from the image build? How long did the build take, did it fail with any errors before the `Moving artifacts from build directory to current working directory` log line. Were there any outputs like
```
Builds finished. The artifacts of successful builds are:
--
raw: VM files in directory: ./output/rhel-8-kube-v1.24.10.gz
raw: VM files in directory: ./output/rhel-8-kube-v1.24.10.gz
```
?

**Comment by oraclefoo** [comment]
[build.txt](https://github.com/aws/eks-anywhere/files/10942864/build.txt)

Hi - Attached is the output from 
nohup image-builder build --os redhat --hypervisor baremetal --release-channel 1-24 --baremetal-config baremetal.json

The failure occurs ~30 seconds. Tried as well in another directory under image-builder, i.e. $HOME/output. user image-builder can sudo. 

image-builder directory listing
[image-builder@brrhel8 ~]$ ll
total 881916
-rw-rw-r--.  1 image-builder image-builder       277 Mar 10 09:02 baremetal.json
drwxrwxr-x. 10 image-builder image-builder      4096 Mar 10 09:25 eks-anywhere-build-tooling
-rw-------.  1 image-builder image-builder    248529 Mar 10 09:17 nohup.out
drwxrwxr-x.  3 image-builder image-builder        57 Mar 10 09:18 output
-rw-r--r--.  1 image-builder image-builder 902823936 Mar  7 10:19 rhel-8.7-x86_64-boot.iso
drwx------.  3 image-builder image-builder        16 Mar  7 11:13 snap
drwxrwxr-x.  2 image-builder image-builder         6 Mar 10 09:25 tmp 

Is this correct in baremetal.json "iso_url": "file:///home/image-builder/rhel-8.7-x86_64-boot.iso" ? (tried also without the file// and same build error).

**Comment by oraclefoo** [comment]
One more note the documentation https://anywhere.eks.amazonaws.com/docs/reference/artifacts/#build-bare-metal-node-images steps refer to ubuntu. These are the steps I did for RHEL. Few of the packages from the documentation (e.g. cpu-checker libguestfs-tools) are not available from RHEL8 repo we subscribed.

sudo dnf update -y
sudo dnf -y install ipmitool jq make unzip python3 ansible-core qemu-kvm
sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
sudo yum -y install snapd
sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap
sudo snap install yq
sudo yum module install virt
sudo yum -y install virt-install virt-viewer

May be the missing packages on my install is causing the error.

**Comment by abhay-krishna** [comment]
Could you try setting `iso_url` to `https://redhat-iso-pdx.s3.us-west-2.amazonaws.com/8.4/rhel-8.4-x86_64-dvd.iso`, `iso_checksum` to `ea5f349d492fed819e5086d351de47261c470fc794f7124805d176d69ddf1fcd` and `extra_rpms` to `https://redhat-iso-pdx.s3.us-west-2.amazonaws.com/8.4/rpms/kmod-megaraid_sas-07.719.06.00_el8.4-1.x86_64.rpm`?
The log line `0 0` seems strange to me.

**Comment by abhay-krishna** [comment]
What is the version of Packer you're using on your system? Could you provide the output of the following:
1. `which packer`
2. `packer version`
3. `$(which packer) version`
4. `df -h`

**Comment by oraclefoo** [comment]
the error is related to packer. 
which packer
/usr/sbin/packer
sudo mv /usr/sbin/packer /usr/sbin/packer.bak
Got past the index out of range error. 
Should update the documentation to check packer for RHEL image-builder

**Comment by abhay-krishna** [comment]
Glad you were able get past the issue! Actually image-builder runs [this script](https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/hack/ensure-packer.sh) to ensure Packer (from Hashicorp) is installed on the machine, but seems like RHEL's packer had it confused. Alternatively, you can also build the RHEL raw image on that same Ubuntu server that you used to build Ubuntu raw images.

**Comment by oraclefoo** [comment]
yep running into packer issue regarding the qemu on RHEL - https://developer.hashicorp.com/packer/plugins/builders/qemu#qemu_binary qemu-kvm instead of qemu-system-x86_64  Thanks good to know that I can use the ubuntu image-builder to build RHEL eks-a image. Let me do that.

**Comment by abhay-krishna** [comment]
@oraclefoo Is there anything else that you need help with regarding the image build? Can I go ahead and close this issue?

**Comment by abhay-krishna** [comment]
I am closing this issue but please feel free to re-open it or create a new issue if something comes up. Cheers!
