### ISSUE TITLE
bare metal: creating management clusters with bottlerocket fails on hp test servers

### ISSUE THREAD

**Issue by chrisdoherty4** [aws/eks-anywhere#5247]
`main`, at time of writing, fails to provision management clusters on AWS HP testing servers.

Console output suggests the network stack isn't coming up. Initial verification of `net.toml` indicates it is correct.

**Comment by jacobweinstock** [comment]
this should be resolved via https://github.com/aws/eks-anywhere-build-tooling/pull/2185
