### ISSUE TITLE
Disable kube-vip component

### ISSUE THREAD

**Issue by whiterm** [aws/eks-anywhere#5308]
**What would you like to be added**:
I would like to disable the kube-vip component for the Tinkerbell provider. In the current implementation, there is no way to remove kube-vip from static pods.

**Why is this needed**:
In some cases, I cannot guarantee a layer 2 network for a cluster. But I can create my own load balancer for control plane nodes.

**Comment by chrisdoherty4** [comment]
Resolved by https://github.com/aws/eks-anywhere/pull/5641. The option first became available in v0.16.

Unfortunately, docs didn't get updated.
