### ISSUE TITLE
Use upstream Tinkerbell Helm chart

### ISSUE THREAD

**Issue by chrisdoherty4** [aws/eks-anywhere#5375]
**What would you like to be added**:

EKS-A uses an in-house Helm chart to deploy the Tinkerbell stack. Tinkerbell has its own Helm chart that is maintained and features a lot of flexibility that would simplify EKS-A code and reduce maintenance errors.

**Why is this needed**:

**Comment by ndeksa** [comment]
removed the tag FL-20,. This task would be part of Tink stack upgrade story, which will be covered in the OP2 item FL-3 [ release management story], need to be covered for v0.20

**Comment by ndeksa** [comment]
covered under [#1952](https://github.com/aws/eks-anywhere-internal/issues/1952)
