### ISSUE TITLE
Change to standard StorageClass storagePolicyName will fail the cluster upgrade

### ISSUE THREAD

**Issue by hainabc** [aws/eks-anywhere#5496]
**What happened**:

Default standard StorageClass is using "storagePolicyName=vSAN Default Storage Policy" parameter. This is not always suitable especially in case of vSphere cluster with no vSAN.

However, update to StorageClass parameters are forbidden. The standard StorageClass need to be re-created to change storagePolicyName.

This unfortunately will fail the upgrade process due to the same reason.

Error: failed to upgrade cluster: installing storage class during upgrade: installing storage class: executing apply: The StorageClass "standard" is invalid: parameters: Forbidden: updates to parameters are forbidden.

**What you expected to happen**:

Perhaps an option to use customized standard StorageClass instead of overwrite it during upgrade.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.15.0
- EKS Distro Release:

**Comment by jiayiwang7** [comment]
This is currently the expected behavior as we do not allow the mutability of StorageClass. We are thinking about getting rid of storage class as part of the EKS-A core workflow, instead letting users to install and manage storage class themselves.

**Comment by csplinter** [comment]
EKS-A no longer manages the vSphere CSI driver as of version v0.17. Please reference the [documentation](https://anywhere.eks.amazonaws.com/docs/clustermgmt/storage/vsphere-storage/) for details on the change.
