### ISSUE TITLE
EKS LoadBalancer?

### ISSUE THREAD

**Issue by WillNilges** [aws/eks-anywhere#550]
**What would you like to be added**: Will EKS Anywhere have the LoadBalancer functionality that normal EKS does? How can I use it? If not, will there be work done to enable it with MetalLB?

**Why is this needed**: Currently on local clusters, there doesn't seem to be any LoadBalancing functionality, and I'm trying to get MetalLB working with the Cilium network backend provided, with limited success.

**Comment by WillNilges** [comment]
I see that CIlium has some loadbalancing features that mention MetalLB. I'm investigating...

**Comment by abhinavmpandey08** [comment]
We have docs on using `kube-vip` and `metallb` LoadBalancers on EKS Anywhere https://anywhere.eks.amazonaws.com/docs/tasks/workload/loadbalance/

**Comment by WillNilges** [comment]
Thanks for the info! I must've missed it while I was reading the docs :facepalm: 
I see that `kube-vip` is the recommended LB to use.

**Comment by TerryHowe** [comment]
I've reopened this ticket to gauge interest in a bundled load balancer. Hit the thumbs up above if this functionality is of interest to you.

**Comment by TerryHowe** [comment]
I'm interested in kube-vip support

**Comment by TerryHowe** [comment]
I'm interested in metallb support

**Comment by DavidSpek** [comment]
For those that aren't aware of this, kube-vip supports load balancing both the control plane nodes in HA deployments as well as Service type `LoadBalancer`, whereas MetalLB can only provide load balancing for Service type `LoadBalancer`. Taking that into account I think kube-vip is the better choice as a bundled load balancer for production environments.

**Comment by madhu-liferay** [comment]
Is it possible to use a nginx ingress controller in EKSA ? i am trying in a local docker based eksa cluster

![image](https://user-images.githubusercontent.com/142578/152464829-389e0395-77c9-4b44-a2dc-9b62ca20d7a5.png)

https://anywhere.eks.amazonaws.com/docs/tasks/workload/test-app/
If you would like to expose your applications with an external load balancer or an ingress controller, you can follow the steps in [Adding an external load balancer](https://anywhere.eks.amazonaws.com/docs/tasks/workload/loadbalance/) .

**Comment by drewvanstone** [comment]
MetalLB is now a managed packaged.
