### ISSUE TITLE
Upgrading node os version 

### ISSUE THREAD

**Issue by or9327** [aws/eks-anywhere#5500]
**What would you like to be added**: Upgrading Node OS version
 
**Why is this needed**: To deploy K8S cluster on latest OS  (ex. Ubuntu 22.04 rather than 20.04)

**Comment by csplinter** [comment]
Support for Ubuntu 22.04 planned for EKS-A v0.17 release

**Comment by csplinter** [comment]
Support for Ubuntu 22.04 was released in EKS-A version v0.17 (see [Changelog](https://anywhere.eks.amazonaws.com/docs/whatsnew/changelog))
