### ISSUE TITLE
Remove CSI and storage class management from EKS-A for vSphere provider

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#5517]
Currently we have a specific storage class installed here https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/defaultStorageClass.yaml which is not flexible, as well as unnecessary management of a driver that is not required for running a cluster. So we want to remove it from the EKS Anywhere create/upgrade flow so users can manage CSI on their own if they require it, with an implementation for VSphere listed [here](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/2.0/vmware-vsphere-csp-getting-started/GUID-C44D8071-85E7-4933-83EA-6797518C1837.html).

**Comment by drewvanstone** [comment]
We are going to no longer install the CSI driver by default and will issue a warning that it will be removed in an upcoming release. This issue is being moved to the 0.17 release

**Comment by vivek-koppuru** [comment]
With #5918, we will give a warning to all our users when `disableCSI` is set to `false` or not specified to tell them to switch to managing their CSI driver and StorageClass on their own if they require it.
