### ISSUE TITLE
Add retries for taking management cluster backup command during upgrade

### ISSUE THREAD

**Issue by panktishah26** [aws/eks-anywhere#5576]
**What would you like to be added**:
We have added a feature to take the backup of management cluster's resources before moving it to kind cluster during an upgrade of a management cluster. We should add retries for that command to make backup process more robust.

**Comment by robbierafay** [comment]
How about auto restore on operation failure as well ? Since eksctl upgrade is also used for operations such as scaling nodes, this becomes quite problematic if scaling operation fails
