### ISSUE TITLE
Need advice on vsphere version for eksanywhere

### ISSUE THREAD

**Issue by sagarkundral24** [aws/eks-anywhere#561]
Hi there,
I am planning to install eksanywhere using VMware vphere and after going through the prerequisites, I saw the vsphere version needs to 7+ however we are using version 6.7 in our environment. Please let me know if version 6.7 will work or its mandatory to go with version 7 or higher

https://anywhere.eks.amazonaws.com/docs/reference/vsphere/vsphere-prereq/

**Comment by panktishah26** [comment]
Hi @sagarkundral24,

We have successfully tested EKS Anywhere on vSphere 7.0+. You can still run our binary on 6.7 U3 or above but it is not supported. Which vSphere version is your team using?

**Comment by sagarkundral24** [comment]
Thanks. We are using below version

vSphere Client version 6.7.0.42000
