### ISSUE TITLE
Prow job linter should also validate env vars

### ISSUE THREAD

**Issue by vignesh-goutham** [aws/eks-anywhere#565]
**What would you like to be added**:
Our presubmits prowjobs have a linter which validates a lot of variables on the job definition like service account, make target, etc. It would be good value add, if we can validate the env vars as well.

**Why is this needed**:
This prevents from checking in, undesirable env variables that would not work for the prow job. An example would be a wrong bucket name for `ARTIFACTS_BUCKET` env.

**Comment by gwesterfieldjr** [comment]
I'm gonna take a stab at this one :)

**Comment by gwesterfieldjr** [comment]
@vignesh-goutham @abhay-krishna please close when you get a chance. Thank you!
