### ISSUE TITLE
Tinkerbell provider Regression in older hardwares

### ISSUE THREAD

**Issue by mitalipaygude** [aws/eks-anywhere#5682]
Regression seen in older hardware like Dell R640s from v0.15.0 for Tinkerbell providers. BMC timeouts observed.

**Comment by jacobweinstock** [comment]
FYI, a short term fix was implemented here https://github.com/aws/eks-anywhere-build-tooling/pull/2116 and is in the v0.15.3 release https://github.com/aws/eks-anywhere/releases/tag/v0.15.3. 

There is in progress work for a longer term solution. Along with these we still need to update Rufio to the latest bmclib version and then update eks-anywhere-build-tooling.
https://github.com/tinkerbell/rufio/pull/87
https://github.com/tinkerbell/rufio/pull/85
https://github.com/bmc-toolbox/bmclib/pull/322

**Comment by jacobweinstock** [comment]
build-tooling PR to update Rufio. https://github.com/aws/eks-anywhere-build-tooling/pull/2170

**Comment by jacobweinstock** [comment]
build-tooling repo PR merged. https://github.com/aws/eks-anywhere-build-tooling/pull/2170
