### ISSUE TITLE
Add Timeout to Cluster Lifcycle Delete Calls in e2e Tests

### ISSUE THREAD

**Issue by jonathanmeier5** [aws/eks-anywhere#5690]
We are seeing the following tests timing out:

```
TestVSphereKubernetes123to124UpgradeFromLatestMinorReleaseBottleRocketAPI
TestVSphereUpgradeKubernetesUbuntuAPI
TestVSphereUpgradeKubernetesCiliumDisableCSIUbuntuAPI
```

this is due to no timeout being applied to the kubectl call deleting a workload cluster resource [here](https://github.com/aws/eks-anywhere/blob/5fb16d2fd0bc960e7c4609c5b44cf0991194e863/test/framework/workload.go#L49-L49).

Additionally, we will rename `TestVSphereUpgradeKubernetesUbuntuAPI`->`TestVSphereUpgradeKubernetes123to124UbuntuWorkloadClusterAPI` to specify the tests function better in its name.

With this timeout configured, all tests should be removed from the [skip list](https://github.com/aws/eks-anywhere/blob/5fb16d2fd0bc960e7c4609c5b44cf0991194e863/test/e2e/SKIPPED_TESTS.yaml#L1-L1). This way we will see failures but they will not draw out the test execution.

**Comment by tatlat** [comment]
PR to add the timeout: https://github.com/aws/eks-anywhere/pull/5689
