### ISSUE TITLE
Tool to uninstall default Cilium CNI

### ISSUE THREAD

**Issue by chrisdoherty4** [aws/eks-anywhere#5705]
## Summary

When users enable the `skipUpgrade` flag for the Cilium CNI installation they inevitably want to uninstall the default Cilium CNI shipped with EKS-A. The Cilium CLI happens to work well for this purpose but there are no defined contracts between EKS-A and the Cilium CLI that ensure compatibility. 

Customers, alternatively, may attempt to uninstall the default Cilium CNI with a rather long `kubectl delete` command. If they inadvertently miss an object it can have undesirable consequences including borking of a cluster (typically when they try to install another Cilium version).

Given EKS-A is the authority for the default Cilium CNI installation, it would be beneficial to provide a tool that can uninstall the CNI.

**Comment by tuxtof** [comment]
#6337 it become mandatory to provide a tool that can uninstall the CNI
