### ISSUE TITLE
Provide a validation method for customer to validate the eks-a admin AMI

### ISSUE THREAD

**Issue by cmengtin** [aws/eks-anywhere#5708]
**What would you like to be added**:  It would be helpful to add some information in the release note for customers to validate if they download the complete raw file given eks-a admin ami is pretty big. We can use md5sum command like following:
```
$ md5sum eks-anywhere-admin-ami-v0.14.2-eks-a-29.raw
c29a5b8819cacf242a75ff7296ada540 eks-anywhere-admin-ami-v0.14.2-eks-a-29.raw
```
When you provide the md5sum value of the raw file, customers can check the md5sum value of their raw file they download.

**Why is this needed**: Some customers met this issue and they couldn't use the eks-a admin AMI as expected. We spent some time to figure out the reason and found the root cause is that they downloaded an incomplete file.

**Comment by abhay-krishna** [comment]
This is a valid ask, we can upload the shasum file of the admin ami also to S3, which can be pulled by customers from `<admin AMI URL>.sha256`
