### ISSUE TITLE
Add support for GitLab Project Access Tokens just like is currently in use for GitHub

### ISSUE THREAD

**Issue by snowkiterdude** [aws/eks-anywhere#5714]
**What would you like to be added**:

There is currently GitOps Cluster Management support for GitHub which allows the use of Project Access Tokens. Flux already supports this functionality for GitLab but it still needs to be added to eks-anywhere.

**Why is this needed**:

When I leave my current company their automation will disable my user and therefore my personal ssh keys. GitLab does not support ssh keys on a project basis. Therefore when I leave our management clusters will lose the ability to fetch git resources stopping our GitOps Cluster Management pipelines.

**Comment by Cajga** [comment]
Hi,

This feature would be nice.

Actually, gitlab do have [deploy keys](https://docs.gitlab.com/ee/user/project/deploy_keys/) on the project level which can be used for this purpose. We have been using that with EKS-A for quite long time.

**Comment by snowkiterdude** [comment]
Ah Ha, Thanks @Cajga
