### ISSUE TITLE
 eksctl anywhere download images -o image.tar 

### ISSUE THREAD

**Issue by neutron11** [aws/eks-anywhere#5716]
failed with Error: downloading chart [public.ecr.aws/eks-anywhere/eks-anywhere-packages:0.3.9-eks-a-36] from registry: Error: failed to do request: Head "https://public.ecr.aws/v2/eks-anywhere/eks-anywhere-packages/manifests/0.3.9-eks-a-36": x509: certificate signed by unknown authority

eksctl anywhere version
v0.15.2

**Comment by TerryHowe** [comment]
I moved this because packages doesn't actually use `download images`

**Comment by TerryHowe** [comment]
Error is from https://github.com/aws/eks-anywhere/blob/main/pkg/helm/download.go#L36

**Comment by TerryHowe** [comment]
The `download images` doesn't seem to support a ca-cert option I assume because it is expect that it is downloading from AWS and the certs would be trusted.

**Comment by neutron11** [comment]
> The `download images` doesn't seem to support a ca-cert option I assume because it is expect that it is downloading from AWS and the certs would be trusted.

Much appreciated!

**Comment by neutron11** [comment]
Certs issue as you pointed to .    Work around is to add a flag --insecure

**Comment by abhay-krishna** [comment]
Closing as resolved.
