### ISSUE TITLE
Building bare metal ubuntu images does not work anymore

### ISSUE THREAD

**Issue by Cajga** [aws/eks-anywhere#5723]
**What happened**: Due to the lack of CSI solution compatibility in Bottlerocket, we are building our own Ubuntu images following the procedure described in the [documentation](https://anywhere.eks.amazonaws.com/docs/reference/artifacts/#build-bare-metal-node-images).
We have successfully built many images with the same procedure in the past (last successful build was for the 1-25 release channel on the 12th of April).
But now, the build procedure fails to build an ubuntu image with the following error message during ansible run (tested both for release-channel 1-25 and for 1-26 and both are failing):
```
    qemu: TASK [containerd : download containerd] ****************************************
    qemu: fatal: [default]: FAILED! => {"changed": false, "checksum_dest": null, "checksum_src": null, "dest": "/tmp/containerd.tar.gz", "elapsed": 0, "msg": "The checksum format is invalid", "url": "null"}
    qemu:
    qemu: PLAY RECAP *********************************************************************
    qemu: default                    : ok=21   changed=16   unreachable=0    failed=1    skipped=182  rescued=0    ignored=0
    qemu:
==> qemu: Provisioning step had errors: Running the cleanup provisioner, if present...
==> qemu: Deleting output directory...
Build 'qemu' errored after 13 minutes 3 seconds: Error executing Ansible: Non-zero exit status: exit status 2
```

Full output is here:
https://gist.github.com/Cajga/80e27cc65f4067d0dca2c116cad24104

**What you expected to happen**:
Image builder procedure works.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the documentation to build a bare metal ubuntu image.

**Environment**:
- EKS Anywhere Release: 0.15.2
- EKS Distro Release: 1.26
- image builder version:
```
image-builder@eks-a-image-builder:~$ image-builder version
0.1.2
```

**Comment by abhay-krishna** [comment]
Thanks for opening this issue! We recently made a change to the source of `containerd` tarball included in the image builds. Earlier we were depending on GitHub releases but now we're building our own `containerd` and baking it into the images. The change to incorporate this change went into the main branch but not the release-0.15 branch, so the containerd URL is getting set to null. We will fix this.

**Comment by dashkan** [comment]
@Cajga we too are affected by this. We require NFS driver which did not work in bottlerocket. [Looks like bottlerocket now supports CSI driver](https://github.com/bottlerocket-os/bottlerocket/issues/1225). I validated that [NFS CSI driver](https://github.com/kubernetes-csi/csi-driver-nfs) does work in EKSA with bottlerocket images now.

**Comment by abhay-krishna** [comment]
@Cajga @dashkan could you try running the image build again? We put in a temp fix at aws/eks-anywhere-build-tooling#2134.

**Comment by dashkan** [comment]
@abhay-krishna I was able to build ubuntu 1.26 image. Thank you for the quick fix...

**Comment by Cajga** [comment]
@abhay-krishna I can also confirm that the build no longer fails for ubuntu image for the 1-26 channel. Thanks for your support.
