### ISSUE TITLE
Add VMware permissions validation in the upgrade workflow

### ISSUE THREAD

**Issue by taneyland** [aws/eks-anywhere#5757]
Users want a way to validate VMWare permissions before attempting operations. We already added this for the create workflow in EKS-A v0.11.2 (PR- https://github.com/aws/eks-anywhere/pull/2907). We should add these same validations for upgrades too.

**Comment by csplinter** [comment]
Is this just a miss from #2907 ?

**Comment by taneyland** [comment]
> Is this just a miss from #2907 ?

Talked with @jonathanmeier5 offline, and yes I believe you are correct. We already added this in 0.11.2 for the create workflow. So I believe we will just have to add the same validations for upgrades.
