### ISSUE TITLE
EKSA Support Bundle for airgap/offline Clusters

### ISSUE THREAD

**Issue by saiteja313** [aws/eks-anywhere#5783]
**What would you like to be added**:

- I have a EKS Anywhere cluster that do not have access to internet. I cannot run EKSA Support bundle against my cluster as it tries to reach out for external endpoints. 

```
eksctl anywhere generate support-bundle -f cluster.yaml
```

```
error from support-bundle in offline cluster version v0.7.2 which i know does not support generating support-bundle
eksctl anywhere generate support-bundle -f bll-eksa-mgmt-stg-cmp/bll-eksa-mgmt-stg-cmp-eks-a-cluster.yaml
Error: failed to create support bundle: unable to get cluster config from file: failed reading file from url [https://anywhere-assets.eks.amazonaws.com/releases/eks-a/manifest.yaml ]: Get "https://anywhere-assets.eks.amazonaws.com/releases/eks-a/manifest.yaml ": dial tcp: lookup anywhere-assets.eks.amazonaws.com : no such host
```

**Why is this needed**:

- Customers with airgap/offline EKSA Cluster environment are not able to upload bundle logs to AWS Support Console. This is causing delay in troubleshooting customer cases and leading to increase in case analysis time.

**Comment by 2ez4szliu** [comment]
I think one way to fix this, just like `--bundle-config`, we can pass a local release manifest to eksctl so that eks-a does not need to fetch it from a remote url

**Comment by sp1999** [comment]
As of EKS-A [v0.20.6](https://github.com/aws/eks-anywhere/releases/tag/v0.20.6), customers can now generate the support bundle for their clusters in an airgapped env with the `--bundles-manifest` flag.
Documentation Reference:- https://anywhere.eks.amazonaws.com/docs/clustermgmt/support/supportbundle/#collecting-a-support-bundle-and-running-analyzers
