### ISSUE TITLE
upgrade eksctl-anywhere   question

### ISSUE THREAD

**Issue by danielem37** [aws/eks-anywhere#5844]
eksctl 0.76.0
eksctl-anywhere v0.7.2
os:ubuntu
I tried upgrading eksctl-anywhere to v0.15.3 from v0.7.2  i understand that this is not possible and have to upgrade to next release ....
I what to get to latest with minimum no. of upgrades also have constraint of being in air-gaped environment.is it possible?
also i tried upgrading to v0.8.2 but can't download the ubuntu.ova accessed denied is there a archive where version can be download if i have to upgrade 8,9,10 ?

**Comment by chrisdoherty4** [comment]
Hi @danielem37. We require users to upgrade incrementally so you can't skip straight to 0.15. With respect to Ubuntu, we stopped vending the images some time ago so you'll need to build and host them (see https://anywhere.eks.amazonaws.com/docs/reference/artifacts/#building-node-images).

I'm closing the issue but feel free to continue asking questions.

**Comment by danielem37** [comment]
I know you stop vending images and from v0.11 start using image builder
I have built images  but I can not upgrade using them
So want you saying is all images from 8-10 are not available even in
archives?
