### ISSUE TITLE
Better representing CLI version and dependencies in EKS-A cluster

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#5847]
The relationship between an EKS-A release and its corresponding bundle is not clear. Furthermore, it is difficult to tell what version of EKS-A was used to create/upgrade a cluster. For these reasons, the bundlesRef field of a cluster should be deprecated in favor of an eksaVersion field. The eksaVersion field should map to an EKSARelease resource on the cluster, which can contain a reference of the release's corresponding bundle.

**Comment by tatlat** [comment]
Implemented in https://github.com/aws/eks-anywhere/pull/6262 and https://github.com/aws/eks-anywhere/pull/6268
