### ISSUE TITLE
Emissary Curated Package docs needs review and testing

### ISSUE THREAD

**Issue by raykrueger** [aws/eks-anywhere#5859]
**What happened**:

Using the Emissary Ingress documentation, several errors are noted.
https://anywhere.eks.amazonaws.com/docs/tasks/workload/ingress/

(Step 2) MetalLB should not be required ( kubectl port-forward can be used for demonstration/testing)
(Step 4) http-listener is using `protocol: HTTPS`
(Step 5) hostname in the spec is not required `hostname: "195.16.99.65"`, even if we are using MetalLB here hostname is not required. Hostname is required if the intent is to use hostname based routing (ex: app1.example.com vs app2.example.com)
(Step 6 & 7) The service name in step 6 is wrong, so step 7 won't work

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by ivyostosh** [comment]
Thanks for bringing up this issue. We will test those steps and make updates to the doc accordingly.

**Comment by lewisdiamond** [comment]
> (Step 4) http-listener is using protocol: HTTPS

This is expected with security model `XFP`. Emissary will map HTTPS request with `X-Forwarded-Proto` 

> The X-Forwarded-Proto header mentioned above is meant to reflect the protocol the original client used to contact Emissary-ingress. When no layer 7 proxies are in use, Envoy will make certain that the X-Forwarded-Proto header matches the wire protocol of the connection the client made to Envoy, which allows Emissary-ingress to trust X-Forwarded-Proto for routing decisions such as deciding to redirect requests made using HTTP over to HTTPS for greater security. When using Emissary-ingr

from https://www.getambassador.io/docs/emissary/latest/topics/running/listener
