### ISSUE TITLE
Create a section for troubleshooting/help articles

### ISSUE THREAD

**Issue by vivek-koppuru** [aws/eks-anywhere#5866]
We need to have a section in our official documentation, anywhere.eks.amazonaws.com, to have troubleshooting guides and docs. We currently have https://anywhere.eks.amazonaws.com/docs/tasks/troubleshoot/troubleshooting/ but it doesn't capture complex steps as shown in the following articles. 

https://repost.aws/knowledge-center/eks-anywhere-check-component-logs
https://repost.aws/knowledge-center/eks-anywhere-etcdadm-controller-issues
https://repost.aws/knowledge-center/eks-anywhere-return-cluster-upgrade-fail
https://repost.aws/knowledge-center/eks-clean-up-resources-failed-cluster
https://repost.aws/knowledge-center/eks-anywhere-bootstrapping-process

**Comment by chrisnegus** [comment]
The PR adds a link to [How do I clean up EKS Anywhere resources without eksctl when cluster creation fails?](https://repost.aws/knowledge-center/eks-clean-up-resources-failed-cluster) in the beginning of the Troubleshooting guide. So I'll close [Issue 6101](https://github.com/aws/eks-anywhere/issues/6101) as well when this PR merges.

**Comment by chrisnegus** [comment]
This [PR #7068](https://github.com/aws/eks-anywhere/pull/7068) resolves this issue.
