### ISSUE TITLE
EKS-A Conformitron Validated Partners Listing in AWS EKS-A Documentation

### ISSUE THREAD

**Issue by elamaran11** [aws/eks-anywhere#5881]
Currently EKS-A Conformance framework (Conformitron) reports all validated Partners automatically in [GitHub Repo](https://github.com/aws-samples/eks-anywhere-addons/tree/main/Validated_Partners) across all EKS-A deployment models such as vSphere, BM, Snow, EKS On Outpost, Nutanix. We would need to refresh our EKS-A docs to reflect list of AWS validated partners using Conformance framework (Conformitron) across different EKS Deployment models.

Appreciate if this can be prioritized to be added to AWS documentation

**Comment by csplinter** [comment]
Resolved by #6565
