### ISSUE TITLE
`--kubeconfig` not honored with `upgrade cluster` command

### ISSUE THREAD

**Issue by jacobweinstock** [aws/eks-anywhere#5905]
**What happened**:
When running `upgrade cluster` the `--kubeconfig` flag is not honored and the process fails.

```bash
$ ./eksctl-anywhere upgrade cluster -z hardware.csv -f bottlerocket.yaml --kubeconfig ./management-cluster.kubeconfig -v12
2023-05-23T17:52:49.602Z	V6	Executing command	{"cmd": "/usr/bin/docker version --format {{.Client.Version}}"}
2023-05-23T17:52:49.664Z	V6	Executing command	{"cmd": "/usr/bin/docker info --format '{{json .MemTotal}}'"}
Error: failed to upgrade cluster: common validations failed due to: validating kubeconfig "bottlerocket/bottlerocket-eks-a-cluster.kubeconfig": file does not exist
```

**What you expected to happen**:
The upgrade command should honor the `--kubeconfig` flag.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a management cluster
2. Move the kubeconfig to a new location
3. run a cluster upgrade specifying the location of the management kubeconfig with `--kubeconfig`

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by ddjjia** [comment]
- bug fixed by https://github.com/aws/eks-anywhere/pull/6666
- to deprecate `wconfig` and get wl kubeconfig from mgmt cluster https://github.com/aws/eks-anywhere/issues/6598 
- to remove wconfig flag https://github.com/aws/eks-anywhere/issues/6673
