### ISSUE TITLE
EKSA CLI Pre-flight validation for AWS authentication issues

### ISSUE THREAD

**Issue by saiteja313** [aws/eks-anywhere#6000]
**What would you like to be added**:

- Post creation of EKSA Cluster, we were not able to deploy Emissary Curated Packages to Workload clusster, due to authentication issue with AWS API's.
- Root cause was that AWS CLI Secret Access key was incorrect.

**Why is this needed**:
- Curated Packages is feature supported for License Paying customers. EKSA command line should add details when CLI fails with authentication issues for AWS API endpoint.

**Comment by vincentni** [comment]
Thanks for reporting that. Did you set up environment variables `EKSA_AWS_SECRET_ACCESS_KEY`, `EKSA_AWS_ACCESS_KEY_ID` and `EKSA_AWS_REGION` when you were creating the cluster?  You can refer to [our doc](https://anywhere.eks.amazonaws.com/docs/packages/prereq/) for details.
