### ISSUE TITLE
Remove cron-ecr-renew not found log in package controller.

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#6142]
This error is found in the package controller:

Package           failed to Update Secret in all namespaces          {"error": "cronjobs.batch \"cron-ecr-renew\" not found"} 

The cronjob is no longer needed or installed in the most recent versions of EKS-A, but the log persists and is misleading.

**Comment by jonahjon** [comment]
https://github.com/aws/eks-anywhere-packages/pull/963
