### ISSUE TITLE
Parsing of multi yaml files in a better way

### ISSUE THREAD

**Issue by HiteshRepo** [aws/eks-anywhere#6306]
**What happened**:
This change request is in line with #6095 .
There are various places where multi-yaml files containing resource configs are being split using string separator '---'.
This might lead to error when certificate deatils are provided in field like `registryMirror` or `certBundles`.
The locations where these string separator based handling of multi resource config yamls are:
- https://github.com/aws/eks-anywhere/blob/92f511982e8ae4d78bde85c42921d4e54ff14370/pkg/api/v1alpha1/cloudstackmachineconfig.go#L73
- https://github.com/aws/eks-anywhere/blob/92f511982e8ae4d78bde85c42921d4e54ff14370/pkg/api/v1alpha1/cluster.go#L285
- https://github.com/aws/eks-anywhere/blob/92f511982e8ae4d78bde85c42921d4e54ff14370/pkg/api/v1alpha1/nutanixmachineconfig.go#L129
- https://github.com/aws/eks-anywhere/blob/92f511982e8ae4d78bde85c42921d4e54ff14370/pkg/api/v1alpha1/tinkerbellmachineconfig.go#L64
- https://github.com/aws/eks-anywhere/blob/92f511982e8ae4d78bde85c42921d4e54ff14370/pkg/api/v1alpha1/tinkerbelltemplateconfig.go#L75
- https://github.com/aws/eks-anywhere/blob/92f511982e8ae4d78bde85c42921d4e54ff14370/pkg/api/v1alpha1/vspheremachineconfig.go#L63

**What you expected to happen**:
Expectation is to handle the multi resource config yamls in a better way as done in #6095 

**Anything else we need to know?**:
A PR has been raised for the mentioned change: #6170

**Comment by chrisdoherty4** [comment]
Issue is resolved through https://github.com/aws/eks-anywhere/pull/6095 and https://github.com/aws/eks-anywhere/pull/6170.
