### ISSUE TITLE
Cilium uninstall don't work with cilium cli 0.15.x

### ISSUE THREAD

**Issue by tuxtof** [aws/eks-anywhere#6337]
**What happened**:

Starting Cilium CLI v0.15.0, cilium uninstall on an eks-a cluster failed with error

```
> cilium uninstall
🔥 Deleting pods in cilium-test namespace...
🔥 Deleting cilium-test namespace...

Error: Unable to uninstall Cilium:  uninstall: Release not loaded: cilium: release: not found
```

**What you expected to happen**:

cilium need to uninstall succesfully or we need to specify in doc which cilium version is supported

**How to reproduce it (as minimally and precisely as possible)**:

follow procedure here https://anywhere.eks.amazonaws.com/docs/clustermgmt/networking/cluster-replace-cilium/#add-a-custom-cni-to-a-new-cluster by using the last cilium cli (v0.15.4 for exemple)

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: 0.16.2
- EKS Distro Release: v1.26.6-eks-3316523
- Cilium CLI: 0.15.4

**Comment by Cajga** [comment]
Hi @tuxtof, this will affect us as well. I am curious if it would be a good practice to use a cilium cli which has a similar version then the installed one for the uninstallation. Have you by chance tested that?

**Comment by tuxtof** [comment]
yes based on this table
https://github.com/cilium/cilium-cli#releases

i have used v0.14.8 succesfully to uninstall

but majority of installer install last version , that's why i create this issue

**Comment by Cajga** [comment]
Fully agree. I just wanted to make sure that this is not a regression in latest eks-a (we did the uninstall on an older version of eks-a)

**Comment by tuxtof** [comment]
@Cajga by curiosity which CNI did you use in place ?

**Comment by Cajga** [comment]
Cilium community :)

**Comment by tuxtof** [comment]
ok a more recent one :-D

**Comment by Cajga** [comment]
That it not the real reason... The bundled Cilium has many limitations (no cilium CRDs, no hubble, native network policies are limited by cilium implementation, no host firewall etc.)... You can find many  tickets (some of them were openeb by me) among the issues realted to these.

**Comment by tuxtof** [comment]
good to know thanks @Cajga
