### ISSUE TITLE
[EPIC] Support air gapped image building

### ISSUE THREAD

**Issue by vignesh-goutham** [aws/eks-anywhere#6457]
Image-builder only supports building an OS in an environment with internet access or have proxy setup. This feature request is to enable building images in an air-gapped environment.

Image builder should be able to use artifacts hosted in a private/internal endpoint for image building. In addition to this, image-builder can also provide a download command that will pull all the required artifacts from public internet to local filesystem, which users can later use to import to private hosting.

**Comment by jacobweinstock** [comment]
working on identifying items that get pulled from the internet.

**Comment by jacobweinstock** [comment]
Need an internal Artifactory instance stood up in the DC.

**Comment by jacobweinstock** [comment]
This is a parent ticket for this work
