### ISSUE TITLE
Upgrade eksctl anywhere CLI version

### ISSUE THREAD

**Issue by Swalloow** [aws/eks-anywhere#6582]
I couldn't find CLI upgrade documentation.
How to upgrade eksctl anywhere CLI 0.11 to 0.17 version?
Will the update affect the existing cluster?
<br>

**Environment:**

- EKS Anywhere Release: v0.11.4
- EKS Distro Release: v1.23.9

**Comment by vivek-koppuru** [comment]
We talk about the CLI upgrades here: https://anywhere.eks.amazonaws.com/docs/clustermgmt/cluster-upgrades/vsphere-and-cloudstack-upgrades/#eks-anywhere-version-upgrades

We recommend upgrading the cluster by going one minor version at a time. If you are upgrading the workload clusters, it won't upgrade the management clusters. We addressed unintentional workload cluster upgrades when the management cluster is being upgraded in v0.11.4.

When you mention affecting the existing cluster, what do you mean by that? When you perform any upgrade, it will roll out new nodes only if there are changes in the EKS Anywhere cluster spec when you are performing that upgrade.

**Comment by Swalloow** [comment]
I mean how upgrades would affect the Workload cluster resource. (machines, nodes, pods, etc..)
Thanks for sharing the docs. I will try it.
