### ISSUE TITLE
Bare Metal: Machine configs can be changed to existing machine configs

### ISSUE THREAD

**Issue by chrisdoherty4** [aws/eks-anywhere#6633]
**Summary**
We block changing the machine config references for control planes and worker node groups on bare metal clusters. However, its possible to change references to existing machine configs. For example, I can change the control plane machine config reference to an existing worker node group machine config.

**Comment by jacobweinstock** [comment]
Open PR. https://github.com/aws/eks-anywhere/pull/6674
