### ISSUE TITLE
Create E2E tests for control plane only clusters

### ISSUE THREAD

**Issue by chrisdoherty4** [aws/eks-anywhere#6660]
**Summary**

Users can create clusters that contain only control plane nodes. Control plane only clusters are clusters composed of nodes that do not have control plane taints meaning workloads can run on any node and every node has an API server.

Historically, these clusters have been called single node as its the most common use-case, however we also support multi node control plane only clusters. We do not have E2E tests to validate this kind of cluster, yet we've found associated bugs (#6614).

**Task**

Create a suite of tests that target single and multi node control plane only clusters.

**Comment by ndeksa** [comment]
single node tests/CI already been added!
