### ISSUE TITLE
Failed to create cluster: failed to lock config file: permission denied

### ISSUE THREAD

**Issue by LowriKate** [aws/eks-anywhere#6678]
**What happened**:

When i try to use create a cluster using this command

`eksctl anywhere create cluster -f ./dev.yaml`

 I get this error 

`ERROR: failed to create cluster: failed to lock config file: open dev/generated/dev.kind.kubeconfig.lock: permission denied `

Full terminal response: 

`Performing setup and validations
Warning: The docker infrastructure provider is meant for local development and testing only
✅ Docker Provider setup is valid
✅ Validate OS is compatible with registry mirror configuration
✅ Validate certificate for registry mirror
✅ Validate authentication for git provider
✅ Validate cluster's eksaVersion matches EKS-A version
Creating new bootstrap cluster
Error: creating bootstrap cluster: executing create cluster: Creating cluster "dev-eks-a-cluster" ...
 • Ensuring node image () 🖼  ...
 ✓ Ensuring node image () 🖼
 • Preparing nodes 📦   ...
 ✓ Preparing nodes 📦 
 • Writing configuration 📜  ...
 ✓ Writing configuration 📜
 • Starting control-plane 🕹️  ...
 ✓ Starting control-plane 🕹️
 • Installing CNI 🔌  ...
 ✓ Installing CNI 🔌
 • Installing StorageClass 💾  ...
 ✓ Installing StorageClass 💾
ERROR: failed to create cluster: failed to lock config file: open dev/generated/dev.kind.kubeconfig.lock: permission denied`

**What you expected to happen**:

I would expect that a cluster is successfully created.

**How to reproduce it (as minimally and precisely as possible)**:

Followed the guidance here to install eks anywhere https://anywhere.eks.amazonaws.com/docs/getting-started/install/ 

I run the command `eksctl anywhere create cluster -f ./dev.yaml`

I have tried this before and after the command `export KUBECONFIG=$PWD/eksa/dev/dev-eks-a-cluster.kubeconfig`

I have also tried using the default ${HOME}/.kube/config location. 

I have also tried adding the flag --kubeconfig=$KUBECONFIG and --kubeconfig /path/to/folder

I have checked permissions on the folder and can't see that i lack permission.

I have tried doing the command as sudo. 

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.17.2
- Docker version 24.0.5

**Comment by abhay-krishna** [comment]
Hey @LowriKate, thanks for tying out EKS Anywhere and for reporting this issue! This seems to be an environment-specific problem that could occur if your current user does not have permissions to the location that `kind` writes the kubeconfig file to. This issue has been logged in Kind as well, refer to kubernetes-sigs/kind#2008 for possible fixes to your environment.

**Comment by abhay-krishna** [comment]
Could you provide permissions of  the folder you're trying to run EKS-A from?

**Comment by LowriKate** [comment]
Thanks for linking the issue logged in Kind. I had tried these fixes and unfortunately wasn't able to fix my issue. The permissions for the folder where i'm trying to run EKS-A from are: drwxr-xr-x

**Comment by nickolaev** [comment]
Had the same issue on OSX (M1). Changed my Docker desktop to use `gRPC FUSE` instead of `VirtioFS` and everything is working again.

**Comment by chrisdoherty4** [comment]
Issue reproducible on an M2 chip also. Seems to be environment specific. I also switched to gRPC Fuse and everything worked again. Seems like this should be reported in the Docker repos.
