### ISSUE TITLE
Add backup and restore strategy of failed cluster in doc site

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#6767]
In certain unfortunate circumstances, an EKS Anywhere cluster may find itself in an unrecoverable state due to various factors such as a failed cluster upgrade, underlying infrastructure problems, or network issues, rendering the cluster inaccessible through conventional means. We need documents that outline detailed steps to guide user through the process of restoring a failed cluster from backups in these critical situations.

**Comment by sharmadinesha** [comment]
Hello Joey, we do see this issue created a month back, seems we are also stuck in a similar situation , where we wish to take a backup of a bottlerocket nodes and restore it say in case when the nodes are not reachable nor the cluster.  Is there any update on the documentation for the same !

**Comment by jiayiwang7** [comment]
> Hello Joey, we do see this issue created a month back, seems we are also stuck in a similar situation , where we wish to take a backup of a bottlerocket nodes and restore it say in case when the nodes are not reachable nor the cluster. Is there any update on the documentation for the same !

Hello the doc site is updated with instruction. Please take a look and give it a try: https://anywhere.eks.amazonaws.com/docs/clustermgmt/cluster-backup-restore/
