### ISSUE TITLE
Refactor cluster controller builds

### ISSUE THREAD

**Issue by abhay-krishna** [aws/eks-anywhere#696]
The cluster controller build logic needs a bit of cleanup as it is invoked by a make target that invokes a script that invokes another make target.

**Comment by gwesterfieldjr** [comment]
@abhay-krishna , I'm excited to get involved in the project. This task seemed like a good one to get started so I figured I would take a stab at it. I look forward to your review.

cc: @danbudris @ndeksa

**Comment by abhay-krishna** [comment]
This has been addressed in #710. Thanks @gwesterfieldjr! 🎉
