### ISSUE TITLE
Possibility to use KVM+Firecraker/Ignite

### ISSUE THREAD

**Issue by rverma-nsl** [aws/eks-anywhere#700]
**What would you like to be added**:
I understood that aws team is not inclined to support KVM at this stage. But I want to highlight that Firecracker can further help the users to narrow the gap between cloud and onprem offering and help to implement something like EKS-Fargate-Anywhere. 
Further restricting to vshpere is not a good strategy, there should be some low-cost/open-source support too.

**Why is this needed**:
On-prem serverless. Community tooling.

**Comment by mdsgabriel** [comment]
Hello @rverma-nsl ,
Thanks for the suggestion!  I've added a thumbs up to track interest.
