### ISSUE TITLE
Update `podIamConfig` attribute using cluster upgrade

### ISSUE THREAD

**Issue by mothman-aws** [aws/eks-anywhere#7108]
**What would you like to be added**:
update the service-account-issuer attribute of a running EKSA cluster. Currently, this attribute can be changed only during the cluster creation time using the cluster configuration "podIamConfig". However, the changes aren't applied using the "eksctl anywhere cluster upgrade" command.

**Why is this needed**:
Changing this attribute is essential for IRSA implementation and the integration with an external IdP, which is not straightforward to do for the existing and running clusters. it's not an option for many customers to delete the existing clusters and create new clusters w/ podIamConfig attribute. Our customers want to change this attribute using the cluster upgrade command.

**Comment by azN2** [comment]
Is it possible to upgrade service-account-issuer attribute of a running EKSA cluster for vsphere cluster with 0.18.3

**Comment by jiayiwang7** [comment]
> Is it possible to upgrade service-account-issuer attribute of a running EKSA cluster for vsphere cluster with 0.18.3

yes.
