### ISSUE TITLE
Packages issues when using registry mirror

### ISSUE THREAD

**Issue by tatlat** [aws/eks-anywhere#7114]
**Issues**:
Registry mirror CA Certificate used in curated package does not update after cluster upgrade with registryMirrorConfig change.
Cannot enable/install curated packages on workload clusters when using a registry mirror

**What happened**:

When updating the caCertContent of a registry mirror configuration of a management cluster, the new certificate was not properly propagated to the packages controller, which led to errors when installing packages due to it using the old certificate. Additionally, packages were not being enabled on newly created workload clusters with registry mirror configs due to the same certificate propagation issue. 

The packages controller gets the CA certificate from 2 secrets: registry-mirror-secret and registry-mirror-cred. The latter gets its data from the former secret. For management clusters, the registry-mirror-secret secret is created in the eksa-packages namespace whereas it is created in `eksa-packages-<clusterName>` for workload clusters. The latter secret is in the eksa-packages namespace and contains the CA certificates for each cluster as `<clusterName>_ca.crt`. After creating clusters named mgmt and worker, the `registry-mirror-cred` secret contained `mgmt_ca.crt` but did not contain `worker_ca.crt`. The `registry-mirror-secret` secrets for both clusters contained the default values as seen below.
```
data:
    CACERTCONTENT: ""
    ENDPOINT: ""
    INSECURE: ZmFsc2UK
    PASSWORD: ""
    USERNAME: ""
```

It seems that registry-mirror-secret receives its data from a helm chart. The EKS-Anywhere controller overrides the default values of the helm chart when enabling packages, which is usually triggered by the CLI when creating a cluster or by the EKS-Anywhere controller as a post reconcile task. However, a new eks-anywhere-packages pod was being rolled out shortly after enabling packages without re-overriding the default values. As a result, `registry-mirror-secret` briefly contains the correct registry data, but loses that data when a new packages pod rolls out. For workload clusters, the `registry-mirror-secret` secret never contains the correct registry data at any point.

Further investigation of the eks-anywhere-packages repo suggests that registry-mirror-secret is only used to fill registry-mirror-cred. 

**What you expected to happen**:

Upgrading a management or workload's cluster CA certificate would also update the certificate used by curated packages. 
To be able to create workload clusters that use registry mirrors and still use curated packages.

**How to reproduce it (as minimally and precisely as possible)**:

Create a registry mirror.
Successfully create a mgmt cluster with correct registry mirror configuration and packages enabled.
Successfully create a workload cluster with the same registry mirror configuration. It should error out when installing/enabling packages. 
Update the CA cert for the registry mirror.
Upgrade the management cluster by changing the `caCertContent` in the `registryMirrorConfig`.
Try to install any package.

**Anything else we need to know?**:

This issue should be fixed with this PR: 
https://github.com/aws/eks-anywhere/pull/7115

**Environment**:
- EKS Anywhere Release: v0.18.1

**Comment by drewvanstone** [comment]
Next steps
- [ ] Need Patch operations in kubectl clients 
- [ ] Replace the apply operations with patch

Estimated effort: 3-5 days
