### ISSUE TITLE
EKS anywhere AMI 

### ISSUE THREAD

**Issue by yanivpaz** [aws/eks-anywhere#713]
**What would you like to be added**: prebuilt AMI with EKS anywhere installed on AML2

**Why is this needed**: to reduce the deployment  time and automate all the related installation requirements

**Comment by jaxesn** [comment]
Thanks for the suggestion!  You are thinking about an AMI with the eks-a cli and docker preinstalled to make it easy to spin up an admin machine to be used for creating eks-a clusters on vsphere (or future infrastructure providers supported by eks-a)?

**Comment by yanivpaz** [comment]
@jaxesn  I am thinking on all in one ec2 instance with all the required kubernetes tools and stand-alone EKS cluster.
so once the EC2 is provisioned, I can 
1) login to the EC2 and run 
```
helm install hello-world"
```
2) open browser and see hello world message in the relevant URL
