### ISSUE TITLE
Only 1 worker VM booted successfully (others stuck) when ubuntu EFI boot is enabled

### ISSUE THREAD

**Issue by ygao-armada** [aws/eks-anywhere#7147]
**What happened**:
Only 1 worker VM passes boot

**What you expected to happen**:
All worker VMs pass boot

**How to reproduce it (as minimally and precisely as possible)**:
Just use EFI boot enabled template to provision the EKS cluster worker nodes

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release: v0.18.0
- EKS Distro Release: 0.164.0-dev

**Comment by vignesh-goutham** [comment]
Hello @ygao-armada, can you get an output of `kubectl get machines -n eksa-system` to check what the status of the machine is. Also trying to understand the issue here, did the VM fail to boot or did it fail to bootstrap into the cluster? If its the former, can you also get the output of `kubectl get workflows.tinkerbell.org -n eksa-system`

**Comment by ygao-armada** [comment]
Hell @vignesh-goutham thanks for your advice:

```
ubuntu@ubuntuguest:~$ kubectl get nodes
NAME                      STATUS     ROLES           AGE     VERSION
mgmt20-gn76z              Ready      control-plane   3d21h   v1.28.2-eks-28c5e82
mgmt20-hmr4s              Ready      control-plane   3d20h   v1.28.2-eks-28c5e82
mgmt20-md-0-swkm9-98hvf   NotReady   <none>          3d20h   v1.28.2-eks-28c5e82
mgmt20-md-0-swkm9-wcnfr   Ready      <none>          3d17h   v1.28.2-eks-28c5e82
```
The machine stuck at booting, I think.

It's EKS anywhere on vShpere, so tinkerbell may not get involved.

Actually, I even can NOT create a VM against ubuntu (even with EFI boot disabled) with the vcenter UI, however, it's fine to create VM against bottlerocket.

So maybe something wrong with ubuntu specific.

**Comment by vignesh-goutham** [comment]
Sorry, it looks like the vm did boot though, otherwise the it wouldnt be showing up in the get nodes output. Can we also get a `kubectl get machines -n eksa-system` to identify what state the vm is at?

**Comment by ygao-armada** [comment]
Actually, what happened was like this:
At first, VM "mgmt20-md-0-swkm9-98hvf" was booted and the rest 2 VMs stuck, as cause the cluster creation times out.
Later, when I tried to power off/on VM "mgmt20-md-0-swkm9-98hvf", another VM "mgmt20-md-0-swkm9-wcnfr" took the only boot seat.
Thus we see:
```
ubuntu@ubuntuguest:~$ kubectl get nodes
NAME                      STATUS     ROLES           AGE     VERSION
mgmt20-gn76z              Ready      control-plane   4d3h    v1.28.2-eks-28c5e82
mgmt20-hmr4s              Ready      control-plane   4d3h    v1.28.2-eks-28c5e82
mgmt20-md-0-swkm9-98hvf   NotReady   <none>          4d3h    v1.28.2-eks-28c5e82
mgmt20-md-0-swkm9-wcnfr   Ready      <none>          3d23h   v1.28.2-eks-28c5e82
```

There is no space "eksa-system", maybe due to timeout mentioned above:
```
ubuntu@ubuntuguest:~$ kubectl get namespaces
NAME              STATUS   AGE
default           Active   4d3h
gpu-operator      Active   3d21h
kube-node-lease   Active   4d3h
kube-public       Active   4d3h
kube-system       Active   4d3h
```

**Comment by ygao-armada** [comment]
Look like it's related to https://askubuntu.com/questions/1408621/ubuntu-22-04-ova-cloud-image-does-not-get-a-dhcp-ipv4-address-in-vsphere
