### ISSUE TITLE
Where is the source code to send the DHCPDISCOVER and DHCPREQUEST request during bare metal cluster creation

### ISSUE THREAD

**Issue by ygao-armada** [aws/eks-anywhere#7241]
Where is the source code to send the DHCPDISCOVER and DHCPREQUEST request when using eksctl anywhere to create a bare metal cluster (with tinkerbell as the provider) ?

**Comment by jacobweinstock** [comment]
Boots/Smee handles this. Select the branch for the version you're using and see this file for the Boots/Smee version: https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/tinkerbell/boots/GIT_TAG.
