### ISSUE TITLE
How to clean up everything of the messed up bare metal cluster

### ISSUE THREAD

**Issue by ygao-armada** [aws/eks-anywhere#7268]
If a EKS anywhere cluster (main cluster and a worker cluster) on bare metal gets messed up, and command "eksctl delete cluster ..." commands error out, how to clean up everything of the cluster?

For example, I see the information about mgmt cluster:
```
$ kubectl get clusters --kubeconfig mgmt03/mgmt03-eks-a-cluster.kubeconfig -A
NAMESPACE   NAME     AGE
default     mgmt03   4d12h

$ kubectl get nodes --kubeconfig mgmt03/mgmt03-eks-a-cluster.kubeconfig -A
NAME                   STATUS   ROLES           AGE     VERSION
eksa-main-control-01   Ready    control-plane   4d12h   v1.26.7
```

If I try to delete it, I will see error:
```
$ eksctl anywhere delete cluster mgmt03 --kubeconfig mgmt03/mgmt03-eks-a-cluster.kubeconfig
...
Analysis output generated	{"path": "mgmt03/generated/mgmt03-2024-01-07T07:04:43Z-analysis.yaml"}
Error: failed to delete cluster: getting the total count of nodes: getting KubeadmControlPlane for cluster mgmt03: getting kubeadmcontrolplane: Error from server (NotFound): kubeadmcontrolplanes.controlplane.cluster.x-k8s.io "mgmt03" not found
```

I try to delete the cluster by force (with null finalizers), however, the resources are still left on the hosts:

1. IPs are still in used (host IP, CP endpoint and tinkerbellIP)
2. host and pods are still running

The host is the only CP node.

**What shall I do**?

At the same time, I also have leftover in worker cluster, after I force delete the cluster and reboot the worker host from BMC, I see both machines.cluster.x-k8s.io and clusters.cluster.x-k8s.io are empty, however, the host IP still responds to fping ICMP request.

**How can I recycle the worker host IP** (before it was unreachable for fping)?

**Comment by cxbrowne1207** [comment]
**What should you do?** For a management (or main) cluster in this state, you simply need to power off the nodes being used. This should address the problem where the IPs are still in use, and then you can use those nodes to create a new functional cluster. If your workloads created external resources such as external DNS entries or load balancer endpoints you may need to delete those resources manually.

If your management cluster were in a good state and you were only trying to clean up a workload cluster, in addition to powering off those nodes in that cluster, you would need to manually cleanup it's leftover resources from the management cluster.

**How can I recycle the worker host IP (before it was unreachable for fping)** If I'm understanding your question right, currently the worker host IP is occupied and you want it to be unreachable when pinged. In this case, the answer would be to power off your BareMetal nodes as in the previous answer.

Did these answers address your questions?
