### ISSUE TITLE
Update Bare Metal provider optional configuration page

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#7270]
We need to update the outdated optional configuration list in the https://anywhere.eks.amazonaws.com/docs/getting-started/baremetal/bare-spec/ page. Right now only CNI and host OS config are listed. We need to verify all [other options](https://anywhere.eks.amazonaws.com/docs/getting-started/optional/) and update this list.

We should also call out how hardware.csv is used / passed when using GitOps/FLC.

**Comment by panktishah26** [comment]
Changes related to this issue are covered in this PR https://github.com/aws/eks-anywhere/pull/6538. Backported this to the release-0.18 branch https://github.com/aws/eks-anywhere/pull/7329.
