### ISSUE TITLE
Make Kubelet Configuration customizable

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#7708]
- [x] Design Review
- [x] Create cluster with custom Kubelet configuration
- [x] Upgrade cluster with custom Kubelet configuration
- [x] Write and Test Docker
- [x] Write and Test vSphere
- [x] Write and Test Cloudstack
- [x] Write and Test Tinkerbell
- [x] Write and Test Nutanix
- [x] Block setting `cloud-provider` and `provider-id` fields
- [x] Bottlerocket support - add patch on the CAPI side to introduce all the fields exposed for BR
- [x] e2e test

**Comment by csplinter** [comment]
Can we close this issue?
