### ISSUE TITLE
Add documentation providing step-by-step guidance to create a "management cluster" and a "workload cluster"

### ISSUE THREAD

**Issue by jaradtke-aws** [aws/eks-anywhere#7882]
**What would you like to be added**:
Working backwards from the goal of having a "management cluster" which manages a "workload cluster":
The steps/procedure to design and deploy the implementation pattern.

**Why is this needed**:
This implementation pattern (management + workload cluster) is supported and a recommended architecture.  The intent of adding this guidance is to provide an efficient path towards a successful implementation.

**Comment by chrisdoherty4** [comment]
Hi @jaradtke-aws. I think we have what you describe for each provider (E.g. https://anywhere.eks.amazonaws.com/docs/getting-started/vsphere/vsphere-getstarted/). Do you have some specifics on what you think is meeting?

**Comment by jaradtke-aws** [comment]
Hey @chrisdoherty4 
At first I was confused (myself) after I had your question.  After recalling why I opened this, I now realize I should have been more clear (which might change the scope of the ask).
I was going through this exercise starting with a Bare Metal cluster (and wanting to create a workload cluster managed by my BM cluster).
Additionally, I intend to create my "management cluster" on vSphere (long-lived) and then use my bare metal systems as my workload cluster.
The instructions in the vSphere specific section did clear things up for me though.
Is this a topic that is more "universal" or generic and possibly should be independent of a specific installation type?
Thanks!
