### ISSUE TITLE
Error importing helm charts for airgapped configuration using private registry certificates

### ISSUE THREAD

**Issue by rossh-iceway** [aws/eks-anywhere#7891]
**What happened**: 
When using `eksctl anywhere import images` on a registry with a private CA, 160 images are pushed successfully using docker, then helm is asked to log in, and fails due to not trusting the certificate of the registry.

This does complete successfully with `--insecure` on in the eksctl command line, so it's not preventing anything other than good practice.

<details><summary>Log snippet</summary>
<p>
<pre>
V0	Logging in to helm registry	{"registry": "registry.redacted.com"}
V6	Executing command	{"cmd": "/usr/bin/docker exec -i -e HELM_EXPERIMENTAL_OCI=1 -e HTTPS_PROXY= -e HTTP_PROXY= -e NO_PROXY= eksa_1711276022316141685 helm registry login registry.redacted.com --username  --password-stdin"}
V9	docker	{"stderr": "time=\"2024-03-24T10:27:57Z\" level=info msg=\"Error logging in to endpoint, trying next endpoint\" error=\"Get \\\"https://registry.redacted.com/v2/\\\": tls: failed to verify certificate: x509: certificate signed by unknown authority\"\nError: Get \"https://registry.redacted.com/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority\n"}
</pre>
</p>
</details> 

**What you expected to happen**:
The `import` command to complete without error.

**How to reproduce it (as minimally and precisely as possible)**:

- Configure a registry with a private CA
- Install private CA `.crt` in `/etc/docker/certs.d/<my-registry.com>/ca.crt` ([per this documentation](https://anywhere.eks.amazonaws.com/docs/getting-started/optional/registrymirror/#admin-machine-configuration))
- Follow [documentation airgapped procedure](https://anywhere.eks.amazonaws.com/docs/getting-started/airgapped/#procedure) as far as step 5.

The error will occur after the docker images are written to the registry.

**Anything else we need to know?**:

- My registry is serving on 443, so I have no port number in my `/etc/docker/certs.d/` folder entry. Before adding this entry the docker pushes immediately fail (as expected), so the helm parts are never reached.
- My registry has no authentication, but the eksctl anywhere import command errors unless `REGISTRY_USERNAME` is set. In my environment both `REGISTRY_USERNAME` and `REGISTRY_PASSWORD` are set to empty strings.
- I have also added the CA to the Admin Machine trusted authorities, with no change in behaviour.
- I attach my commands and the full output at `-v9` to this issue. 

**Environment**:
- Admin OS: Ubuntu 20.04.6
- eksctl version: 0.175.0
- eksctl-anywhere version: v0.19.1 (bundle 61)

[import.redacted.log](https://github.com/aws/eks-anywhere/files/14735251/import.redacted.log)

**Comment by chrisdoherty4** [comment]
@rossh-iceway Thanks for the info. We'll take a look asap.

**Comment by sp1999** [comment]
We have updated the [docs](https://anywhere.eks.amazonaws.com/docs/clustermgmt/cluster-upgrades/airgapped-upgrades/#:~:text=When%20using%20self%2Dsigned%20certificates%20for%20your%20registry%2C%20you%20should%20run%20with%20the%20%2D%2Dinsecure%20command%20line%20argument%20to%20indicate%20skipping%20TLS%20verification%20while%20pushing%20helm%20charts%20and%20bundles.) to include the instructions about using `--insecure` flag when using self-signed certs for the registry.
