### ISSUE TITLE
image-builder build for ubuntu 22.04 baremetal failing with "qemu: Timeout waiting for SSH"

### ISSUE THREAD

**Issue by terry-hasegawa** [aws/eks-anywhere#7982]
**What happened**:

`image-builder build --os ubuntu --hypervisor baremetal --release-channel 1-29 --os-version 22.04`

is failing with:

```
==> qemu: Waiting for SSH to become available...
==> qemu: Timeout waiting for SSH.
==> qemu: Deleting output directory...
Build 'qemu' errored after 41 minutes 2 seconds: Timeout waiting for SSH.
```

**What you expected to happen**:

image-builder to successfully build ubuntu 22.04 for baremetal

**How to reproduce it (as minimally and precisely as possible)**:

Follow Build Bare Metal node images instructions for Ubuntu with --os-version 22.04:
[https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#build-bare-metal-node-images](https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#build-bare-metal-node-images)

**Anything else we need to know?**:

Here are some additional details from our build machine:

```
image-builder@ip-172-31-100-199:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
```

```
image-builder@ip-172-31-100-199:~$ /usr/bin/env bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Console log with error(build ubuntu **22.04** for bare metal):
[ubuntu22.04.txt](https://github.com/aws/eks-anywhere/files/14965530/ubuntu22.04.txt)

I have successfully built **ubuntu 20.04** for bare metal in the same environment.
`image-builder build --os ubuntu --hypervisor baremetal --release-channel 1-29 --os-version 20.04`

**Environment**:
- EKS Anywhere Release: v0.19.2

**Comment by Cajga** [comment]
@terry-hasegawa we had the same issue. The root cause is that the `apt update` fails on the original 22.04 ubuntu image.
The solution is to use a newer ubuntu image through baremetal.json (verify the image checksum as the image may have changed):
```
cat << EOF > baremetal.json
{
  "iso_url": "https://releases.ubuntu.com/jammy/ubuntu-22.04.4-live-server-amd64.iso",
  "iso_checksum": "45f873de9f8cb637345d6e66a583762730bbea30277ef7b32c9c3bd6700a32b2",
  "iso_checksum_type": "sha256"
}
EOF
```

And pass it like:
```
image-builder build --os ubuntu --hypervisor baremetal --release-channel 1-29 --os-version 22.04 --baremetal-config baremetal.json
```

**Comment by terry-hasegawa** [comment]
Hi @Cajga , Thank you, the 22.04 build is complete.
[ubuntu22.04v2.txt](https://github.com/aws/eks-anywhere/files/14983215/ubuntu22.04v2.txt)

**Comment by abhay-krishna** [comment]
The permanent [fix](https://github.com/aws/eks-anywhere-build-tooling/commit/eb68b5a080993d7a3fc54d7889dbff766dec79b6) for this issue has been included in the image-builder CLI that ships with EKS-A v0.19.4 and above. In general, we recommend upgrading the image-builder CLI as well whenever you upgrade the EKS-A CLI. Refer to the image-builder CLI installation [docs](https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#downloading-the-image-builder-cli) to download the latest CLI.
