### ISSUE TITLE
Update doc site to replace legacy ECR registry for accessing curated packages

### ISSUE THREAD

**Issue by jiayiwang7** [aws/eks-anywhere#8033]
After EKS-A GA'ed the [Self-Service Enterprise Subscription](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-eks-anywhere-self-service-enterprise-subscription-purchases/), we replace the legacy ECR with the new regional ECR repo to store all the curated packages images. Although many places in our doc site still point to the legacy ECR for configuring and using curated packages. We need to update them all and point users to use the regional ECR repo specified here: https://anywhere.eks.amazonaws.com/docs/clustermgmt/support/share-packages/#1-save-eks-anywhere-curated-packages-registry-account-for-your-subscription

**Comment by vivek-koppuru** [comment]
Need to replace all the doc references to this account: https://github.com/search?q=repo%3Aaws%2Feks-anywhere%20%20783794618700&type=code
