### ISSUE TITLE
VMware Resource pool not found

### ISSUE THREAD

**Issue by ronin201** [aws/eks-anywhere#856]
**What happened**:
I always receve the error resource pool not found. I have created different variations of resource pools in WMware. But the system maschine unable to find them. 

Performing setup and validations
Warning: VSphereDatacenterConfig configured in insecure mode
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
✅ Datastore validated
✅ Folder validated
❌ Validation failed    {"validation": "vsphere Provider setup is valid", "error": "error validating vCenter setup for VSphereMachineConfig SC-cp: resource pool 'AWS' not found", "remediation": ""}
✅ Create preflight validations pass

I had tried:
If there is no resource pool: /<datacenter>/host/<cluster-name>/Resources - same issue
If there is a resource pool: /<datacenter>/host/<cluster-name>/Resources/<resource-pool-name> -same issue
The wild card option */Resources also often works -same issue

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- EKS Anywhere Release:
- EKS Distro Release:

**Comment by abhinavmpandey08** [comment]
Hi @ronin201,

Thank you for opening the issue.
I would suggest installing the [`govc` command line utility](https://github.com/vmware/govmomi/blob/master/govc/README.md#installation) and set the following environment variables:
```bash
export GOVC_URL=<vsphere url>
export GOVC_USERNAME=<vsphere login username>
export GOVC_PASSWORD=<vsphere login password>
```
and then running `govc pool.info <ResourcePool Name>`. 
This command should print out the full path to the resource pool, if it exists. You can use this path in the cluster config file to then create the cluster.

Let me know if this works or if you have any other questions

**Comment by ronin201** [comment]
@abhinavmpandey08  Thank you it helps.

now system shows: panic: runtime error: slice bounds out of range [:7] with length 0
goroutine 1 [running]:
github.com/aws/eks-anywhere/pkg/providers/vsphere.(*vsphereProvider).defaultTemplateForClusterSpec(0xc00011dee0, 0xc00013f4d0, 0xc0007f0700, 0xc0006656ff, 0x1cec4e4)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/providers/vsphere/vsphere.go:858 +0x4a5
.... etc and stops

**Comment by abhinavmpandey08** [comment]
Can you describe where this issue is happening and what command you were running (create, delete, upgrade, something else). Also, can you post a few more lines of logs before and after you notice the error?

**Comment by ronin201** [comment]
@abhinavmpandey08 
the command:

eksctl anywhere create cluster -f eksa-mgmt-cluster.yaml

Performing setup and validations
Warning: VSphereDatacenterConfig configured in insecure mode
✅ Connected to server
✅ Authenticated to vSphere
✅ Datacenter validated
✅ Network validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
✅ Datastore validated
✅ Folder validated
✅ Resource pool validated
panic: runtime error: slice bounds out of range [:7] with length 0

goroutine 1 [running]:
github.com/aws/eks-anywhere/pkg/providers/vsphere.(*vsphereProvider).defaultTemplateForClusterSpec(0xc00009ea90, 0xc0001bb5f0, 0xc0000f1340, 0xc0007b36ff, 0x1cec4e4)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/providers/vsphere/vsphere.go:858 +0x4a5
github.com/aws/eks-anywhere/pkg/providers/vsphere.(*vsphereProvider).setupDefaultTemplate(0xc00009ea90, 0x1f03b68, 0xc000040078, 0xc0001bb5f0, 0xc0000f1340, 0xc000273620, 0x0, 0x0)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/providers/vsphere/vsphere.go:834 +0x49
github.com/aws/eks-anywhere/pkg/providers/vsphere.(*vsphereProvider).setupAndValidateCluster(0xc00009ea90, 0x1f03b68, 0xc000040078, 0xc0001bb5f0, 0x0, 0xc000652400)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/providers/vsphere/vsphere.go:624 +0x167d
github.com/aws/eks-anywhere/pkg/providers/vsphere.(*vsphereProvider).SetupAndValidateCreateCluster(0xc00009ea90, 0x1f03b68, 0xc000040078, 0xc0001bb5f0, 0x1, 0xc000518ba0)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/providers/vsphere/vsphere.go:877 +0x133
github.com/aws/eks-anywhere/pkg/workflows.(*SetAndValidateTask).providerValidation.func1(0xc000516108)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/workflows/create.go:190 +0x115
github.com/aws/eks-anywhere/pkg/validations.(*Runner).Run(0xc0007b3a60, 0xc000516108, 0x1)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/validations/runner.go:24 +0x52
github.com/aws/eks-anywhere/pkg/workflows.(*SetAndValidateTask).Run(0x2c28690, 0x1f03b68, 0xc000040078, 0xc00026c3c0, 0xe, 0x2)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/workflows/create.go:166 +0x378
github.com/aws/eks-anywhere/pkg/task.(*taskRunner).RunTask(0xc0007b3ba8, 0x1f03b68, 0xc000040078, 0xc00026c3c0, 0x0, 0x0)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/task/task.go:126 +0x2e2
github.com/aws/eks-anywhere/pkg/workflows.(*Create).Run(0xc0007b3c78, 0x1f03b68, 0xc000040078, 0xc0001bb5f0, 0x1ec7940, 0xc000114388, 0xc0001bb500, 0x0, 0x0)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/pkg/workflows/create.go:60 +0x191
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.(*createClusterOptions).createCluster(0x2bf82a0, 0x1f03b68, 0xc000040078, 0x0, 0x0)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/cmd/eksctl-anywhere/cmd/createcluster.go:128 +0x465
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.glob..func1(0x2bc8fa0, 0xc0004040e0, 0x0, 0x2, 0x0, 0x0)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/cmd/eksctl-anywhere/cmd/createcluster.go:37 +0x93
github.com/spf13/cobra.(*Command).execute(0x2bc8fa0, 0xc0004040c0, 0x2, 0x2, 0x2bc8fa0, 0xc0004040c0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x2bc8320, 0x8, 0xc000000180, 0x1897525)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/aws/eks-anywhere/cmd/eksctl-anywhere/cmd.Execute(0x0, 0x0)
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/cmd/eksctl-anywhere/cmd/root.go:43 +0x53
main.main()
        /codebuild/output/src446545835/src/git-codecommit.us-west-2.amazonaws.com/v1/repos/aws.eks-anywhere/cmd/eksctl-anywhere/main.go:29 +0xe5

**Comment by abhinavmpandey08** [comment]
Can you also share your clusterconfig file `eksa-mgmt-cluster.yaml`?

**Comment by ronin201** [comment]
[Yamlconfig.txt](https://github.com/aws/eks-anywhere/files/7764575/Yamlconfig.txt)
Pls see config

**Comment by abhinavmpandey08** [comment]
For `osFamily` in the clusterconfig, you need to say `ubuntu` in lowercase
```yaml
  osFamily: "ubuntu"
```
I have opened a new issue to fix this https://github.com/aws/eks-anywhere/issues/875

**Comment by ronin201** [comment]
Thank you everything works! can you pls put this info in official guid if possible

**Comment by abhinavmpandey08** [comment]
It is mentioned in the [docs](https://anywhere.eks.amazonaws.com/docs/reference/clusterspec/vsphere/#osfamily-optional) already but we can make it more obvious.
 
Thanks for reporting the issue @ronin201! I'm going to close this issue now and the osFamily issue will be tracked in this ticket #875. Feel free to re-open if you have any further questions
