### ISSUE TITLE
building os image for bare metal

### ISSUE THREAD

**Issue by Mani-tailwinds** [aws/eks-anywhere#8573]
i need a help to build a ubuntu os image for tinkerbell and assign it to the config file. anyone guide me ?

**Comment by Cajga** [comment]
Have you read the documentation: https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#building-node-images

**Comment by abhay-krishna** [comment]
@Mani-tailwinds Refer to the image-builder CLI documentation for bare metal images [here](https://anywhere.eks.amazonaws.com/docs/osmgmt/artifacts/#build-bare-metal-node-images).

Once you have built the image, you can host it at an accessible location and specify the hosted image in the `osImageUrl` field in the [Tinkerbell cluster spec](https://anywhere.eks.amazonaws.com/docs/getting-started/baremetal/bare-spec/).

**Comment by abhay-krishna** [comment]
Feel free to re-open this issue or create a new issue if you have any additional questions.

**Comment by thecloudgarage** [comment]
You can read my blog for this purpose https://medium.com/@ambar-thecloudgarage/eks-anywhere-creating-ubuntu-22-04-os-images-for-bare-metal-clusters-2b23fd460ecf
