### ISSUE TITLE
New workload cluster creation stuck

### ISSUE THREAD

**Issue by ronin201** [aws/eks-anywhere#883]
New workload cluster creation stuck

No VM created

Capv logs
[logs.txt](https://github.com/aws/eks-anywhere/files/7773288/logs.txt)

**Comment by ronin201** [comment]
Problem solved, reason: network in cluster.yaml must be named as existing Vnet in Vsphere (IP addresses are not allowed!!! fo example 192.168.0.0/24)

**Comment by vivek-koppuru** [comment]
Hi @ronin201, thanks for reporting this issue. May I ask which field you are referring to in the cluster.yaml file?

**Comment by ronin201** [comment]
@vivek-koppuru 
Hello!

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: DC_name
spec:
  datacenter: "Name_DC"
    network: "Name_network!!!" - here, IP address pool is not allowed

I found it during installation with details (eksctl anywhere create... --v5), sytem report network was not found!, but the status was validated! pls check

**Comment by vivek-koppuru** [comment]
Thanks for the information @ronin201. However, I am not able to replicate it locally. What version of the binary are you running? You can run `eksctl anywhere version` to check that. The latest version we have right now is `v0.6.1`.

We currently validate the network here, so just want to check how you are able to see that it gets past the validation step: https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/validator.go#L362

**Comment by ronin201** [comment]
1) yes the latest version 0.6.1
2) eksctl anywhere create cluster.yml - f --v5

**Comment by vivek-koppuru** [comment]
Hey @ronin201, can you show me the CLI output with that error you were talking about? Want to see what is showing up. For your yaml file, it failed when you specified `192.168.0.0/24` in your spec file right? When I try to replicate it locally, I am getting the following validation error like it should:

```
[ec2-user@ip-172-31-8-141 ~]$ ./eksctl-anywhere create cluster -f cluster2.yaml 
Performing setup and validations
✅ Connected to server
✅ Authenticated to vSphere
Warning: VSphereMachineConfig MemoryMiB for etcd machines should not be less than 8192. Defaulting to 8192
Warning: Your VM template includes snapshot(s). LinkedClone mode will be used. DiskGiB cannot be customizable as disks cannot be expanded when using LinkedClone mode. Using default of 25 for DiskGiBs.
Warning: Your VM template includes snapshot(s). LinkedClone mode will be used. DiskGiB cannot be customizable as disks cannot be expanded when using LinkedClone mode. Using default of 25 for DiskGiBs.
✅ Datacenter validated
❌ Validation failed	{"validation": "vsphere Provider setup is valid", "error": "failed checking '24' network", "remediation": ""}
✅ Validate taints support
✅ Create preflight validations pass
```

**Comment by ronin201** [comment]
Thank you! the issue is  closed
