### ISSUE TITLE
EKS Anywhere cluster registration on AWS portal

### ISSUE THREAD

**Issue by ronin201** [aws/eks-anywhere#889]
**What happened**:   After adding cluster to portal the error displays:  Error loading Namespaces
users "arn:aws:iam::496586270756:user/aws_<name>_admin" is forbidden: User "system:serviceaccount:eks-connector:eks-connector" cannot impersonate resource "users" in API group "" at the cluster scope. 

what does it mean? Should I customize additional user and where?

**Comment by g-gaston** [comment]
EKS Connector is not an EKS Anywhere specific feature. It is know to work with EKS Anywhere but please see the support page for EKS Connector or contact support for assistance.
