### ISSUE TITLE
Remove lock for etcd machines if underlying machine is deleted

### ISSUE THREAD

**Issue by vivek-koppuru** [aws/eks-anywhere#8906]
If etcd controller is rolling out new nodes for external etcd, there is a deadlock scenario where the lock is waiting for another machine to initialize even though the underlying machine got deleted for a transient issue. 

https://github.com/aws/etcdadm-bootstrap-provider/blob/main/internal/locking/locking.go#L58

We need to fix this by checking if the machine exists to be able to remove the lock and have it reconcile normally.

**Comment by rahulbabu95** [comment]
https://github.com/aws/etcdadm-bootstrap-provider/pull/41 should fix this deadlock issue.
