### ISSUE TITLE
How to clean created resources when installation failed in mid of creation (3-etcd 1 CP was created )

### ISSUE THREAD

**Issue by DINESHKUMAR-DK** [aws/eks-anywhere#910]
status and cluster info:
    The management cluster is running properly with its nodes.
    I am using k8s versions 1.21, and I can use management cluster kubeconfig to access resource 
    Vsphere version 7 +

Issue:

I tried to create a workload cluster using the management cluster, but it failed in the step of "Waiting for control plan to be ready"
and till creation time 3-Etcd & 1 control plane was created. But the kubeconfig file was not created yet. Node still running on the Vsphere and how I can delete it because kubeconfig is not available for that this workload cluster.

I tried to delete the machine; it automatically created a new machine.
I cannot execute the delete cluster command because kubeconfig was not generated for the workload cluster.
I can see all the machines using management cluster kubeconfig credentials and tried to delete but again it will create a new one.

Can someone know how to clean failed creation cluster resources from the management cluster
or any suggestion if you have, please comment

**Comment by TerryHowe** [comment]
In theory, if you supplied a valid ssh public key, you could ssh into the control plane and get the kubeconfig.

It sounds like the management cluster was moved successfully to the workload cluster. I'm a little surprised it didn't get the kubeconfig.

Either way, to get rid of a cluster, you just need to remove the control plane and worker nodes quickly enough so CAPV doesn't have a chance to recreate them. The easiest way to do that would be using the govc command line tool for example `govc vm.destroy <vm-path>` You can also do this through the vSphere web ui.

**Comment by abhinavmpandey08** [comment]
When a cluster creation fails, it leaves behind a [kind](https://kind.sigs.k8s.io/) cluster. To delete this, you can either install kind and run `kind delete cluster <cluster-name>` or delete it using docker by getting the container ID using `docker ps` and then `docker rm -f <container-id>`.

After the kind cluster is deleted, you can go ahead and delete the VMs like Terry mentioned in the comment above.

**Comment by joe2709** [comment]
I have the same problem, That is resolved to remove cluster resources in management cluster as below

- kubectl get machine -A --kubeconfig mgmt/mgmt-eks-a-cluster.kubeconfig | grep workload04
NAMESPACE     NAME                               PROVIDERID                                       PHASE          VERSION
eksa-system   workload04-etcd-xs899                                                               Provisioning   
eksa-system   workload04-md-0-5597ff4896-j2f5v                                                    Pending        v1.20.7-eks-1-20-8

That can be deleted using kubectl command 
- kubectl delete -f cluster.yaml  

You can find cluster.yaml file in "{target_cluster_name}/geneated" directory as below.
- workload04/generated/workload04-eks-a-cluster.yaml

[example]
 - kubectl delete -f workload04/generated/workload04-eks-a-cluster.yaml --kubeconfig {mgmt_cluster_name}/{mgmt_cluster_name}-eks-a-cluster.kubeconfig

-  kubectl delete -f workload04/generated/workload04-eks-a-cluster.yaml --kubeconfig mgmt/mgmt-eks-a-cluster.kubeconfig 
cluster.cluster.x-k8s.io "workload04" deleted
vspherecluster.infrastructure.cluster.x-k8s.io "workload04" deleted
vspheremachinetemplate.infrastructure.cluster.x-k8s.io "workload04-control-plane-template-1646392793738" deleted
kubeadmcontrolplane.controlplane.cluster.x-k8s.io "workload04" deleted
clusterresourceset.addons.cluster.x-k8s.io "workload04-crs-0" deleted
etcdadmcluster.etcdcluster.cluster.x-k8s.io "workload04-etcd" deleted
vspheremachinetemplate.infrastructure.cluster.x-k8s.io "workload04-etcd-template-1646392793738" deleted
secret "vsphere-csi-controller" deleted
configmap "vsphere-csi-controller-role" deleted
configmap "vsphere-csi-controller-binding" deleted
configmap "csi.vsphere.vmware.com" deleted
configmap "vsphere-csi-node" deleted
configmap "vsphere-csi-controller" deleted
configmap "internal-feature-states.csi.vsphere.vmware.com" deleted
kubeadmconfigtemplate.bootstrap.cluster.x-k8s.io "workload04-md-0" deleted
vspheremachinetemplate.infrastructure.cluster.x-k8s.io "workload04-worker-node-template-1646392793740" deleted
Error from server (NotFound): error when deleting "workload04/generated/workload04-eks-a-cluster.yaml": machinedeployments.cluster.x-k8s.io "workload04-md-0" not found

Then, that machine will be deleted and It won't be creating a new machine of target_cluster anymore.
