### ISSUE TITLE
Allow configurable docker.sock location

### ISSUE THREAD

**Issue by jonrichards** [aws/eks-anywhere#916]
**What would you like to be added**:

Currently, `eks-anywhere` hardcodes the expected `docker.sock` location to `/var/run/docker.sock`. This is fine as a default, but it is not the only location that the docker socket may be present on a system. It would be preferred if `eks-anywhere` honored `$DOCKER_HOST` if set instead of only supporting `/var/run/docker.sock`.

**Why is this needed**:

Enabling this allows `eks-anywhere` to be flexible across different environment needs.

**Comment by jaxesn** [comment]
Thanks for the request! We'll track interest on the ticket and see about pulling this up.
