### ISSUE TITLE
Support bundle improvements

### ISSUE THREAD

**Issue by jaxesn** [aws/eks-anywhere#92]
The current support bundle functionality can pull relevant pod logs and analyze the current state of the cluster.  We should improve the gathered data to better support debugging failures via the support bundle.

- [x] #123
- [x] #188
- [x] #238
- [x] #263
- [x] #243

**Comment by danbudris** [comment]
opened an issue with replicated regarding the import issues we've seen with the latest troublshoot go package

https://github.com/replicatedhq/troubleshoot/issues/416

**Comment by danbudris** [comment]
> opened an issue with replicated regarding the import issues we've seen with the latest troublshoot go package
> 
> [replicatedhq/troubleshoot#416](https://github.com/replicatedhq/troubleshoot/issues/416)

merged to main; next time we update the ts version in the bundle, we'll be able to take advantage of this improved output formatting.
