### ISSUE TITLE
Reused machine-id causing duplicate IP address allocations

### ISSUE THREAD

**Issue by EGmhenze** [aws/eks-anywhere#940]
Using the provided Ubuntu 20.04 OVA on the artifacts page found here: https://anywhere.eks.amazonaws.com/docs/reference/artifacts/

All VMs being cloned have the same DHCP address. Cluster deployment fails as a result. 

VMware KB to the behavior with Ubuntu VMs: https://kb.vmware.com/s/article/82229

Steps to reproduce: 
Import OVA from artifacts page
snapshot then convert to template
specify template in deployment YAML file (do not use content library mechanism)
run cluster creation command
Observe ETCD machines pulling the same DHCP address leading to a failed deployment

**Environment**:
- EKS Anywhere Release: 1.21
- EKS Distro Release: 6

**Comment by TerryHowe** [comment]
Interesting. I haven't heard of that happening before. Do they have unique mac addresses?

**Comment by EGmhenze** [comment]
Different MAC addresses. I just tested it again and got three unique MACs but the same IP. It's infinitely repeatable in my environment. Presumably, when you use the content library-style deployment there is an entry that is stripping the machine-id out as evidenced by "INFO: clearing and regenerating /etc/machine-id" in deployment logs. But this does NOT happen when you specify a template in the deployment.

**Comment by abhinavmpandey08** [comment]
Hi @EGmhenze, so I checked with the team and the OVAs we provide do have blank `/etc/machine-id`. This gets populated when Ubuntu boots up. The only times we have seen this issue in the past is when someone powers on the vm, makes some changes and then uses this as a template to clone newer VMs.

Could you try importing a fresh OVA to your environment and convert it to a template without powering it on first and see if you still get the same issue?

**Comment by EGmhenze** [comment]
That did it! During troubleshooting with my TAM we powered it on to check connectivity and make changes (customize the OVA) and then ran into this problem. Seems like a one-liner in the documentation about customizing the OVA and then running through those steps would make this more straight forward.
