### ISSUE TITLE
Flux (GitOps): Support Managed Github Repositories

### ISSUE THREAD

**Issue by samueljmello** [aws/eks-anywhere#950]
**What would you like to be added**:
Flux supports custom URLs under the CRD "GitRepository" declaration "spec.url". Unfortunately, EKS-Anywhere does not and tries to authenticate against Github's public facing site. Requesting support be added for on-prem (managed) Github instances.

**Why is this needed**:
Many companies do not allow external Github use, and therefore private Github becomes a necessity. Additionally, Git providers (like Gitlab, etc.) would also be supported if this is enabled.

**Comment by jaxesn** [comment]
In the 0.9 release we added "byo git" support which you should be able to use to work with github enterprise vs github saas.
