### ISSUE TITLE
"Bring your own Registry" support

### ISSUE THREAD

**Issue by jaxesn** [aws/eks-anywhere#98]
Currently we pull all container images from public.ecr to make it easier for users who prefer to limit outgoing traffic.  Some users would prefer having a local registry, such as Harbor, to avoid pulling the images from the internet for every node.  This becomes increasingly more important as cluster size increases.

- [x] Allow local registry configuration via cluster spec
- [x] Provide script/subcommand to download all images from a given release manifest and push to local registry
- [x]  capi patch to pass registry mirror config to bottlerocket user-data (@abhinavmpandey08). A PR for this is already open: Add capi patch for bottlerocket registry mirror support eks-anywhere-build-tooling#41
- [x] Update the deployment template to pass mirror config for br based on the capi patch (@abhinavmpandey08)
- [x] etcd changes to add registry mirror settings to bottlerocket etcd nodes (@mrajashree)
- [x] CAPI patch to fix BR proxy template error (@mrajashree)
- [ ] e2e test for testing registry mirror
- [x] docs update to reflect the changes (@mdsgabriel)

High level instructions which beta users were able to use to manually support this workflow:

1. Convert the ova template to a VM 
2. Power on the VM and get shell access. The easiest way of doing this is by resetting the VM a few times until you get to the GRUB menu and then boot into recovery mode (Advanced options for Ubuntu -> recovery mode -> Drop to root shell prompt). 
3. Append the following section to the /etc/containerd/config.toml file.   Make sure to replace “<YOUR-LOCAL-REGISTRY-ENDPOINT>” with your container registry endpoint
      ```
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."public.ecr.aws"]
          endpoint = ["https://<YOUR-LOCAL-REGISTRY-ENDPOINT>"]
        [plugins."io.containerd.grpc.v1.cri".registry.configs."<YOUR-LOCAL-REGISTRY-ENDPOINT>".tls]
          insecure_skip_verify = true
      ```
4. If you want you use tls verification, you can follow the steps listed herehttps://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-tls-communication
5. Save the file and power off the VM 
6. Convert the ova back to a template and use this modified template in your clusterconfig yaml

**Comment by abhinavmpandey08** [comment]
What still needs to be done:
- [ ] capi patch to pass registry mirror config to bottlerocket user-data (@abhinavmpandey08). A PR for this is already open: https://github.com/aws/eks-anywhere-build-tooling/pull/41
- [ ] Update the [deployment template](https://github.com/aws/eks-anywhere/blob/main/pkg/providers/vsphere/config/template.yaml) to pass mirror config for br based on the capi patch (@abhinavmpandey08) 
- [ ] etcd changes to add registry mirror settings to bottlerocket etcd nodes (@mrajashree)
- [ ] e2e test for testing registry mirror
- [ ] docs update to reflect the changes
